# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi_vs_v.0.4\forms\fmChangeVirtPribors.ui'
#
# Created: Wed Apr 15 17:31:23 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmChangeVirtPribors(object):
    def setupUi(self, fmChangeVirtPribors):
        fmChangeVirtPribors.setObjectName(_fromUtf8("fmChangeVirtPribors"))
        fmChangeVirtPribors.resize(907, 723)
        self.centralwidget = QtGui.QWidget(fmChangeVirtPribors)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.lwCh = QtGui.QListWidget(self.centralwidget)
        self.lwCh.setMinimumSize(QtCore.QSize(439, 131))
        self.lwCh.setMaximumSize(QtCore.QSize(439, 131))
        self.lwCh.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lwCh.setObjectName(_fromUtf8("lwCh"))
        self.verticalLayout.addWidget(self.lwCh)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tbAddAutoSearch = QtGui.QToolButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbAddAutoSearch.setFont(font)
        self.tbAddAutoSearch.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbAddAutoSearch.setArrowType(QtCore.Qt.NoArrow)
        self.tbAddAutoSearch.setObjectName(_fromUtf8("tbAddAutoSearch"))
        self.gridLayout.addWidget(self.tbAddAutoSearch, 0, 0, 1, 1)
        self.tbDelCh_2 = QtGui.QToolButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDelCh_2.setFont(font)
        self.tbDelCh_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbDelCh_2.setArrowType(QtCore.Qt.NoArrow)
        self.tbDelCh_2.setObjectName(_fromUtf8("tbDelCh_2"))
        self.gridLayout.addWidget(self.tbDelCh_2, 0, 1, 1, 1)
        self.tbAutoSearch = QtGui.QToolButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbAutoSearch.setFont(font)
        self.tbAutoSearch.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbAutoSearch.setArrowType(QtCore.Qt.NoArrow)
        self.tbAutoSearch.setObjectName(_fromUtf8("tbAutoSearch"))
        self.gridLayout.addWidget(self.tbAutoSearch, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_16.addLayout(self.verticalLayout)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lbl1_8 = QtGui.QLabel(self.groupBox)
        self.lbl1_8.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_8.setFont(font)
        self.lbl1_8.setLineWidth(-5)
        self.lbl1_8.setObjectName(_fromUtf8("lbl1_8"))
        self.verticalLayout_2.addWidget(self.lbl1_8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.leIndexMess = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leIndexMess.setFont(font)
        self.leIndexMess.setObjectName(_fromUtf8("leIndexMess"))
        self.horizontalLayout.addWidget(self.leIndexMess)
        self.tbChangeCh = QtGui.QToolButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbChangeCh.setFont(font)
        self.tbChangeCh.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbChangeCh.setArrowType(QtCore.Qt.NoArrow)
        self.tbChangeCh.setObjectName(_fromUtf8("tbChangeCh"))
        self.horizontalLayout.addWidget(self.tbChangeCh)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.lbl1_9 = QtGui.QLabel(self.groupBox)
        self.lbl1_9.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_9.setFont(font)
        self.lbl1_9.setLineWidth(-5)
        self.lbl1_9.setObjectName(_fromUtf8("lbl1_9"))
        self.verticalLayout_2.addWidget(self.lbl1_9)
        self.lwChInMess = QtGui.QListWidget(self.groupBox)
        self.lwChInMess.setMaximumSize(QtCore.QSize(409, 78))
        self.lwChInMess.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lwChInMess.setObjectName(_fromUtf8("lwChInMess"))
        self.verticalLayout_2.addWidget(self.lwChInMess)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_16.addWidget(self.groupBox)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lbl1_13 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_13.setFont(font)
        self.lbl1_13.setLineWidth(-5)
        self.lbl1_13.setObjectName(_fromUtf8("lbl1_13"))
        self.horizontalLayout_2.addWidget(self.lbl1_13)
        self.lePortNum = QtGui.QLineEdit(self.centralwidget)
        self.lePortNum.setMaximumSize(QtCore.QSize(51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lePortNum.setFont(font)
        self.lePortNum.setObjectName(_fromUtf8("lePortNum"))
        self.horizontalLayout_2.addWidget(self.lePortNum)
        spacerItem = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.tbSavePortNum = QtGui.QToolButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbSavePortNum.setFont(font)
        self.tbSavePortNum.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbSavePortNum.setArrowType(QtCore.Qt.NoArrow)
        self.tbSavePortNum.setObjectName(_fromUtf8("tbSavePortNum"))
        self.horizontalLayout_2.addWidget(self.tbSavePortNum)
        spacerItem1 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.tbParam = QtGui.QToolButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbParam.setFont(font)
        self.tbParam.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbParam.setArrowType(QtCore.Qt.NoArrow)
        self.tbParam.setObjectName(_fromUtf8("tbParam"))
        self.horizontalLayout_2.addWidget(self.tbParam)
        self.verticalLayout_17.addLayout(self.horizontalLayout_2)
        self.gridLayout_5.addLayout(self.verticalLayout_17, 0, 0, 1, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(437, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_15.addWidget(self.label_2)
        self.lwVIns = QtGui.QListWidget(self.centralwidget)
        self.lwVIns.setMinimumSize(QtCore.QSize(439, 129))
        self.lwVIns.setMaximumSize(QtCore.QSize(439, 129))
        self.lwVIns.setObjectName(_fromUtf8("lwVIns"))
        self.verticalLayout_15.addWidget(self.lwVIns)
        self.verticalLayout_7.addLayout(self.verticalLayout_15)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.lbl1_7 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_7.setFont(font)
        self.lbl1_7.setLineWidth(-5)
        self.lbl1_7.setObjectName(_fromUtf8("lbl1_7"))
        self.verticalLayout_14.addWidget(self.lbl1_7)
        self.cbTypeVPribor = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTypeVPribor.sizePolicy().hasHeightForWidth())
        self.cbTypeVPribor.setSizePolicy(sizePolicy)
        self.cbTypeVPribor.setEditable(False)
        self.cbTypeVPribor.setObjectName(_fromUtf8("cbTypeVPribor"))
        self.verticalLayout_14.addWidget(self.cbTypeVPribor)
        self.gridLayout_4.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.lbl1_5 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_5.setFont(font)
        self.lbl1_5.setLineWidth(-5)
        self.lbl1_5.setObjectName(_fromUtf8("lbl1_5"))
        self.verticalLayout_13.addWidget(self.lbl1_5)
        self.leIndexVPribor = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leIndexVPribor.sizePolicy().hasHeightForWidth())
        self.leIndexVPribor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leIndexVPribor.setFont(font)
        self.leIndexVPribor.setObjectName(_fromUtf8("leIndexVPribor"))
        self.verticalLayout_13.addWidget(self.leIndexVPribor)
        self.gridLayout_4.addLayout(self.verticalLayout_13, 0, 1, 1, 1)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.lbl1_10 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_10.setFont(font)
        self.lbl1_10.setLineWidth(-5)
        self.lbl1_10.setObjectName(_fromUtf8("lbl1_10"))
        self.verticalLayout_12.addWidget(self.lbl1_10)
        self.leParamVPribor = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leParamVPribor.sizePolicy().hasHeightForWidth())
        self.leParamVPribor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leParamVPribor.setFont(font)
        self.leParamVPribor.setObjectName(_fromUtf8("leParamVPribor"))
        self.verticalLayout_12.addWidget(self.leParamVPribor)
        self.gridLayout_4.addLayout(self.verticalLayout_12, 0, 2, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tbAddVPribor = QtGui.QToolButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbAddVPribor.setFont(font)
        self.tbAddVPribor.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbAddVPribor.setArrowType(QtCore.Qt.NoArrow)
        self.tbAddVPribor.setObjectName(_fromUtf8("tbAddVPribor"))
        self.horizontalLayout_7.addWidget(self.tbAddVPribor)
        self.tbChangeVPribor = QtGui.QToolButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbChangeVPribor.setFont(font)
        self.tbChangeVPribor.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbChangeVPribor.setArrowType(QtCore.Qt.NoArrow)
        self.tbChangeVPribor.setObjectName(_fromUtf8("tbChangeVPribor"))
        self.horizontalLayout_7.addWidget(self.tbChangeVPribor)
        self.tbDelVPribor = QtGui.QToolButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDelVPribor.setFont(font)
        self.tbDelVPribor.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbDelVPribor.setArrowType(QtCore.Qt.NoArrow)
        self.tbDelVPribor.setObjectName(_fromUtf8("tbDelVPribor"))
        self.horizontalLayout_7.addWidget(self.tbDelVPribor)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 1, 0, 1, 3)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lwChInVP = QtGui.QListWidget(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwChInVP.sizePolicy().hasHeightForWidth())
        self.lwChInVP.setSizePolicy(sizePolicy)
        self.lwChInVP.setMaximumSize(QtCore.QSize(401, 81))
        self.lwChInVP.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lwChInVP.setObjectName(_fromUtf8("lwChInVP"))
        self.verticalLayout_6.addWidget(self.lwChInVP)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lbl1_20 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_20.setFont(font)
        self.lbl1_20.setLineWidth(-5)
        self.lbl1_20.setObjectName(_fromUtf8("lbl1_20"))
        self.gridLayout_2.addWidget(self.lbl1_20, 0, 0, 1, 1)
        self.lbl1_19 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_19.setFont(font)
        self.lbl1_19.setLineWidth(-5)
        self.lbl1_19.setObjectName(_fromUtf8("lbl1_19"))
        self.gridLayout_2.addWidget(self.lbl1_19, 0, 1, 1, 1)
        self.cbChInVPType = QtGui.QComboBox(self.groupBox_7)
        self.cbChInVPType.setEditable(False)
        self.cbChInVPType.setObjectName(_fromUtf8("cbChInVPType"))
        self.gridLayout_2.addWidget(self.cbChInVPType, 1, 0, 1, 1)
        self.cbChInVPModul = QtGui.QComboBox(self.groupBox_7)
        self.cbChInVPModul.setEditable(False)
        self.cbChInVPModul.setObjectName(_fromUtf8("cbChInVPModul"))
        self.gridLayout_2.addWidget(self.cbChInVPModul, 1, 1, 1, 1)
        self.lbl1_22 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_22.setFont(font)
        self.lbl1_22.setLineWidth(-5)
        self.lbl1_22.setObjectName(_fromUtf8("lbl1_22"))
        self.gridLayout_2.addWidget(self.lbl1_22, 2, 1, 1, 1)
        self.cbChInVPChannel = QtGui.QComboBox(self.groupBox_7)
        self.cbChInVPChannel.setEditable(False)
        self.cbChInVPChannel.setObjectName(_fromUtf8("cbChInVPChannel"))
        self.gridLayout_2.addWidget(self.cbChInVPChannel, 3, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tbAddChInVP = QtGui.QToolButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbAddChInVP.setFont(font)
        self.tbAddChInVP.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbAddChInVP.setArrowType(QtCore.Qt.NoArrow)
        self.tbAddChInVP.setObjectName(_fromUtf8("tbAddChInVP"))
        self.horizontalLayout_6.addWidget(self.tbAddChInVP)
        self.tbChangeChInVP = QtGui.QToolButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbChangeChInVP.setFont(font)
        self.tbChangeChInVP.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbChangeChInVP.setArrowType(QtCore.Qt.NoArrow)
        self.tbChangeChInVP.setObjectName(_fromUtf8("tbChangeChInVP"))
        self.horizontalLayout_6.addWidget(self.tbChangeChInVP)
        self.tbDelChInVP = QtGui.QToolButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDelChInVP.setFont(font)
        self.tbDelChInVP.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbDelChInVP.setArrowType(QtCore.Qt.NoArrow)
        self.tbDelChInVP.setObjectName(_fromUtf8("tbDelChInVP"))
        self.horizontalLayout_6.addWidget(self.tbDelChInVP)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lbl1_21 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_21.setFont(font)
        self.lbl1_21.setLineWidth(-5)
        self.lbl1_21.setObjectName(_fromUtf8("lbl1_21"))
        self.verticalLayout_4.addWidget(self.lbl1_21)
        self.lwChOutVP = QtGui.QListWidget(self.groupBox_8)
        self.lwChOutVP.setMaximumSize(QtCore.QSize(401, 91))
        self.lwChOutVP.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lwChOutVP.setObjectName(_fromUtf8("lwChOutVP"))
        self.verticalLayout_4.addWidget(self.lwChOutVP)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lbl1_23 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_23.setFont(font)
        self.lbl1_23.setLineWidth(-5)
        self.lbl1_23.setObjectName(_fromUtf8("lbl1_23"))
        self.horizontalLayout_4.addWidget(self.lbl1_23)
        self.cbChOutVPType = QtGui.QComboBox(self.groupBox_8)
        self.cbChOutVPType.setEditable(False)
        self.cbChOutVPType.setObjectName(_fromUtf8("cbChOutVPType"))
        self.horizontalLayout_4.addWidget(self.cbChOutVPType)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tbAddChOutVP = QtGui.QToolButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbAddChOutVP.setFont(font)
        self.tbAddChOutVP.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbAddChOutVP.setArrowType(QtCore.Qt.NoArrow)
        self.tbAddChOutVP.setObjectName(_fromUtf8("tbAddChOutVP"))
        self.horizontalLayout_5.addWidget(self.tbAddChOutVP)
        self.tbChangeChOutVP = QtGui.QToolButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbChangeChOutVP.setFont(font)
        self.tbChangeChOutVP.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbChangeChOutVP.setArrowType(QtCore.Qt.NoArrow)
        self.tbChangeChOutVP.setObjectName(_fromUtf8("tbChangeChOutVP"))
        self.horizontalLayout_5.addWidget(self.tbChangeChOutVP)
        self.tbDelChOutVP = QtGui.QToolButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDelChOutVP.setFont(font)
        self.tbDelChOutVP.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbDelChOutVP.setArrowType(QtCore.Qt.NoArrow)
        self.tbDelChOutVP.setObjectName(_fromUtf8("tbDelChOutVP"))
        self.horizontalLayout_5.addWidget(self.tbDelChOutVP)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.groupBox_8)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.gridLayout_5.addLayout(self.verticalLayout_7, 0, 1, 2, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 308, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem2, 1, 0, 1, 1)
        fmChangeVirtPribors.setCentralWidget(self.centralwidget)

        self.retranslateUi(fmChangeVirtPribors)
        self.cbTypeVPribor.setCurrentIndex(-1)
        self.cbChInVPType.setCurrentIndex(-1)
        self.cbChInVPModul.setCurrentIndex(-1)
        self.cbChInVPChannel.setCurrentIndex(-1)
        self.cbChOutVPType.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(fmChangeVirtPribors)

    def retranslateUi(self, fmChangeVirtPribors):
        fmChangeVirtPribors.setWindowTitle(_translate("fmChangeVirtPribors", "Создание виртуальных приборов", None))
        self.label.setText(_translate("fmChangeVirtPribors", "Измерители", None))
        self.tbAddAutoSearch.setText(_translate("fmChangeVirtPribors", "Добавить", None))
        self.tbDelCh_2.setText(_translate("fmChangeVirtPribors", "Удалить", None))
        self.tbAutoSearch.setText(_translate("fmChangeVirtPribors", "Тест", None))
        self.groupBox.setTitle(_translate("fmChangeVirtPribors", "Параметры изменение измерителя", None))
        self.lbl1_8.setText(_translate("fmChangeVirtPribors", "Наименование измерителя", None))
        self.leIndexMess.setText(_translate("fmChangeVirtPribors", "0", None))
        self.tbChangeCh.setText(_translate("fmChangeVirtPribors", "Изменить", None))
        self.lbl1_9.setText(_translate("fmChangeVirtPribors", "Наименование канала измерителя", None))
        self.lbl1_13.setText(_translate("fmChangeVirtPribors", "Порт 485", None))
        self.tbSavePortNum.setText(_translate("fmChangeVirtPribors", "Изменить", None))
        self.tbParam.setText(_translate("fmChangeVirtPribors", "Параметры", None))
        self.label_2.setText(_translate("fmChangeVirtPribors", "Виртуальные приборы", None))
        self.groupBox_2.setTitle(_translate("fmChangeVirtPribors", "Добавление", None))
        self.lbl1_7.setText(_translate("fmChangeVirtPribors", "Тип прибора", None))
        self.lbl1_5.setText(_translate("fmChangeVirtPribors", "Наименование прибора", None))
        self.leIndexVPribor.setText(_translate("fmChangeVirtPribors", "0", None))
        self.lbl1_10.setText(_translate("fmChangeVirtPribors", "Параметр", None))
        self.leParamVPribor.setText(_translate("fmChangeVirtPribors", "0", None))
        self.tbAddVPribor.setText(_translate("fmChangeVirtPribors", "Добавить", None))
        self.tbChangeVPribor.setText(_translate("fmChangeVirtPribors", "Изменить", None))
        self.tbDelVPribor.setText(_translate("fmChangeVirtPribors", "Удалить", None))
        self.groupBox_7.setTitle(_translate("fmChangeVirtPribors", "Добавление входного канала прибора", None))
        self.lbl1_20.setText(_translate("fmChangeVirtPribors", "Тип канала прибора", None))
        self.lbl1_19.setText(_translate("fmChangeVirtPribors", "Наименование модуля измерителя", None))
        self.lbl1_22.setText(_translate("fmChangeVirtPribors", "Наименование канала измерителя", None))
        self.tbAddChInVP.setText(_translate("fmChangeVirtPribors", "Добавить", None))
        self.tbChangeChInVP.setText(_translate("fmChangeVirtPribors", "Изменить", None))
        self.tbDelChInVP.setText(_translate("fmChangeVirtPribors", "Удалить", None))
        self.groupBox_8.setTitle(_translate("fmChangeVirtPribors", "Добавление выходного канала прибора", None))
        self.lbl1_21.setText(_translate("fmChangeVirtPribors", "Наименование канала прибора", None))
        self.lbl1_23.setText(_translate("fmChangeVirtPribors", "Тип канала прибора", None))
        self.tbAddChOutVP.setText(_translate("fmChangeVirtPribors", "Добавить", None))
        self.tbChangeChOutVP.setText(_translate("fmChangeVirtPribors", "Изменить", None))
        self.tbDelChOutVP.setText(_translate("fmChangeVirtPribors", "Удалить", None))

