# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi_vs_v.0.3\forms\fmChangeVPribors.ui'
#
# Created: Tue Feb 25 16:51:18 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmChangeVPribors(object):
    def setupUi(self, fmChangeVPribors):
        fmChangeVPribors.setObjectName(_fromUtf8("fmChangeVPribors"))
        fmChangeVPribors.resize(782, 503)
        self.centralwidget = QtGui.QWidget(fmChangeVPribors)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.twMeas = QtGui.QTreeWidget(self.centralwidget)
        self.twMeas.setGeometry(QtCore.QRect(790, 450, 292, 221))
        self.twMeas.setFrameShadow(QtGui.QFrame.Sunken)
        self.twMeas.setLineWidth(1)
        self.twMeas.setObjectName(_fromUtf8("twMeas"))
        self.twMeas.headerItem().setText(0, _fromUtf8("1"))
        self.twMeas.header().setVisible(False)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(374, 10, 291, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lwVIns = QtGui.QListWidget(self.centralwidget)
        self.lwVIns.setGeometry(QtCore.QRect(374, 30, 351, 191))
        self.lwVIns.setObjectName(_fromUtf8("lwVIns"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 10, 292, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.tbAddCh = QtGui.QToolButton(self.centralwidget)
        self.tbAddCh.setGeometry(QtCore.QRect(40, 320, 78, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbAddCh.setFont(font)
        self.tbAddCh.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbAddCh.setArrowType(QtCore.Qt.NoArrow)
        self.tbAddCh.setObjectName(_fromUtf8("tbAddCh"))
        self.tbDelCh = QtGui.QToolButton(self.centralwidget)
        self.tbDelCh.setGeometry(QtCore.QRect(270, 320, 78, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDelCh.setFont(font)
        self.tbDelCh.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbDelCh.setArrowType(QtCore.Qt.NoArrow)
        self.tbDelCh.setObjectName(_fromUtf8("tbDelCh"))
        self.tbAddVPribor = QtGui.QToolButton(self.centralwidget)
        self.tbAddVPribor.setGeometry(QtCore.QRect(382, 404, 78, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbAddVPribor.setFont(font)
        self.tbAddVPribor.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbAddVPribor.setArrowType(QtCore.Qt.NoArrow)
        self.tbAddVPribor.setObjectName(_fromUtf8("tbAddVPribor"))
        self.tbDelVPribor = QtGui.QToolButton(self.centralwidget)
        self.tbDelVPribor.setGeometry(QtCore.QRect(592, 404, 78, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDelVPribor.setFont(font)
        self.tbDelVPribor.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbDelVPribor.setArrowType(QtCore.Qt.NoArrow)
        self.tbDelVPribor.setObjectName(_fromUtf8("tbDelVPribor"))
        self.lwVIns_3 = QtGui.QListWidget(self.centralwidget)
        self.lwVIns_3.setGeometry(QtCore.QRect(35, 30, 311, 191))
        self.lwVIns_3.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lwVIns_3.setObjectName(_fromUtf8("lwVIns_3"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(36, 230, 311, 80))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lbl1_4 = QtGui.QLabel(self.groupBox)
        self.lbl1_4.setGeometry(QtCore.QRect(220, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_4.setFont(font)
        self.lbl1_4.setLineWidth(-5)
        self.lbl1_4.setObjectName(_fromUtf8("lbl1_4"))
        self.lbl1_2 = QtGui.QLabel(self.groupBox)
        self.lbl1_2.setGeometry(QtCore.QRect(4, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_2.setFont(font)
        self.lbl1_2.setLineWidth(-5)
        self.lbl1_2.setObjectName(_fromUtf8("lbl1_2"))
        self.leModbusNum = QtGui.QLineEdit(self.groupBox)
        self.leModbusNum.setGeometry(QtCore.QRect(7, 48, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leModbusNum.setFont(font)
        self.leModbusNum.setObjectName(_fromUtf8("leModbusNum"))
        self.leIndexMess = QtGui.QLineEdit(self.groupBox)
        self.leIndexMess.setGeometry(QtCore.QRect(224, 47, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leIndexMess.setFont(font)
        self.leIndexMess.setObjectName(_fromUtf8("leIndexMess"))
        self.lbl1_3 = QtGui.QLabel(self.groupBox)
        self.lbl1_3.setGeometry(QtCore.QRect(115, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_3.setFont(font)
        self.lbl1_3.setLineWidth(-5)
        self.lbl1_3.setObjectName(_fromUtf8("lbl1_3"))
        self.cbTypeMess = QtGui.QComboBox(self.groupBox)
        self.cbTypeMess.setGeometry(QtCore.QRect(97, 46, 121, 22))
        self.cbTypeMess.setEditable(False)
        self.cbTypeMess.setObjectName(_fromUtf8("cbTypeMess"))
        self.cbTypeMess.addItem(_fromUtf8(""))
        self.cbTypeMess.setItemText(0, _fromUtf8(""))
        self.cbTypeMess.addItem(_fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 233, 351, 161))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lbl1_5 = QtGui.QLabel(self.groupBox_2)
        self.lbl1_5.setGeometry(QtCore.QRect(176, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_5.setFont(font)
        self.lbl1_5.setLineWidth(-5)
        self.lbl1_5.setObjectName(_fromUtf8("lbl1_5"))
        self.leIndexMess_2 = QtGui.QLineEdit(self.groupBox_2)
        self.leIndexMess_2.setGeometry(QtCore.QRect(180, 47, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leIndexMess_2.setFont(font)
        self.leIndexMess_2.setObjectName(_fromUtf8("leIndexMess_2"))
        self.lbl1_7 = QtGui.QLabel(self.groupBox_2)
        self.lbl1_7.setGeometry(QtCore.QRect(30, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_7.setFont(font)
        self.lbl1_7.setLineWidth(-5)
        self.lbl1_7.setObjectName(_fromUtf8("lbl1_7"))
        self.cbTypeMess_2 = QtGui.QComboBox(self.groupBox_2)
        self.cbTypeMess_2.setGeometry(QtCore.QRect(12, 46, 151, 22))
        self.cbTypeMess_2.setEditable(False)
        self.cbTypeMess_2.setObjectName(_fromUtf8("cbTypeMess_2"))
        self.cbTypeMess_2.addItem(_fromUtf8(""))
        self.cbTypeMess_2.setItemText(0, _fromUtf8(""))
        self.cbTypeMess_2.addItem(_fromUtf8(""))
        self.lblch_1 = QtGui.QLabel(self.groupBox_2)
        self.lblch_1.setGeometry(QtCore.QRect(10, 90, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblch_1.setFont(font)
        self.lblch_1.setLineWidth(-5)
        self.lblch_1.setObjectName(_fromUtf8("lblch_1"))
        self.cbCh_1 = QtGui.QComboBox(self.groupBox_2)
        self.cbCh_1.setGeometry(QtCore.QRect(110, 90, 211, 22))
        self.cbCh_1.setEditable(False)
        self.cbCh_1.setObjectName(_fromUtf8("cbCh_1"))
        self.cbCh_1.addItem(_fromUtf8(""))
        self.cbCh_1.setItemText(0, _fromUtf8(""))
        self.cbCh_1.addItem(_fromUtf8(""))
        self.lblch_2 = QtGui.QLabel(self.groupBox_2)
        self.lblch_2.setGeometry(QtCore.QRect(10, 125, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblch_2.setFont(font)
        self.lblch_2.setLineWidth(-5)
        self.lblch_2.setObjectName(_fromUtf8("lblch_2"))
        self.cbCh_2 = QtGui.QComboBox(self.groupBox_2)
        self.cbCh_2.setGeometry(QtCore.QRect(110, 125, 211, 22))
        self.cbCh_2.setEditable(False)
        self.cbCh_2.setObjectName(_fromUtf8("cbCh_2"))
        self.cbCh_2.addItem(_fromUtf8(""))
        self.cbCh_2.setItemText(0, _fromUtf8(""))
        self.cbCh_2.addItem(_fromUtf8(""))
        self.cbCh_2.setItemText(1, _fromUtf8(""))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 350, 311, 71))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.lePortNum = QtGui.QLineEdit(self.groupBox_3)
        self.lePortNum.setGeometry(QtCore.QRect(20, 30, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lePortNum.setFont(font)
        self.lePortNum.setObjectName(_fromUtf8("lePortNum"))
        self.tbSave = QtGui.QToolButton(self.centralwidget)
        self.tbSave.setGeometry(QtCore.QRect(320, 440, 78, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbSave.setFont(font)
        self.tbSave.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbSave.setArrowType(QtCore.Qt.NoArrow)
        self.tbSave.setObjectName(_fromUtf8("tbSave"))
        fmChangeVPribors.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fmChangeVPribors)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        fmChangeVPribors.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fmChangeVPribors)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fmChangeVPribors.setStatusBar(self.statusbar)

        self.retranslateUi(fmChangeVPribors)
        self.cbTypeMess.setCurrentIndex(0)
        self.cbTypeMess_2.setCurrentIndex(0)
        self.cbCh_1.setCurrentIndex(0)
        self.cbCh_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(fmChangeVPribors)

    def retranslateUi(self, fmChangeVPribors):
        fmChangeVPribors.setWindowTitle(_translate("fmChangeVPribors", "MainWindow", None))
        self.label_2.setText(_translate("fmChangeVPribors", "Виртуальные приборы", None))
        self.label.setText(_translate("fmChangeVPribors", "Измерители", None))
        self.tbAddCh.setText(_translate("fmChangeVPribors", "Добавить", None))
        self.tbDelCh.setText(_translate("fmChangeVPribors", "Удалить", None))
        self.tbAddVPribor.setText(_translate("fmChangeVPribors", "Добавить", None))
        self.tbDelVPribor.setText(_translate("fmChangeVPribors", "Удалить", None))
        self.groupBox.setTitle(_translate("fmChangeVPribors", "Добавление", None))
        self.lbl1_4.setText(_translate("fmChangeVPribors", "Индекс канала", None))
        self.lbl1_2.setText(_translate("fmChangeVPribors", "Адрес MODBUS", None))
        self.leModbusNum.setText(_translate("fmChangeVPribors", "0", None))
        self.leIndexMess.setText(_translate("fmChangeVPribors", "0", None))
        self.lbl1_3.setText(_translate("fmChangeVPribors", "Тип канала", None))
        self.cbTypeMess.setItemText(1, _translate("fmChangeVPribors", "AD7793 (24  бит)", None))
        self.groupBox_2.setTitle(_translate("fmChangeVPribors", "Добавление", None))
        self.lbl1_5.setText(_translate("fmChangeVPribors", "Индекс прибора", None))
        self.leIndexMess_2.setText(_translate("fmChangeVPribors", "0", None))
        self.lbl1_7.setText(_translate("fmChangeVPribors", "Тип прибора", None))
        self.cbTypeMess_2.setItemText(1, _translate("fmChangeVPribors", "AD7793 (24  бит)", None))
        self.lblch_1.setText(_translate("fmChangeVPribors", "Канал", None))
        self.cbCh_1.setItemText(1, _translate("fmChangeVPribors", "AD7793 (24  бит)", None))
        self.lblch_2.setText(_translate("fmChangeVPribors", "Канал", None))
        self.groupBox_3.setTitle(_translate("fmChangeVPribors", "Порт 485", None))
        self.tbSave.setText(_translate("fmChangeVPribors", "Сохранить", None))

