# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi (4)\svi\forms\fmChangeVirtPribors.ui'
#
# Created: Thu Sep 13 10:22:52 2018
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmChangeVirtPribors(object):
    def setupUi(self, fmChangeVirtPribors):
        fmChangeVirtPribors.setObjectName(_fromUtf8("fmChangeVirtPribors"))
        fmChangeVirtPribors.resize(1539, 1050)
        self.centralwidget = QtGui.QWidget(fmChangeVirtPribors)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_7 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(820, 430, 691, 371))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.lwChInVP = QtGui.QListWidget(self.groupBox_7)
        self.lwChInVP.setGeometry(QtCore.QRect(10, 28, 671, 101))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwChInVP.sizePolicy().hasHeightForWidth())
        self.lwChInVP.setSizePolicy(sizePolicy)
        self.lwChInVP.setMaximumSize(QtCore.QSize(3980, 810))
        self.lwChInVP.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lwChInVP.setObjectName(_fromUtf8("lwChInVP"))
        self.tbAddChInVP = QtGui.QToolButton(self.groupBox_7)
        self.tbAddChInVP.setGeometry(QtCore.QRect(30, 310, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbAddChInVP.setFont(font)
        self.tbAddChInVP.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbAddChInVP.setArrowType(QtCore.Qt.NoArrow)
        self.tbAddChInVP.setObjectName(_fromUtf8("tbAddChInVP"))
        self.tbChangeChInVP = QtGui.QToolButton(self.groupBox_7)
        self.tbChangeChInVP.setGeometry(QtCore.QRect(220, 310, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbChangeChInVP.setFont(font)
        self.tbChangeChInVP.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbChangeChInVP.setArrowType(QtCore.Qt.NoArrow)
        self.tbChangeChInVP.setObjectName(_fromUtf8("tbChangeChInVP"))
        self.tbDelChInVP = QtGui.QToolButton(self.groupBox_7)
        self.tbDelChInVP.setGeometry(QtCore.QRect(410, 310, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDelChInVP.setFont(font)
        self.tbDelChInVP.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbDelChInVP.setArrowType(QtCore.Qt.NoArrow)
        self.tbDelChInVP.setObjectName(_fromUtf8("tbDelChInVP"))
        self.cbChInVPChannel = QtGui.QComboBox(self.groupBox_7)
        self.cbChInVPChannel.setGeometry(QtCore.QRect(280, 250, 391, 41))
        self.cbChInVPChannel.setEditable(False)
        self.cbChInVPChannel.setObjectName(_fromUtf8("cbChInVPChannel"))
        self.lbl1_20 = QtGui.QLabel(self.groupBox_7)
        self.lbl1_20.setGeometry(QtCore.QRect(20, 140, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_20.setFont(font)
        self.lbl1_20.setLineWidth(-5)
        self.lbl1_20.setObjectName(_fromUtf8("lbl1_20"))
        self.lbl1_19 = QtGui.QLabel(self.groupBox_7)
        self.lbl1_19.setGeometry(QtCore.QRect(280, 140, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_19.setFont(font)
        self.lbl1_19.setLineWidth(-5)
        self.lbl1_19.setObjectName(_fromUtf8("lbl1_19"))
        self.cbChInVPType = QtGui.QComboBox(self.groupBox_7)
        self.cbChInVPType.setGeometry(QtCore.QRect(20, 170, 221, 41))
        self.cbChInVPType.setEditable(False)
        self.cbChInVPType.setObjectName(_fromUtf8("cbChInVPType"))
        self.cbChInVPModul = QtGui.QComboBox(self.groupBox_7)
        self.cbChInVPModul.setGeometry(QtCore.QRect(280, 170, 381, 41))
        self.cbChInVPModul.setEditable(False)
        self.cbChInVPModul.setObjectName(_fromUtf8("cbChInVPModul"))
        self.lbl1_22 = QtGui.QLabel(self.groupBox_7)
        self.lbl1_22.setGeometry(QtCore.QRect(280, 220, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_22.setFont(font)
        self.lbl1_22.setLineWidth(-5)
        self.lbl1_22.setObjectName(_fromUtf8("lbl1_22"))
        self.groupBox_8 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(830, 800, 681, 231))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.lbl1_21 = QtGui.QLabel(self.groupBox_8)
        self.lbl1_21.setGeometry(QtCore.QRect(10, 26, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_21.setFont(font)
        self.lbl1_21.setLineWidth(-5)
        self.lbl1_21.setObjectName(_fromUtf8("lbl1_21"))
        self.lwChOutVP = QtGui.QListWidget(self.groupBox_8)
        self.lwChOutVP.setGeometry(QtCore.QRect(10, 60, 391, 91))
        self.lwChOutVP.setMaximumSize(QtCore.QSize(4010, 9100))
        self.lwChOutVP.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lwChOutVP.setObjectName(_fromUtf8("lwChOutVP"))
        self.tbAddChOutVP = QtGui.QToolButton(self.groupBox_8)
        self.tbAddChOutVP.setGeometry(QtCore.QRect(40, 170, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbAddChOutVP.setFont(font)
        self.tbAddChOutVP.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbAddChOutVP.setArrowType(QtCore.Qt.NoArrow)
        self.tbAddChOutVP.setObjectName(_fromUtf8("tbAddChOutVP"))
        self.tbChangeChOutVP = QtGui.QToolButton(self.groupBox_8)
        self.tbChangeChOutVP.setGeometry(QtCore.QRect(220, 170, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbChangeChOutVP.setFont(font)
        self.tbChangeChOutVP.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbChangeChOutVP.setArrowType(QtCore.Qt.NoArrow)
        self.tbChangeChOutVP.setObjectName(_fromUtf8("tbChangeChOutVP"))
        self.tbDelChOutVP = QtGui.QToolButton(self.groupBox_8)
        self.tbDelChOutVP.setGeometry(QtCore.QRect(400, 170, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDelChOutVP.setFont(font)
        self.tbDelChOutVP.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbDelChOutVP.setArrowType(QtCore.Qt.NoArrow)
        self.tbDelChOutVP.setObjectName(_fromUtf8("tbDelChOutVP"))
        self.lbl1_23 = QtGui.QLabel(self.groupBox_8)
        self.lbl1_23.setGeometry(QtCore.QRect(420, 20, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_23.setFont(font)
        self.lbl1_23.setLineWidth(-5)
        self.lbl1_23.setObjectName(_fromUtf8("lbl1_23"))
        self.cbChOutVPType = QtGui.QComboBox(self.groupBox_8)
        self.cbChOutVPType.setGeometry(QtCore.QRect(420, 60, 231, 41))
        self.cbChOutVPType.setEditable(False)
        self.cbChOutVPType.setObjectName(_fromUtf8("cbChOutVPType"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 360, 741, 361))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lbl1_8 = QtGui.QLabel(self.groupBox)
        self.lbl1_8.setGeometry(QtCore.QRect(20, 30, 331, 21))
        self.lbl1_8.setMaximumSize(QtCore.QSize(16777215, 140))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_8.setFont(font)
        self.lbl1_8.setLineWidth(-5)
        self.lbl1_8.setObjectName(_fromUtf8("lbl1_8"))
        self.lbl1_9 = QtGui.QLabel(self.groupBox)
        self.lbl1_9.setGeometry(QtCore.QRect(30, 130, 411, 31))
        self.lbl1_9.setMaximumSize(QtCore.QSize(16777215, 140))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_9.setFont(font)
        self.lbl1_9.setLineWidth(-5)
        self.lbl1_9.setObjectName(_fromUtf8("lbl1_9"))
        self.lwChInMess = QtGui.QListWidget(self.groupBox)
        self.lwChInMess.setGeometry(QtCore.QRect(30, 170, 691, 171))
        self.lwChInMess.setMaximumSize(QtCore.QSize(4092, 7800))
        self.lwChInMess.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lwChInMess.setObjectName(_fromUtf8("lwChInMess"))
        self.leIndexMess = QtGui.QLineEdit(self.groupBox)
        self.leIndexMess.setGeometry(QtCore.QRect(30, 70, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leIndexMess.setFont(font)
        self.leIndexMess.setObjectName(_fromUtf8("leIndexMess"))
        self.tbChangeCh = QtGui.QToolButton(self.groupBox)
        self.tbChangeCh.setGeometry(QtCore.QRect(410, 60, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbChangeCh.setFont(font)
        self.tbChangeCh.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbChangeCh.setArrowType(QtCore.Qt.NoArrow)
        self.tbChangeCh.setObjectName(_fromUtf8("tbChangeCh"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(12, 12, 311, 21))
        self.label.setMaximumSize(QtCore.QSize(16777215, 140))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.lwCh = QtGui.QListWidget(self.centralwidget)
        self.lwCh.setGeometry(QtCore.QRect(40, 50, 711, 221))
        self.lwCh.setMinimumSize(QtCore.QSize(439, 131))
        self.lwCh.setMaximumSize(QtCore.QSize(4390, 1310))
        self.lwCh.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lwCh.setObjectName(_fromUtf8("lwCh"))
        self.tbDelCh_2 = QtGui.QToolButton(self.centralwidget)
        self.tbDelCh_2.setGeometry(QtCore.QRect(250, 280, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDelCh_2.setFont(font)
        self.tbDelCh_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbDelCh_2.setArrowType(QtCore.Qt.NoArrow)
        self.tbDelCh_2.setObjectName(_fromUtf8("tbDelCh_2"))
        self.tbAddAutoSearch = QtGui.QToolButton(self.centralwidget)
        self.tbAddAutoSearch.setGeometry(QtCore.QRect(50, 280, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbAddAutoSearch.setFont(font)
        self.tbAddAutoSearch.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbAddAutoSearch.setArrowType(QtCore.Qt.NoArrow)
        self.tbAddAutoSearch.setObjectName(_fromUtf8("tbAddAutoSearch"))
        self.tbAutoSearch = QtGui.QToolButton(self.centralwidget)
        self.tbAutoSearch.setGeometry(QtCore.QRect(440, 280, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbAutoSearch.setFont(font)
        self.tbAutoSearch.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbAutoSearch.setArrowType(QtCore.Qt.NoArrow)
        self.tbAutoSearch.setObjectName(_fromUtf8("tbAutoSearch"))
        self.lbl1_13 = QtGui.QLabel(self.centralwidget)
        self.lbl1_13.setGeometry(QtCore.QRect(70, 750, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_13.setFont(font)
        self.lbl1_13.setLineWidth(-5)
        self.lbl1_13.setObjectName(_fromUtf8("lbl1_13"))
        self.lePortNum = QtGui.QLineEdit(self.centralwidget)
        self.lePortNum.setGeometry(QtCore.QRect(190, 740, 111, 41))
        self.lePortNum.setMaximumSize(QtCore.QSize(510, 200))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lePortNum.setFont(font)
        self.lePortNum.setObjectName(_fromUtf8("lePortNum"))
        self.tbSavePortNum = QtGui.QToolButton(self.centralwidget)
        self.tbSavePortNum.setGeometry(QtCore.QRect(330, 730, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbSavePortNum.setFont(font)
        self.tbSavePortNum.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbSavePortNum.setArrowType(QtCore.Qt.NoArrow)
        self.tbSavePortNum.setObjectName(_fromUtf8("tbSavePortNum"))
        self.tbParam = QtGui.QToolButton(self.centralwidget)
        self.tbParam.setGeometry(QtCore.QRect(570, 730, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbParam.setFont(font)
        self.tbParam.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbParam.setArrowType(QtCore.Qt.NoArrow)
        self.tbParam.setObjectName(_fromUtf8("tbParam"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(820, 240, 681, 191))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lbl1_10 = QtGui.QLabel(self.groupBox_2)
        self.lbl1_10.setGeometry(QtCore.QRect(570, 34, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_10.setFont(font)
        self.lbl1_10.setLineWidth(-5)
        self.lbl1_10.setObjectName(_fromUtf8("lbl1_10"))
        self.leParamVPribor = QtGui.QLineEdit(self.groupBox_2)
        self.leParamVPribor.setGeometry(QtCore.QRect(570, 64, 133, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leParamVPribor.sizePolicy().hasHeightForWidth())
        self.leParamVPribor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leParamVPribor.setFont(font)
        self.leParamVPribor.setObjectName(_fromUtf8("leParamVPribor"))
        self.lbl1_5 = QtGui.QLabel(self.groupBox_2)
        self.lbl1_5.setGeometry(QtCore.QRect(270, 26, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_5.setFont(font)
        self.lbl1_5.setLineWidth(-5)
        self.lbl1_5.setObjectName(_fromUtf8("lbl1_5"))
        self.leIndexVPribor = QtGui.QLineEdit(self.groupBox_2)
        self.leIndexVPribor.setGeometry(QtCore.QRect(273, 66, 271, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leIndexVPribor.sizePolicy().hasHeightForWidth())
        self.leIndexVPribor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leIndexVPribor.setFont(font)
        self.leIndexVPribor.setObjectName(_fromUtf8("leIndexVPribor"))
        self.lbl1_7 = QtGui.QLabel(self.groupBox_2)
        self.lbl1_7.setGeometry(QtCore.QRect(40, 25, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_7.setFont(font)
        self.lbl1_7.setLineWidth(-5)
        self.lbl1_7.setObjectName(_fromUtf8("lbl1_7"))
        self.cbTypeVPribor = QtGui.QComboBox(self.groupBox_2)
        self.cbTypeVPribor.setGeometry(QtCore.QRect(10, 64, 241, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTypeVPribor.sizePolicy().hasHeightForWidth())
        self.cbTypeVPribor.setSizePolicy(sizePolicy)
        self.cbTypeVPribor.setEditable(False)
        self.cbTypeVPribor.setObjectName(_fromUtf8("cbTypeVPribor"))
        self.tbAddVPribor = QtGui.QToolButton(self.groupBox_2)
        self.tbAddVPribor.setGeometry(QtCore.QRect(10, 124, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbAddVPribor.setFont(font)
        self.tbAddVPribor.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbAddVPribor.setArrowType(QtCore.Qt.NoArrow)
        self.tbAddVPribor.setObjectName(_fromUtf8("tbAddVPribor"))
        self.tbChangeVPribor = QtGui.QToolButton(self.groupBox_2)
        self.tbChangeVPribor.setGeometry(QtCore.QRect(230, 124, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbChangeVPribor.setFont(font)
        self.tbChangeVPribor.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbChangeVPribor.setArrowType(QtCore.Qt.NoArrow)
        self.tbChangeVPribor.setObjectName(_fromUtf8("tbChangeVPribor"))
        self.tbDelVPribor = QtGui.QToolButton(self.groupBox_2)
        self.tbDelVPribor.setGeometry(QtCore.QRect(420, 124, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDelVPribor.setFont(font)
        self.tbDelVPribor.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbDelVPribor.setArrowType(QtCore.Qt.NoArrow)
        self.tbDelVPribor.setObjectName(_fromUtf8("tbDelVPribor"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(830, 10, 321, 31))
        self.label_2.setMaximumSize(QtCore.QSize(4370, 1400))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lwVIns = QtGui.QListWidget(self.centralwidget)
        self.lwVIns.setGeometry(QtCore.QRect(820, 50, 711, 181))
        self.lwVIns.setMinimumSize(QtCore.QSize(439, 129))
        self.lwVIns.setMaximumSize(QtCore.QSize(4390, 1290))
        self.lwVIns.setObjectName(_fromUtf8("lwVIns"))
        fmChangeVirtPribors.setCentralWidget(self.centralwidget)

        self.retranslateUi(fmChangeVirtPribors)
        self.cbChInVPChannel.setCurrentIndex(-1)
        self.cbChInVPType.setCurrentIndex(-1)
        self.cbChInVPModul.setCurrentIndex(-1)
        self.cbChOutVPType.setCurrentIndex(-1)
        self.cbTypeVPribor.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(fmChangeVirtPribors)

    def retranslateUi(self, fmChangeVirtPribors):
        fmChangeVirtPribors.setWindowTitle(_translate("fmChangeVirtPribors", "Создание виртуальных приборов", None))
        self.groupBox_7.setTitle(_translate("fmChangeVirtPribors", "Добавление входного канала прибора", None))
        self.tbAddChInVP.setText(_translate("fmChangeVirtPribors", "Добавить", None))
        self.tbChangeChInVP.setText(_translate("fmChangeVirtPribors", "Изменить", None))
        self.tbDelChInVP.setText(_translate("fmChangeVirtPribors", "Удалить", None))
        self.lbl1_20.setText(_translate("fmChangeVirtPribors", "Тип канала прибора", None))
        self.lbl1_19.setText(_translate("fmChangeVirtPribors", "Наименование модуля измерителя", None))
        self.lbl1_22.setText(_translate("fmChangeVirtPribors", "Наименование канала измерителя", None))
        self.groupBox_8.setTitle(_translate("fmChangeVirtPribors", "Добавление выходного канала прибора", None))
        self.lbl1_21.setText(_translate("fmChangeVirtPribors", "Наименование канала прибора", None))
        self.tbAddChOutVP.setText(_translate("fmChangeVirtPribors", "Добавить", None))
        self.tbChangeChOutVP.setText(_translate("fmChangeVirtPribors", "Изменить", None))
        self.tbDelChOutVP.setText(_translate("fmChangeVirtPribors", "Удалить", None))
        self.lbl1_23.setText(_translate("fmChangeVirtPribors", "Тип канала прибора", None))
        self.groupBox.setTitle(_translate("fmChangeVirtPribors", "Параметры изменение измерителя", None))
        self.lbl1_8.setText(_translate("fmChangeVirtPribors", "Наименование измерителя", None))
        self.lbl1_9.setText(_translate("fmChangeVirtPribors", "Наименование канала измерителя", None))
        self.leIndexMess.setText(_translate("fmChangeVirtPribors", "0", None))
        self.tbChangeCh.setText(_translate("fmChangeVirtPribors", "Изменить", None))
        self.label.setText(_translate("fmChangeVirtPribors", "Измерители", None))
        self.tbDelCh_2.setText(_translate("fmChangeVirtPribors", "Удалить", None))
        self.tbAddAutoSearch.setText(_translate("fmChangeVirtPribors", "Добавить", None))
        self.tbAutoSearch.setText(_translate("fmChangeVirtPribors", "Тест", None))
        self.lbl1_13.setText(_translate("fmChangeVirtPribors", "Порт 485", None))
        self.tbSavePortNum.setText(_translate("fmChangeVirtPribors", "Изменить", None))
        self.tbParam.setText(_translate("fmChangeVirtPribors", "Параметры", None))
        self.groupBox_2.setTitle(_translate("fmChangeVirtPribors", "Добавление", None))
        self.lbl1_10.setText(_translate("fmChangeVirtPribors", "Параметр", None))
        self.leParamVPribor.setText(_translate("fmChangeVirtPribors", "0", None))
        self.lbl1_5.setText(_translate("fmChangeVirtPribors", "Наименование прибора", None))
        self.leIndexVPribor.setText(_translate("fmChangeVirtPribors", "0", None))
        self.lbl1_7.setText(_translate("fmChangeVirtPribors", "Тип прибора", None))
        self.tbAddVPribor.setText(_translate("fmChangeVirtPribors", "Добавить", None))
        self.tbChangeVPribor.setText(_translate("fmChangeVirtPribors", "Изменить", None))
        self.tbDelVPribor.setText(_translate("fmChangeVirtPribors", "Удалить", None))
        self.label_2.setText(_translate("fmChangeVirtPribors", "Виртуальные приборы", None))

