# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi_vs_v.0.5.1\forms\fmCondConf.ui'
#
# Created: Fri Oct  9 10:46:31 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmCondConf(object):
    def setupUi(self, fmCondConf):
        fmCondConf.setObjectName(_fromUtf8("fmCondConf"))
        fmCondConf.resize(936, 711)
        self.centralwidget = QtGui.QWidget(fmCondConf)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.leAddrMB = QtGui.QLineEdit(self.centralwidget)
        self.leAddrMB.setGeometry(QtCore.QRect(172, 18, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAddrMB.setFont(font)
        self.leAddrMB.setObjectName(_fromUtf8("leAddrMB"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.tbAddrMBWr = QtGui.QToolButton(self.centralwidget)
        self.tbAddrMBWr.setGeometry(QtCore.QRect(290, 17, 27, 22))
        self.tbAddrMBWr.setObjectName(_fromUtf8("tbAddrMBWr"))
        self.tbAddrMBRd = QtGui.QToolButton(self.centralwidget)
        self.tbAddrMBRd.setGeometry(QtCore.QRect(260, 17, 27, 22))
        self.tbAddrMBRd.setObjectName(_fromUtf8("tbAddrMBRd"))
        self.tbthrATRd = QtGui.QToolButton(self.centralwidget)
        self.tbthrATRd.setGeometry(QtCore.QRect(260, 47, 27, 22))
        self.tbthrATRd.setObjectName(_fromUtf8("tbthrATRd"))
        self.tbthrATWr = QtGui.QToolButton(self.centralwidget)
        self.tbthrATWr.setGeometry(QtCore.QRect(290, 47, 27, 22))
        self.tbthrATWr.setObjectName(_fromUtf8("tbthrATWr"))
        self.lethrAT = QtGui.QLineEdit(self.centralwidget)
        self.lethrAT.setGeometry(QtCore.QRect(172, 48, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lethrAT.setFont(font)
        self.lethrAT.setObjectName(_fromUtf8("lethrAT"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(10, 50, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.tbConfRd = QtGui.QToolButton(self.centralwidget)
        self.tbConfRd.setGeometry(QtCore.QRect(260, 207, 27, 22))
        self.tbConfRd.setObjectName(_fromUtf8("tbConfRd"))
        self.tbConfWr = QtGui.QToolButton(self.centralwidget)
        self.tbConfWr.setGeometry(QtCore.QRect(290, 207, 27, 22))
        self.tbConfWr.setObjectName(_fromUtf8("tbConfWr"))
        self.leConf = QtGui.QLineEdit(self.centralwidget)
        self.leConf.setGeometry(QtCore.QRect(172, 208, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leConf.setFont(font)
        self.leConf.setObjectName(_fromUtf8("leConf"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(10, 211, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(10, 291, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.leSerNum = QtGui.QLineEdit(self.centralwidget)
        self.leSerNum.setGeometry(QtCore.QRect(172, 289, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leSerNum.setFont(font)
        self.leSerNum.setObjectName(_fromUtf8("leSerNum"))
        self.tbSerNumWr = QtGui.QToolButton(self.centralwidget)
        self.tbSerNumWr.setGeometry(QtCore.QRect(290, 288, 27, 22))
        self.tbSerNumWr.setObjectName(_fromUtf8("tbSerNumWr"))
        self.tbSerNumRd = QtGui.QToolButton(self.centralwidget)
        self.tbSerNumRd.setGeometry(QtCore.QRect(260, 288, 27, 22))
        self.tbSerNumRd.setObjectName(_fromUtf8("tbSerNumRd"))
        self.leZeroA = QtGui.QLineEdit(self.centralwidget)
        self.leZeroA.setGeometry(QtCore.QRect(171, 97, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leZeroA.setFont(font)
        self.leZeroA.setObjectName(_fromUtf8("leZeroA"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(11, 100, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lemK = QtGui.QLineEdit(self.centralwidget)
        self.lemK.setGeometry(QtCore.QRect(170, 129, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lemK.setFont(font)
        self.lemK.setObjectName(_fromUtf8("lemK"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(12, 130, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setLineWidth(-5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.tbZeroARd = QtGui.QToolButton(self.centralwidget)
        self.tbZeroARd.setGeometry(QtCore.QRect(320, 96, 27, 22))
        self.tbZeroARd.setObjectName(_fromUtf8("tbZeroARd"))
        self.tbZeroAWr = QtGui.QToolButton(self.centralwidget)
        self.tbZeroAWr.setGeometry(QtCore.QRect(350, 96, 27, 22))
        self.tbZeroAWr.setObjectName(_fromUtf8("tbZeroAWr"))
        self.tbZeroARdVar = QtGui.QToolButton(self.centralwidget)
        self.tbZeroARdVar.setGeometry(QtCore.QRect(262, 96, 51, 22))
        self.tbZeroARdVar.setObjectName(_fromUtf8("tbZeroARdVar"))
        self.tbmKRdVar = QtGui.QToolButton(self.centralwidget)
        self.tbmKRdVar.setGeometry(QtCore.QRect(262, 128, 51, 22))
        self.tbmKRdVar.setObjectName(_fromUtf8("tbmKRdVar"))
        self.tbmKRd = QtGui.QToolButton(self.centralwidget)
        self.tbmKRd.setGeometry(QtCore.QRect(320, 128, 27, 22))
        self.tbmKRd.setObjectName(_fromUtf8("tbmKRd"))
        self.tbmKWr = QtGui.QToolButton(self.centralwidget)
        self.tbmKWr.setGeometry(QtCore.QRect(350, 128, 27, 22))
        self.tbmKWr.setObjectName(_fromUtf8("tbmKWr"))
        self.tbModeRd = QtGui.QToolButton(self.centralwidget)
        self.tbModeRd.setGeometry(QtCore.QRect(259, 175, 27, 22))
        self.tbModeRd.setObjectName(_fromUtf8("tbModeRd"))
        self.tbModeWr = QtGui.QToolButton(self.centralwidget)
        self.tbModeWr.setGeometry(QtCore.QRect(289, 175, 27, 22))
        self.tbModeWr.setObjectName(_fromUtf8("tbModeWr"))
        self.leMode = QtGui.QLineEdit(self.centralwidget)
        self.leMode.setGeometry(QtCore.QRect(171, 176, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leMode.setFont(font)
        self.leMode.setObjectName(_fromUtf8("leMode"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(10, 179, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(10, 243, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.leIO = QtGui.QLineEdit(self.centralwidget)
        self.leIO.setGeometry(QtCore.QRect(171, 241, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leIO.setFont(font)
        self.leIO.setObjectName(_fromUtf8("leIO"))
        self.tbIOWr = QtGui.QToolButton(self.centralwidget)
        self.tbIOWr.setGeometry(QtCore.QRect(289, 240, 27, 22))
        self.tbIOWr.setObjectName(_fromUtf8("tbIOWr"))
        self.tbIORd = QtGui.QToolButton(self.centralwidget)
        self.tbIORd.setGeometry(QtCore.QRect(259, 240, 27, 22))
        self.tbIORd.setObjectName(_fromUtf8("tbIORd"))
        self.tbSave = QtGui.QToolButton(self.centralwidget)
        self.tbSave.setGeometry(QtCore.QRect(320, 636, 361, 22))
        self.tbSave.setObjectName(_fromUtf8("tbSave"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(11, 319, 581, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 400, 581, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(11, 341, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.lePD47 = QtGui.QLineEdit(self.centralwidget)
        self.lePD47.setGeometry(QtCore.QRect(173, 338, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lePD47.setFont(font)
        self.lePD47.setObjectName(_fromUtf8("lePD47"))
        self.tbPB5Wr = QtGui.QToolButton(self.centralwidget)
        self.tbPB5Wr.setGeometry(QtCore.QRect(349, 371, 27, 22))
        self.tbPB5Wr.setObjectName(_fromUtf8("tbPB5Wr"))
        self.tbPD47Wr = QtGui.QToolButton(self.centralwidget)
        self.tbPD47Wr.setGeometry(QtCore.QRect(350, 339, 27, 22))
        self.tbPD47Wr.setObjectName(_fromUtf8("tbPD47Wr"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(11, 373, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.tbPD47Rd = QtGui.QToolButton(self.centralwidget)
        self.tbPD47Rd.setGeometry(QtCore.QRect(320, 339, 27, 22))
        self.tbPD47Rd.setObjectName(_fromUtf8("tbPD47Rd"))
        self.lePB5 = QtGui.QLineEdit(self.centralwidget)
        self.lePB5.setGeometry(QtCore.QRect(172, 371, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lePB5.setFont(font)
        self.lePB5.setObjectName(_fromUtf8("lePB5"))
        self.tbPB5Rd = QtGui.QToolButton(self.centralwidget)
        self.tbPB5Rd.setGeometry(QtCore.QRect(319, 371, 27, 22))
        self.tbPB5Rd.setObjectName(_fromUtf8("tbPB5Rd"))
        self.tbPB5Var = QtGui.QToolButton(self.centralwidget)
        self.tbPB5Var.setGeometry(QtCore.QRect(260, 370, 51, 22))
        self.tbPB5Var.setObjectName(_fromUtf8("tbPB5Var"))
        self.tbPD47Var = QtGui.QToolButton(self.centralwidget)
        self.tbPD47Var.setGeometry(QtCore.QRect(260, 338, 51, 22))
        self.tbPD47Var.setObjectName(_fromUtf8("tbPD47Var"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 420, 581, 211))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.leAet_1 = QtGui.QLineEdit(self.groupBox_3)
        self.leAet_1.setGeometry(QtCore.QRect(80, 30, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAet_1.setFont(font)
        self.leAet_1.setObjectName(_fromUtf8("leAet_1"))
        self.tbAetRd_1 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetRd_1.setGeometry(QtCore.QRect(170, 30, 27, 22))
        self.tbAetRd_1.setObjectName(_fromUtf8("tbAetRd_1"))
        self.tbAetWr_1 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetWr_1.setGeometry(QtCore.QRect(256, 30, 27, 22))
        self.tbAetWr_1.setObjectName(_fromUtf8("tbAetWr_1"))
        self.label_24 = QtGui.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(10, 30, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setLineWidth(-5)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.tbNtWr_1 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtWr_1.setGeometry(QtCore.QRect(545, 30, 27, 22))
        self.tbNtWr_1.setObjectName(_fromUtf8("tbNtWr_1"))
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(296, 30, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setLineWidth(-5)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.leNt_1 = QtGui.QLineEdit(self.groupBox_3)
        self.leNt_1.setGeometry(QtCore.QRect(366, 30, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leNt_1.setFont(font)
        self.leNt_1.setObjectName(_fromUtf8("leNt_1"))
        self.tbNtRd_1 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtRd_1.setGeometry(QtCore.QRect(456, 30, 27, 22))
        self.tbNtRd_1.setObjectName(_fromUtf8("tbNtRd_1"))
        self.tbNtWr_2 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtWr_2.setGeometry(QtCore.QRect(545, 60, 27, 22))
        self.tbNtWr_2.setObjectName(_fromUtf8("tbNtWr_2"))
        self.tbNtRd_2 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtRd_2.setGeometry(QtCore.QRect(456, 60, 27, 22))
        self.tbNtRd_2.setObjectName(_fromUtf8("tbNtRd_2"))
        self.label_26 = QtGui.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(296, 60, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setLineWidth(-5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.tbAetWr_2 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetWr_2.setGeometry(QtCore.QRect(256, 60, 27, 22))
        self.tbAetWr_2.setObjectName(_fromUtf8("tbAetWr_2"))
        self.label_27 = QtGui.QLabel(self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(10, 60, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setLineWidth(-5)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.leNt_2 = QtGui.QLineEdit(self.groupBox_3)
        self.leNt_2.setGeometry(QtCore.QRect(366, 60, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leNt_2.setFont(font)
        self.leNt_2.setObjectName(_fromUtf8("leNt_2"))
        self.leAet_2 = QtGui.QLineEdit(self.groupBox_3)
        self.leAet_2.setGeometry(QtCore.QRect(80, 60, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAet_2.setFont(font)
        self.leAet_2.setObjectName(_fromUtf8("leAet_2"))
        self.tbAetRd_2 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetRd_2.setGeometry(QtCore.QRect(170, 60, 27, 22))
        self.tbAetRd_2.setObjectName(_fromUtf8("tbAetRd_2"))
        self.tbNtWr_3 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtWr_3.setGeometry(QtCore.QRect(545, 90, 27, 22))
        self.tbNtWr_3.setObjectName(_fromUtf8("tbNtWr_3"))
        self.tbNtRd_3 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtRd_3.setGeometry(QtCore.QRect(456, 90, 27, 22))
        self.tbNtRd_3.setObjectName(_fromUtf8("tbNtRd_3"))
        self.label_28 = QtGui.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(296, 90, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setLineWidth(-5)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.tbAetWr_3 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetWr_3.setGeometry(QtCore.QRect(256, 90, 27, 22))
        self.tbAetWr_3.setObjectName(_fromUtf8("tbAetWr_3"))
        self.label_29 = QtGui.QLabel(self.groupBox_3)
        self.label_29.setGeometry(QtCore.QRect(10, 90, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setLineWidth(-5)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.leNt_3 = QtGui.QLineEdit(self.groupBox_3)
        self.leNt_3.setGeometry(QtCore.QRect(366, 90, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leNt_3.setFont(font)
        self.leNt_3.setObjectName(_fromUtf8("leNt_3"))
        self.leAet_3 = QtGui.QLineEdit(self.groupBox_3)
        self.leAet_3.setGeometry(QtCore.QRect(80, 90, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAet_3.setFont(font)
        self.leAet_3.setObjectName(_fromUtf8("leAet_3"))
        self.tbAetRd_3 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetRd_3.setGeometry(QtCore.QRect(170, 90, 27, 22))
        self.tbAetRd_3.setObjectName(_fromUtf8("tbAetRd_3"))
        self.tbAetVar_1 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetVar_1.setGeometry(QtCore.QRect(200, 30, 51, 22))
        self.tbAetVar_1.setObjectName(_fromUtf8("tbAetVar_1"))
        self.tbAetVar_2 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetVar_2.setGeometry(QtCore.QRect(200, 60, 51, 22))
        self.tbAetVar_2.setObjectName(_fromUtf8("tbAetVar_2"))
        self.tbAetVar_3 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetVar_3.setGeometry(QtCore.QRect(200, 90, 51, 22))
        self.tbAetVar_3.setObjectName(_fromUtf8("tbAetVar_3"))
        self.tbNtVar_2 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtVar_2.setGeometry(QtCore.QRect(490, 60, 51, 22))
        self.tbNtVar_2.setObjectName(_fromUtf8("tbNtVar_2"))
        self.tbNtVar_1 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtVar_1.setGeometry(QtCore.QRect(490, 30, 51, 22))
        self.tbNtVar_1.setObjectName(_fromUtf8("tbNtVar_1"))
        self.tbNtVar_3 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtVar_3.setGeometry(QtCore.QRect(490, 90, 51, 22))
        self.tbNtVar_3.setObjectName(_fromUtf8("tbNtVar_3"))
        self.label_37 = QtGui.QLabel(self.groupBox_3)
        self.label_37.setGeometry(QtCore.QRect(296, 183, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_37.setFont(font)
        self.label_37.setLineWidth(-5)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.leB_ = QtGui.QLineEdit(self.groupBox_3)
        self.leB_.setGeometry(QtCore.QRect(366, 183, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leB_.setFont(font)
        self.leB_.setObjectName(_fromUtf8("leB_"))
        self.tbB_Rd = QtGui.QToolButton(self.groupBox_3)
        self.tbB_Rd.setGeometry(QtCore.QRect(456, 183, 27, 22))
        self.tbB_Rd.setObjectName(_fromUtf8("tbB_Rd"))
        self.tbB_Var = QtGui.QToolButton(self.groupBox_3)
        self.tbB_Var.setGeometry(QtCore.QRect(490, 183, 51, 22))
        self.tbB_Var.setObjectName(_fromUtf8("tbB_Var"))
        self.tbB_Wr = QtGui.QToolButton(self.groupBox_3)
        self.tbB_Wr.setGeometry(QtCore.QRect(545, 183, 27, 22))
        self.tbB_Wr.setObjectName(_fromUtf8("tbB_Wr"))
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(20, 540, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setLineWidth(-5)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.tbAetWr_4 = QtGui.QToolButton(self.centralwidget)
        self.tbAetWr_4.setGeometry(QtCore.QRect(266, 540, 27, 22))
        self.tbAetWr_4.setObjectName(_fromUtf8("tbAetWr_4"))
        self.leAet_4 = QtGui.QLineEdit(self.centralwidget)
        self.leAet_4.setGeometry(QtCore.QRect(90, 540, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAet_4.setFont(font)
        self.leAet_4.setObjectName(_fromUtf8("leAet_4"))
        self.tbAetVar_4 = QtGui.QToolButton(self.centralwidget)
        self.tbAetVar_4.setGeometry(QtCore.QRect(210, 540, 51, 22))
        self.tbAetVar_4.setObjectName(_fromUtf8("tbAetVar_4"))
        self.tbAetRd_4 = QtGui.QToolButton(self.centralwidget)
        self.tbAetRd_4.setGeometry(QtCore.QRect(180, 540, 27, 22))
        self.tbAetRd_4.setObjectName(_fromUtf8("tbAetRd_4"))
        self.leAet_5 = QtGui.QLineEdit(self.centralwidget)
        self.leAet_5.setGeometry(QtCore.QRect(90, 570, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAet_5.setFont(font)
        self.leAet_5.setObjectName(_fromUtf8("leAet_5"))
        self.tbAetRd_5 = QtGui.QToolButton(self.centralwidget)
        self.tbAetRd_5.setGeometry(QtCore.QRect(180, 570, 27, 22))
        self.tbAetRd_5.setObjectName(_fromUtf8("tbAetRd_5"))
        self.tbAetWr_5 = QtGui.QToolButton(self.centralwidget)
        self.tbAetWr_5.setGeometry(QtCore.QRect(266, 570, 27, 22))
        self.tbAetWr_5.setObjectName(_fromUtf8("tbAetWr_5"))
        self.tbAetVar_5 = QtGui.QToolButton(self.centralwidget)
        self.tbAetVar_5.setGeometry(QtCore.QRect(210, 570, 51, 22))
        self.tbAetVar_5.setObjectName(_fromUtf8("tbAetVar_5"))
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(20, 570, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setLineWidth(-5)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.tbAetWr_6 = QtGui.QToolButton(self.centralwidget)
        self.tbAetWr_6.setGeometry(QtCore.QRect(266, 600, 27, 22))
        self.tbAetWr_6.setObjectName(_fromUtf8("tbAetWr_6"))
        self.leAet_6 = QtGui.QLineEdit(self.centralwidget)
        self.leAet_6.setGeometry(QtCore.QRect(90, 600, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAet_6.setFont(font)
        self.leAet_6.setObjectName(_fromUtf8("leAet_6"))
        self.label_32 = QtGui.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(20, 600, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setLineWidth(-5)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.tbAetRd_6 = QtGui.QToolButton(self.centralwidget)
        self.tbAetRd_6.setGeometry(QtCore.QRect(180, 600, 27, 22))
        self.tbAetRd_6.setObjectName(_fromUtf8("tbAetRd_6"))
        self.tbAetVar_6 = QtGui.QToolButton(self.centralwidget)
        self.tbAetVar_6.setGeometry(QtCore.QRect(210, 600, 51, 22))
        self.tbAetVar_6.setObjectName(_fromUtf8("tbAetVar_6"))
        self.teDescribe1 = QtGui.QTextEdit(self.centralwidget)
        self.teDescribe1.setGeometry(QtCore.QRect(610, 370, 311, 161))
        self.teDescribe1.setObjectName(_fromUtf8("teDescribe1"))
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(610, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.tbDescribeWr = QtGui.QToolButton(self.centralwidget)
        self.tbDescribeWr.setGeometry(QtCore.QRect(880, 210, 27, 22))
        self.tbDescribeWr.setObjectName(_fromUtf8("tbDescribeWr"))
        self.tbDescribeRd = QtGui.QToolButton(self.centralwidget)
        self.tbDescribeRd.setGeometry(QtCore.QRect(850, 210, 27, 22))
        self.tbDescribeRd.setObjectName(_fromUtf8("tbDescribeRd"))
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(610, 240, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.tbTypeIDWr = QtGui.QToolButton(self.centralwidget)
        self.tbTypeIDWr.setGeometry(QtCore.QRect(880, 237, 27, 22))
        self.tbTypeIDWr.setObjectName(_fromUtf8("tbTypeIDWr"))
        self.leTypeID = QtGui.QLineEdit(self.centralwidget)
        self.leTypeID.setGeometry(QtCore.QRect(762, 238, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leTypeID.setFont(font)
        self.leTypeID.setObjectName(_fromUtf8("leTypeID"))
        self.tbTypeIDRd = QtGui.QToolButton(self.centralwidget)
        self.tbTypeIDRd.setGeometry(QtCore.QRect(850, 237, 27, 22))
        self.tbTypeIDRd.setObjectName(_fromUtf8("tbTypeIDRd"))
        self.tbNewAddr_Wr = QtGui.QToolButton(self.centralwidget)
        self.tbNewAddr_Wr.setGeometry(QtCore.QRect(800, 320, 27, 22))
        self.tbNewAddr_Wr.setObjectName(_fromUtf8("tbNewAddr_Wr"))
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(610, 293, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.leSerNum_S = QtGui.QLineEdit(self.centralwidget)
        self.leSerNum_S.setGeometry(QtCore.QRect(610, 320, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leSerNum_S.setFont(font)
        self.leSerNum_S.setObjectName(_fromUtf8("leSerNum_S"))
        self.leAddrMB_S = QtGui.QLineEdit(self.centralwidget)
        self.leAddrMB_S.setGeometry(QtCore.QRect(710, 320, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAddrMB_S.setFont(font)
        self.leAddrMB_S.setObjectName(_fromUtf8("leAddrMB_S"))
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(710, 293, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.teDescribe = QtGui.QLineEdit(self.centralwidget)
        self.teDescribe.setGeometry(QtCore.QRect(610, 40, 311, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.teDescribe.setFont(font)
        self.teDescribe.setObjectName(_fromUtf8("teDescribe"))
        fmCondConf.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fmCondConf)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 936, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        fmCondConf.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fmCondConf)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fmCondConf.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(fmCondConf)
        QtCore.QMetaObject.connectSlotsByName(fmCondConf)

    def retranslateUi(self, fmCondConf):
        fmCondConf.setWindowTitle(_translate("fmCondConf", "Настройки кондуктометра ", None))
        self.label_16.setText(_translate("fmCondConf", "Адрес MODBUS:", None))
        self.tbAddrMBWr.setText(_translate("fmCondConf", "Wr", None))
        self.tbAddrMBRd.setText(_translate("fmCondConf", "Rd", None))
        self.tbthrATRd.setText(_translate("fmCondConf", "Rd", None))
        self.tbthrATWr.setText(_translate("fmCondConf", "Wr", None))
        self.label_17.setText(_translate("fmCondConf", "Пауза во фрейме:", None))
        self.tbConfRd.setText(_translate("fmCondConf", "Rd", None))
        self.tbConfWr.setText(_translate("fmCondConf", "Wr", None))
        self.label_18.setText(_translate("fmCondConf", "ADC conf <b>(hex)</b>:", None))
        self.label_19.setText(_translate("fmCondConf", "Серийный номер:", None))
        self.tbSerNumWr.setText(_translate("fmCondConf", "Wr", None))
        self.tbSerNumRd.setText(_translate("fmCondConf", "Rd", None))
        self.label_2.setText(_translate("fmCondConf", "Смещение нуля(32р):", None))
        self.label_12.setText(_translate("fmCondConf", "Коэффициент(32р):", None))
        self.tbZeroARd.setText(_translate("fmCondConf", "Rd", None))
        self.tbZeroAWr.setText(_translate("fmCondConf", "Wr", None))
        self.tbZeroARdVar.setText(_translate("fmCondConf", "RdVar", None))
        self.tbmKRdVar.setText(_translate("fmCondConf", "RdVar", None))
        self.tbmKRd.setText(_translate("fmCondConf", "Rd", None))
        self.tbmKWr.setText(_translate("fmCondConf", "Wr", None))
        self.tbModeRd.setText(_translate("fmCondConf", "Rd", None))
        self.tbModeWr.setText(_translate("fmCondConf", "Wr", None))
        self.label_20.setText(_translate("fmCondConf", "ADC mode <b>(hex)</b>:", None))
        self.label_21.setText(_translate("fmCondConf", "ADC IO <b>(hex)</b>:", None))
        self.tbIOWr.setText(_translate("fmCondConf", "Wr", None))
        self.tbIORd.setText(_translate("fmCondConf", "Rd", None))
        self.tbSave.setText(_translate("fmCondConf", "Сохранить в энергонезависимой памяти", None))
        self.label_22.setText(_translate("fmCondConf", "PD4...PD7 <b>(hex)</b>:", None))
        self.tbPB5Wr.setText(_translate("fmCondConf", "Wr", None))
        self.tbPD47Wr.setText(_translate("fmCondConf", "Wr", None))
        self.label_23.setText(_translate("fmCondConf", "PB5 меандр <b>(hex)</b>:", None))
        self.tbPD47Rd.setText(_translate("fmCondConf", "Rd", None))
        self.tbPB5Rd.setText(_translate("fmCondConf", "Rd", None))
        self.tbPB5Var.setText(_translate("fmCondConf", "RdVar", None))
        self.tbPD47Var.setText(_translate("fmCondConf", "RdVar", None))
        self.groupBox_3.setTitle(_translate("fmCondConf", "Коэффициенты калибровки диапазонов", None))
        self.tbAetRd_1.setText(_translate("fmCondConf", "Rd", None))
        self.tbAetWr_1.setText(_translate("fmCondConf", "Wr", None))
        self.label_24.setText(_translate("fmCondConf", "Kд 1", None))
        self.tbNtWr_1.setText(_translate("fmCondConf", "Wr", None))
        self.label_25.setText(_translate("fmCondConf", "Nд min", None))
        self.tbNtRd_1.setText(_translate("fmCondConf", "Rd", None))
        self.tbNtWr_2.setText(_translate("fmCondConf", "Wr", None))
        self.tbNtRd_2.setText(_translate("fmCondConf", "Rd", None))
        self.label_26.setText(_translate("fmCondConf", "Nд max", None))
        self.tbAetWr_2.setText(_translate("fmCondConf", "Wr", None))
        self.label_27.setText(_translate("fmCondConf", "Kд 2", None))
        self.tbAetRd_2.setText(_translate("fmCondConf", "Rd", None))
        self.tbNtWr_3.setText(_translate("fmCondConf", "Wr", None))
        self.tbNtRd_3.setText(_translate("fmCondConf", "Rd", None))
        self.label_28.setText(_translate("fmCondConf", "R/0.38K", None))
        self.tbAetWr_3.setText(_translate("fmCondConf", "Wr", None))
        self.label_29.setText(_translate("fmCondConf", "Kд 3", None))
        self.tbAetRd_3.setText(_translate("fmCondConf", "Rd", None))
        self.tbAetVar_1.setText(_translate("fmCondConf", "RdVar", None))
        self.tbAetVar_2.setText(_translate("fmCondConf", "RdVar", None))
        self.tbAetVar_3.setText(_translate("fmCondConf", "RdVar", None))
        self.tbNtVar_2.setText(_translate("fmCondConf", "RdVar", None))
        self.tbNtVar_1.setText(_translate("fmCondConf", "RdVar", None))
        self.tbNtVar_3.setText(_translate("fmCondConf", "RdVar", None))
        self.label_37.setText(_translate("fmCondConf", "B_", None))
        self.tbB_Rd.setText(_translate("fmCondConf", "Rd", None))
        self.tbB_Var.setText(_translate("fmCondConf", "RdVar", None))
        self.tbB_Wr.setText(_translate("fmCondConf", "Wr", None))
        self.label_30.setText(_translate("fmCondConf", "Kд 4", None))
        self.tbAetWr_4.setText(_translate("fmCondConf", "Wr", None))
        self.tbAetVar_4.setText(_translate("fmCondConf", "RdVar", None))
        self.tbAetRd_4.setText(_translate("fmCondConf", "Rd", None))
        self.tbAetRd_5.setText(_translate("fmCondConf", "Rd", None))
        self.tbAetWr_5.setText(_translate("fmCondConf", "Wr", None))
        self.tbAetVar_5.setText(_translate("fmCondConf", "RdVar", None))
        self.label_31.setText(_translate("fmCondConf", "Kд 5", None))
        self.tbAetWr_6.setText(_translate("fmCondConf", "Wr", None))
        self.label_32.setText(_translate("fmCondConf", "Kд 6", None))
        self.tbAetRd_6.setText(_translate("fmCondConf", "Rd", None))
        self.tbAetVar_6.setText(_translate("fmCondConf", "RdVar", None))
        self.label_33.setText(_translate("fmCondConf", "Описание", None))
        self.tbDescribeWr.setText(_translate("fmCondConf", "Wr", None))
        self.tbDescribeRd.setText(_translate("fmCondConf", "Rd", None))
        self.label_34.setText(_translate("fmCondConf", "Тип модуля", None))
        self.tbTypeIDWr.setText(_translate("fmCondConf", "Wr", None))
        self.tbTypeIDRd.setText(_translate("fmCondConf", "Rd", None))
        self.tbNewAddr_Wr.setText(_translate("fmCondConf", "Wr", None))
        self.label_35.setText(_translate("fmCondConf", "Зав. номер", None))
        self.label_36.setText(_translate("fmCondConf", "Адрес", None))
        self.menu.setTitle(_translate("fmCondConf", "?", None))

