# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\__2018\term7\svi\forms\fmCondCalib1.ui'
#
# Created: Fri Nov 16 12:04:59 2018
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmCondCalib(object):
    def setupUi(self, fmCondCalib):
        fmCondCalib.setObjectName(_fromUtf8("fmCondCalib"))
        fmCondCalib.resize(1080, 1024)
        fmCondCalib.setMinimumSize(QtCore.QSize(1080, 1024))
        fmCondCalib.setMaximumSize(QtCore.QSize(1080, 1024))
        fmCondCalib.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(fmCondCalib)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tbSaveCalib_ = QtGui.QToolButton(self.centralwidget)
        self.tbSaveCalib_.setGeometry(QtCore.QRect(700, 900, 141, 51))
        self.tbSaveCalib_.setObjectName(_fromUtf8("tbSaveCalib_"))
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(30, 10, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setLineWidth(-5)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 50, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lblCond_ed = QtGui.QLabel(self.centralwidget)
        self.lblCond_ed.setGeometry(QtCore.QRect(410, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblCond_ed.setFont(font)
        self.lblCond_ed.setText(_fromUtf8(""))
        self.lblCond_ed.setObjectName(_fromUtf8("lblCond_ed"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 750, 631, 211))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_37 = QtGui.QLabel(self.groupBox)
        self.label_37.setGeometry(QtCore.QRect(10, 150, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_37.setFont(font)
        self.label_37.setLineWidth(-5)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.leProfilName_ = QtGui.QLineEdit(self.groupBox)
        self.leProfilName_.setGeometry(QtCore.QRect(260, 60, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leProfilName_.setFont(font)
        self.leProfilName_.setObjectName(_fromUtf8("leProfilName_"))
        self.leDescr_ = QtGui.QLineEdit(self.groupBox)
        self.leDescr_.setGeometry(QtCore.QRect(150, 150, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leDescr_.setFont(font)
        self.leDescr_.setObjectName(_fromUtf8("leDescr_"))
        self.label_40 = QtGui.QLabel(self.groupBox)
        self.label_40.setGeometry(QtCore.QRect(10, 50, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_40.setFont(font)
        self.label_40.setLineWidth(-5)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.chbBKd = QtGui.QCheckBox(self.centralwidget)
        self.chbBKd.setGeometry(QtCore.QRect(20, 150, 331, 31))
        self.chbBKd.setObjectName(_fromUtf8("chbBKd"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 59, 381, 91))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(590, 59, 471, 91))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.lblKD6_2 = QtGui.QLabel(self.centralwidget)
        self.lblKD6_2.setEnabled(False)
        self.lblKD6_2.setGeometry(QtCore.QRect(60, 680, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblKD6_2.setFont(font)
        self.lblKD6_2.setLineWidth(-5)
        self.lblKD6_2.setObjectName(_fromUtf8("lblKD6_2"))
        self.tbRecalc = QtGui.QToolButton(self.centralwidget)
        self.tbRecalc.setEnabled(False)
        self.tbRecalc.setGeometry(QtCore.QRect(550, 670, 131, 51))
        self.tbRecalc.setObjectName(_fromUtf8("tbRecalc"))
        self.leCondSet = QtGui.QLineEdit(self.centralwidget)
        self.leCondSet.setEnabled(False)
        self.leCondSet.setGeometry(QtCore.QRect(360, 680, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leCondSet.setFont(font)
        self.leCondSet.setObjectName(_fromUtf8("leCondSet"))
        self.label_38 = QtGui.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(230, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_38.setFont(font)
        self.label_38.setLineWidth(-5)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.leCond_min = QtGui.QLineEdit(self.centralwidget)
        self.leCond_min.setGeometry(QtCore.QRect(660, 90, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leCond_min.setFont(font)
        self.leCond_min.setObjectName(_fromUtf8("leCond_min"))
        self.label_41 = QtGui.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(840, 90, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_41.setFont(font)
        self.label_41.setLineWidth(-5)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.leCond_max = QtGui.QLineEdit(self.centralwidget)
        self.leCond_max.setGeometry(QtCore.QRect(910, 90, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leCond_max.setFont(font)
        self.leCond_max.setObjectName(_fromUtf8("leCond_max"))
        self.label_39 = QtGui.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(600, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_39.setFont(font)
        self.label_39.setLineWidth(-5)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gbxBKd = QtGui.QGroupBox(self.centralwidget)
        self.gbxBKd.setEnabled(False)
        self.gbxBKd.setGeometry(QtCore.QRect(20, 200, 1021, 461))
        self.gbxBKd.setObjectName(_fromUtf8("gbxBKd"))
        self.lblKD4 = QtGui.QLabel(self.gbxBKd)
        self.lblKD4.setGeometry(QtCore.QRect(20, 260, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblKD4.setFont(font)
        self.lblKD4.setLineWidth(-5)
        self.lblKD4.setObjectName(_fromUtf8("lblKD4"))
        self.lblKD5 = QtGui.QLabel(self.gbxBKd)
        self.lblKD5.setGeometry(QtCore.QRect(20, 330, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblKD5.setFont(font)
        self.lblKD5.setLineWidth(-5)
        self.lblKD5.setObjectName(_fromUtf8("lblKD5"))
        self.lblKD6 = QtGui.QLabel(self.gbxBKd)
        self.lblKD6.setGeometry(QtCore.QRect(20, 400, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblKD6.setFont(font)
        self.lblKD6.setLineWidth(-5)
        self.lblKD6.setObjectName(_fromUtf8("lblKD6"))
        self.lblKD1 = QtGui.QLabel(self.gbxBKd)
        self.lblKD1.setGeometry(QtCore.QRect(20, 40, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblKD1.setFont(font)
        self.lblKD1.setLineWidth(-5)
        self.lblKD1.setObjectName(_fromUtf8("lblKD1"))
        self.lblKD3 = QtGui.QLabel(self.gbxBKd)
        self.lblKD3.setGeometry(QtCore.QRect(20, 190, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblKD3.setFont(font)
        self.lblKD3.setLineWidth(-5)
        self.lblKD3.setObjectName(_fromUtf8("lblKD3"))
        self.lblKD2 = QtGui.QLabel(self.gbxBKd)
        self.lblKD2.setGeometry(QtCore.QRect(20, 120, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblKD2.setFont(font)
        self.lblKD2.setLineWidth(-5)
        self.lblKD2.setObjectName(_fromUtf8("lblKD2"))
        self.label_48 = QtGui.QLabel(self.gbxBKd)
        self.label_48.setGeometry(QtCore.QRect(330, 390, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_48.setFont(font)
        self.label_48.setLineWidth(-5)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.label_49 = QtGui.QLabel(self.gbxBKd)
        self.label_49.setGeometry(QtCore.QRect(330, 320, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_49.setFont(font)
        self.label_49.setLineWidth(-5)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_50 = QtGui.QLabel(self.gbxBKd)
        self.label_50.setGeometry(QtCore.QRect(330, 250, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_50.setFont(font)
        self.label_50.setLineWidth(-5)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.label_51 = QtGui.QLabel(self.gbxBKd)
        self.label_51.setGeometry(QtCore.QRect(330, 183, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_51.setFont(font)
        self.label_51.setLineWidth(-5)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.label_52 = QtGui.QLabel(self.gbxBKd)
        self.label_52.setGeometry(QtCore.QRect(330, 110, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_52.setFont(font)
        self.label_52.setLineWidth(-5)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.label_53 = QtGui.QLabel(self.gbxBKd)
        self.label_53.setGeometry(QtCore.QRect(330, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_53.setFont(font)
        self.label_53.setLineWidth(-5)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.label_54 = QtGui.QLabel(self.gbxBKd)
        self.label_54.setGeometry(QtCore.QRect(610, 400, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_54.setFont(font)
        self.label_54.setLineWidth(-5)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.label_55 = QtGui.QLabel(self.gbxBKd)
        self.label_55.setGeometry(QtCore.QRect(610, 50, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_55.setFont(font)
        self.label_55.setLineWidth(-5)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_56 = QtGui.QLabel(self.gbxBKd)
        self.label_56.setGeometry(QtCore.QRect(610, 330, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_56.setFont(font)
        self.label_56.setLineWidth(-5)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_57 = QtGui.QLabel(self.gbxBKd)
        self.label_57.setGeometry(QtCore.QRect(610, 110, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_57.setFont(font)
        self.label_57.setLineWidth(-5)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.label_58 = QtGui.QLabel(self.gbxBKd)
        self.label_58.setGeometry(QtCore.QRect(610, 250, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_58.setFont(font)
        self.label_58.setLineWidth(-5)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_59 = QtGui.QLabel(self.gbxBKd)
        self.label_59.setGeometry(QtCore.QRect(610, 180, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_59.setFont(font)
        self.label_59.setLineWidth(-5)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.leB_1 = QtGui.QLineEdit(self.gbxBKd)
        self.leB_1.setGeometry(QtCore.QRect(380, 50, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leB_1.setFont(font)
        self.leB_1.setObjectName(_fromUtf8("leB_1"))
        self.leB_2 = QtGui.QLineEdit(self.gbxBKd)
        self.leB_2.setGeometry(QtCore.QRect(380, 110, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leB_2.setFont(font)
        self.leB_2.setObjectName(_fromUtf8("leB_2"))
        self.leB_3 = QtGui.QLineEdit(self.gbxBKd)
        self.leB_3.setGeometry(QtCore.QRect(380, 180, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leB_3.setFont(font)
        self.leB_3.setObjectName(_fromUtf8("leB_3"))
        self.leB_4 = QtGui.QLineEdit(self.gbxBKd)
        self.leB_4.setGeometry(QtCore.QRect(380, 250, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leB_4.setFont(font)
        self.leB_4.setObjectName(_fromUtf8("leB_4"))
        self.leB_5 = QtGui.QLineEdit(self.gbxBKd)
        self.leB_5.setGeometry(QtCore.QRect(380, 320, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leB_5.setFont(font)
        self.leB_5.setObjectName(_fromUtf8("leB_5"))
        self.leB_6 = QtGui.QLineEdit(self.gbxBKd)
        self.leB_6.setGeometry(QtCore.QRect(380, 390, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leB_6.setFont(font)
        self.leB_6.setObjectName(_fromUtf8("leB_6"))
        self.leA_1 = QtGui.QLineEdit(self.gbxBKd)
        self.leA_1.setGeometry(QtCore.QRect(660, 40, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA_1.setFont(font)
        self.leA_1.setObjectName(_fromUtf8("leA_1"))
        self.leA_2 = QtGui.QLineEdit(self.gbxBKd)
        self.leA_2.setGeometry(QtCore.QRect(660, 110, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA_2.setFont(font)
        self.leA_2.setObjectName(_fromUtf8("leA_2"))
        self.leA_3 = QtGui.QLineEdit(self.gbxBKd)
        self.leA_3.setGeometry(QtCore.QRect(660, 180, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA_3.setFont(font)
        self.leA_3.setObjectName(_fromUtf8("leA_3"))
        self.leA_4 = QtGui.QLineEdit(self.gbxBKd)
        self.leA_4.setGeometry(QtCore.QRect(660, 250, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA_4.setFont(font)
        self.leA_4.setObjectName(_fromUtf8("leA_4"))
        self.leA_5 = QtGui.QLineEdit(self.gbxBKd)
        self.leA_5.setGeometry(QtCore.QRect(660, 320, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA_5.setFont(font)
        self.leA_5.setObjectName(_fromUtf8("leA_5"))
        self.leA_6 = QtGui.QLineEdit(self.gbxBKd)
        self.leA_6.setGeometry(QtCore.QRect(660, 390, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA_6.setFont(font)
        self.leA_6.setObjectName(_fromUtf8("leA_6"))
        self.leKu_1_ = QtGui.QLineEdit(self.gbxBKd)
        self.leKu_1_.setGeometry(QtCore.QRect(118, 43, 150, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leKu_1_.setFont(font)
        self.leKu_1_.setObjectName(_fromUtf8("leKu_1_"))
        self.leKu_2_ = QtGui.QLineEdit(self.gbxBKd)
        self.leKu_2_.setGeometry(QtCore.QRect(120, 110, 150, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leKu_2_.setFont(font)
        self.leKu_2_.setObjectName(_fromUtf8("leKu_2_"))
        self.leKu_3_ = QtGui.QLineEdit(self.gbxBKd)
        self.leKu_3_.setGeometry(QtCore.QRect(120, 180, 150, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leKu_3_.setFont(font)
        self.leKu_3_.setObjectName(_fromUtf8("leKu_3_"))
        self.leKu_4_ = QtGui.QLineEdit(self.gbxBKd)
        self.leKu_4_.setGeometry(QtCore.QRect(120, 250, 150, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leKu_4_.setFont(font)
        self.leKu_4_.setObjectName(_fromUtf8("leKu_4_"))
        self.leKu_5_ = QtGui.QLineEdit(self.gbxBKd)
        self.leKu_5_.setGeometry(QtCore.QRect(120, 320, 150, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leKu_5_.setFont(font)
        self.leKu_5_.setObjectName(_fromUtf8("leKu_5_"))
        self.leKu_6_ = QtGui.QLineEdit(self.gbxBKd)
        self.leKu_6_.setGeometry(QtCore.QRect(120, 390, 150, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leKu_6_.setFont(font)
        self.leKu_6_.setObjectName(_fromUtf8("leKu_6_"))
        self.llCond_ = QtGui.QLabel(self.centralwidget)
        self.llCond_.setGeometry(QtCore.QRect(50, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.llCond_.setFont(font)
        self.llCond_.setFrameShape(QtGui.QFrame.Panel)
        self.llCond_.setFrameShadow(QtGui.QFrame.Sunken)
        self.llCond_.setText(_fromUtf8(""))
        self.llCond_.setObjectName(_fromUtf8("llCond_"))
        self.leKu_ = QtGui.QLineEdit(self.centralwidget)
        self.leKu_.setGeometry(QtCore.QRect(300, 90, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leKu_.setFont(font)
        self.leKu_.setObjectName(_fromUtf8("leKu_"))
        fmCondCalib.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(fmCondCalib)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fmCondCalib.setStatusBar(self.statusbar)
        self.actTIns = QtGui.QAction(fmCondCalib)
        self.actTIns.setObjectName(_fromUtf8("actTIns"))
        self.actTDel = QtGui.QAction(fmCondCalib)
        self.actTDel.setObjectName(_fromUtf8("actTDel"))
        self.actPrIns = QtGui.QAction(fmCondCalib)
        self.actPrIns.setObjectName(_fromUtf8("actPrIns"))
        self.actPrDel = QtGui.QAction(fmCondCalib)
        self.actPrDel.setObjectName(_fromUtf8("actPrDel"))
        self.actPrRen = QtGui.QAction(fmCondCalib)
        self.actPrRen.setObjectName(_fromUtf8("actPrRen"))

        self.retranslateUi(fmCondCalib)
        QtCore.QMetaObject.connectSlotsByName(fmCondCalib)

    def retranslateUi(self, fmCondCalib):
        fmCondCalib.setWindowTitle(_translate("fmCondCalib", "Градуировка", None))
        self.tbSaveCalib_.setText(_translate("fmCondCalib", "Сохранить", None))
        self.label_31.setText(_translate("fmCondCalib", "Профиль измерения", None))
        self.label_9.setText(_translate("fmCondCalib", "Проводимость", None))
        self.groupBox.setTitle(_translate("fmCondCalib", "Изменение наименования профиля", None))
        self.label_37.setText(_translate("fmCondCalib", " Описание профиля", None))
        self.label_40.setText(_translate("fmCondCalib", "Профиль измерения", None))
        self.chbBKd.setText(_translate("fmCondCalib", "Коррекция нелинейности", None))
        self.groupBox_2.setTitle(_translate("fmCondCalib", "Изменение характеристик профиля", None))
        self.groupBox_3.setTitle(_translate("fmCondCalib", "Диапазон измерения проводимости  ( мСм )", None))
        self.lblKD6_2.setText(_translate("fmCondCalib", "Ввод проводимости", None))
        self.tbRecalc.setText(_translate("fmCondCalib", "Пересчет", None))
        self.label_38.setText(_translate("fmCondCalib", "<html><head/><body><p>K яч</p></body></html>", None))
        self.label_41.setText(_translate("fmCondCalib", "<html><head/><body><p>Макс.</p></body></html>", None))
        self.label_39.setText(_translate("fmCondCalib", "<html><head/><body><p>Мин.</p></body></html>", None))
        self.gbxBKd.setTitle(_translate("fmCondCalib", "Коррекция нелинейности", None))
        self.lblKD4.setText(_translate("fmCondCalib", "Кд яч 4", None))
        self.lblKD5.setText(_translate("fmCondCalib", "Кд яч 5", None))
        self.lblKD6.setText(_translate("fmCondCalib", "Кд яч 6", None))
        self.lblKD1.setText(_translate("fmCondCalib", "<html><head/><body><p>Kд яч 1</p></body></html>", None))
        self.lblKD3.setText(_translate("fmCondCalib", "Kд яч 3", None))
        self.lblKD2.setText(_translate("fmCondCalib", "Kд яч 2", None))
        self.label_48.setText(_translate("fmCondCalib", "B 6", None))
        self.label_49.setText(_translate("fmCondCalib", "B 5", None))
        self.label_50.setText(_translate("fmCondCalib", "B 4", None))
        self.label_51.setText(_translate("fmCondCalib", "B 3", None))
        self.label_52.setText(_translate("fmCondCalib", "B 2", None))
        self.label_53.setText(_translate("fmCondCalib", "B 1", None))
        self.label_54.setText(_translate("fmCondCalib", "A 6", None))
        self.label_55.setText(_translate("fmCondCalib", "A 1", None))
        self.label_56.setText(_translate("fmCondCalib", "A 5", None))
        self.label_57.setText(_translate("fmCondCalib", "A 2", None))
        self.label_58.setText(_translate("fmCondCalib", "A 4", None))
        self.label_59.setText(_translate("fmCondCalib", "A 3", None))
        self.actTIns.setText(_translate("fmCondCalib", "Вставить строку", None))
        self.actTDel.setText(_translate("fmCondCalib", "Удалить строку", None))
        self.actPrIns.setText(_translate("fmCondCalib", "Новый профиль", None))
        self.actPrDel.setText(_translate("fmCondCalib", "Удалить профиль", None))
        self.actPrRen.setText(_translate("fmCondCalib", "Переименовать профиль", None))

