# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi (4)\svi\forms\fmCondPar.ui'
#
# Created: Thu Sep 13 10:26:35 2018
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmCondPar(object):
    def setupUi(self, fmCondPar):
        fmCondPar.setObjectName(_fromUtf8("fmCondPar"))
        fmCondPar.resize(1703, 1050)
        fmCondPar.setMinimumSize(QtCore.QSize(1703, 1050))
        fmCondPar.setMaximumSize(QtCore.QSize(1703, 1050))
        self.centralwidget = QtGui.QWidget(fmCondPar)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lcdDataConv_cond = QtGui.QLCDNumber(self.centralwidget)
        self.lcdDataConv_cond.setGeometry(QtCore.QRect(16, 240, 241, 41))
        self.lcdDataConv_cond.setNumDigits(14)
        self.lcdDataConv_cond.setObjectName(_fromUtf8("lcdDataConv_cond"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(15, 72, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.tbScan = QtGui.QToolButton(self.centralwidget)
        self.tbScan.setGeometry(QtCore.QRect(340, 240, 41, 41))
        self.tbScan.setObjectName(_fromUtf8("tbScan"))
        self.llData_cond = QtGui.QLabel(self.centralwidget)
        self.llData_cond.setGeometry(QtCore.QRect(280, 70, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.llData_cond.setFont(font)
        self.llData_cond.setFrameShape(QtGui.QFrame.Panel)
        self.llData_cond.setFrameShadow(QtGui.QFrame.Sunken)
        self.llData_cond.setText(_fromUtf8(""))
        self.llData_cond.setObjectName(_fromUtf8("llData_cond"))
        self.tbAutoScan = QtGui.QToolButton(self.centralwidget)
        self.tbAutoScan.setGeometry(QtCore.QRect(280, 240, 41, 41))
        self.tbAutoScan.setObjectName(_fromUtf8("tbAutoScan"))
        self.lemK = QtGui.QLineEdit(self.centralwidget)
        self.lemK.setGeometry(QtCore.QRect(1120, 220, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lemK.setFont(font)
        self.lemK.setObjectName(_fromUtf8("lemK"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(880, 220, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setLineWidth(-5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.ch24b = QtGui.QCheckBox(self.centralwidget)
        self.ch24b.setGeometry(QtCore.QRect(1360, 130, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ch24b.setFont(font)
        self.ch24b.setObjectName(_fromUtf8("ch24b"))
        self.chZeroComp = QtGui.QCheckBox(self.centralwidget)
        self.chZeroComp.setEnabled(False)
        self.chZeroComp.setGeometry(QtCore.QRect(1360, 180, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chZeroComp.setFont(font)
        self.chZeroComp.setObjectName(_fromUtf8("chZeroComp"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(850, 60, 20, 221))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.tbIgnRd = QtGui.QToolButton(self.centralwidget)
        self.tbIgnRd.setGeometry(QtCore.QRect(1220, 70, 41, 41))
        self.tbIgnRd.setObjectName(_fromUtf8("tbIgnRd"))
        self.leIgn = QtGui.QLineEdit(self.centralwidget)
        self.leIgn.setGeometry(QtCore.QRect(1120, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leIgn.setFont(font)
        self.leIgn.setObjectName(_fromUtf8("leIgn"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(880, 70, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setLineWidth(-5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tbIgnWr = QtGui.QToolButton(self.centralwidget)
        self.tbIgnWr.setGeometry(QtCore.QRect(1280, 70, 41, 41))
        self.tbIgnWr.setObjectName(_fromUtf8("tbIgnWr"))
        self.tbZeroWr = QtGui.QToolButton(self.centralwidget)
        self.tbZeroWr.setGeometry(QtCore.QRect(1280, 120, 41, 41))
        self.tbZeroWr.setObjectName(_fromUtf8("tbZeroWr"))
        self.leZero = QtGui.QLineEdit(self.centralwidget)
        self.leZero.setGeometry(QtCore.QRect(1120, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leZero.setFont(font)
        self.leZero.setObjectName(_fromUtf8("leZero"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(880, 120, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setLineWidth(-5)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.tbZeroRd = QtGui.QToolButton(self.centralwidget)
        self.tbZeroRd.setGeometry(QtCore.QRect(1220, 120, 41, 41))
        self.tbZeroRd.setObjectName(_fromUtf8("tbZeroRd"))
        self.tbMeasWr = QtGui.QToolButton(self.centralwidget)
        self.tbMeasWr.setGeometry(QtCore.QRect(1280, 170, 41, 41))
        self.tbMeasWr.setObjectName(_fromUtf8("tbMeasWr"))
        self.leMeas = QtGui.QLineEdit(self.centralwidget)
        self.leMeas.setGeometry(QtCore.QRect(1120, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leMeas.setFont(font)
        self.leMeas.setObjectName(_fromUtf8("leMeas"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(880, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setLineWidth(-5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.tbMeasRd = QtGui.QToolButton(self.centralwidget)
        self.tbMeasRd.setGeometry(QtCore.QRect(1220, 170, 41, 41))
        self.tbMeasRd.setObjectName(_fromUtf8("tbMeasRd"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(15, 18, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.leAddrMB = QtGui.QLineEdit(self.centralwidget)
        self.leAddrMB.setGeometry(QtCore.QRect(200, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAddrMB.setFont(font)
        self.leAddrMB.setObjectName(_fromUtf8("leAddrMB"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 50, 811, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.tbmKRd = QtGui.QToolButton(self.centralwidget)
        self.tbmKRd.setGeometry(QtCore.QRect(1220, 220, 41, 41))
        self.tbmKRd.setObjectName(_fromUtf8("tbmKRd"))
        self.tbmKWr = QtGui.QToolButton(self.centralwidget)
        self.tbmKWr.setGeometry(QtCore.QRect(1280, 220, 41, 41))
        self.tbmKWr.setObjectName(_fromUtf8("tbmKWr"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(18, 180, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtGui.QFrame.Box)
        self.label_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 290, 1901, 31))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(15, 310, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.llDataF_cond = QtGui.QLabel(self.centralwidget)
        self.llDataF_cond.setGeometry(QtCore.QRect(250, 320, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.llDataF_cond.setFont(font)
        self.llDataF_cond.setFrameShape(QtGui.QFrame.Panel)
        self.llDataF_cond.setFrameShadow(QtGui.QFrame.Sunken)
        self.llDataF_cond.setText(_fromUtf8(""))
        self.llDataF_cond.setObjectName(_fromUtf8("llDataF_cond"))
        self.lcdDataConvF_cond = QtGui.QLCDNumber(self.centralwidget)
        self.lcdDataConvF_cond.setGeometry(QtCore.QRect(17, 370, 241, 41))
        self.lcdDataConvF_cond.setNumDigits(14)
        self.lcdDataConvF_cond.setObjectName(_fromUtf8("lcdDataConvF_cond"))
        self.leWSize = QtGui.QLineEdit(self.centralwidget)
        self.leWSize.setGeometry(QtCore.QRect(879, 328, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leWSize.setFont(font)
        self.leWSize.setObjectName(_fromUtf8("leWSize"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(650, 380, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setLineWidth(-5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.leMinCntS = QtGui.QLineEdit(self.centralwidget)
        self.leMinCntS.setGeometry(QtCore.QRect(879, 379, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leMinCntS.setFont(font)
        self.leMinCntS.setObjectName(_fromUtf8("leMinCntS"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(650, 330, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setLineWidth(-5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.llCntS = QtGui.QLabel(self.centralwidget)
        self.llCntS.setGeometry(QtCore.QRect(1230, 330, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.llCntS.setFont(font)
        self.llCntS.setFrameShape(QtGui.QFrame.Panel)
        self.llCntS.setFrameShadow(QtGui.QFrame.Sunken)
        self.llCntS.setText(_fromUtf8(""))
        self.llCntS.setObjectName(_fromUtf8("llCntS"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1000, 330, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.llNumPass = QtGui.QLabel(self.centralwidget)
        self.llNumPass.setGeometry(QtCore.QRect(1230, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.llNumPass.setFont(font)
        self.llNumPass.setFrameShape(QtGui.QFrame.Panel)
        self.llNumPass.setFrameShadow(QtGui.QFrame.Sunken)
        self.llNumPass.setText(_fromUtf8(""))
        self.llNumPass.setObjectName(_fromUtf8("llNumPass"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1000, 380, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 420, 1851, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 440, 441, 541))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.cbPD1 = QtGui.QCheckBox(self.groupBox)
        self.cbPD1.setGeometry(QtCore.QRect(10, 50, 391, 31))
        self.cbPD1.setObjectName(_fromUtf8("cbPD1"))
        self.cbPD2 = QtGui.QCheckBox(self.groupBox)
        self.cbPD2.setGeometry(QtCore.QRect(10, 100, 411, 41))
        self.cbPD2.setObjectName(_fromUtf8("cbPD2"))
        self.cbPD3 = QtGui.QCheckBox(self.groupBox)
        self.cbPD3.setGeometry(QtCore.QRect(10, 150, 371, 31))
        self.cbPD3.setObjectName(_fromUtf8("cbPD3"))
        self.cbPD4 = QtGui.QCheckBox(self.groupBox)
        self.cbPD4.setGeometry(QtCore.QRect(10, 200, 411, 41))
        self.cbPD4.setObjectName(_fromUtf8("cbPD4"))
        self.lePD47 = QtGui.QLineEdit(self.groupBox)
        self.lePD47.setGeometry(QtCore.QRect(10, 490, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lePD47.setFont(font)
        self.lePD47.setObjectName(_fromUtf8("lePD47"))
        self.tbPD47Rd = QtGui.QToolButton(self.groupBox)
        self.tbPD47Rd.setGeometry(QtCore.QRect(100, 480, 41, 41))
        self.tbPD47Rd.setObjectName(_fromUtf8("tbPD47Rd"))
        self.tbPD47Wr = QtGui.QToolButton(self.groupBox)
        self.tbPD47Wr.setGeometry(QtCore.QRect(160, 480, 41, 41))
        self.tbPD47Wr.setObjectName(_fromUtf8("tbPD47Wr"))
        self.cbPDAuto = QtGui.QCheckBox(self.groupBox)
        self.cbPDAuto.setGeometry(QtCore.QRect(10, 430, 231, 51))
        self.cbPDAuto.setObjectName(_fromUtf8("cbPDAuto"))
        self.cbPDXx10 = QtGui.QCheckBox(self.groupBox)
        self.cbPDXx10.setGeometry(QtCore.QRect(10, 390, 231, 41))
        self.cbPDXx10.setObjectName(_fromUtf8("cbPDXx10"))
        self.cbPD6 = QtGui.QCheckBox(self.groupBox)
        self.cbPD6.setGeometry(QtCore.QRect(10, 300, 421, 31))
        self.cbPD6.setObjectName(_fromUtf8("cbPD6"))
        self.cbPD5 = QtGui.QCheckBox(self.groupBox)
        self.cbPD5.setGeometry(QtCore.QRect(10, 250, 431, 31))
        self.cbPD5.setObjectName(_fromUtf8("cbPD5"))
        self.cbPD7 = QtGui.QCheckBox(self.groupBox)
        self.cbPD7.setGeometry(QtCore.QRect(10, 340, 401, 51))
        self.cbPD7.setObjectName(_fromUtf8("cbPD7"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(460, 440, 241, 371))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.leFreqMeandr = QtGui.QLineEdit(self.groupBox_2)
        self.leFreqMeandr.setGeometry(QtCore.QRect(10, 310, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leFreqMeandr.setFont(font)
        self.leFreqMeandr.setObjectName(_fromUtf8("leFreqMeandr"))
        self.tbFreqMeandrRd = QtGui.QToolButton(self.groupBox_2)
        self.tbFreqMeandrRd.setGeometry(QtCore.QRect(110, 310, 41, 41))
        self.tbFreqMeandrRd.setObjectName(_fromUtf8("tbFreqMeandrRd"))
        self.rb500 = QtGui.QRadioButton(self.groupBox_2)
        self.rb500.setGeometry(QtCore.QRect(20, 50, 91, 31))
        self.rb500.setObjectName(_fromUtf8("rb500"))
        self.rb5000 = QtGui.QRadioButton(self.groupBox_2)
        self.rb5000.setGeometry(QtCore.QRect(20, 150, 161, 31))
        self.rb5000.setObjectName(_fromUtf8("rb5000"))
        self.rbOff = QtGui.QRadioButton(self.groupBox_2)
        self.rbOff.setGeometry(QtCore.QRect(20, 200, 121, 31))
        self.rbOff.setObjectName(_fromUtf8("rbOff"))
        self.tbFreqMeandrWr = QtGui.QToolButton(self.groupBox_2)
        self.tbFreqMeandrWr.setGeometry(QtCore.QRect(170, 310, 41, 41))
        self.tbFreqMeandrWr.setObjectName(_fromUtf8("tbFreqMeandrWr"))
        self.rbOn = QtGui.QRadioButton(self.groupBox_2)
        self.rbOn.setGeometry(QtCore.QRect(20, 100, 111, 31))
        self.rbOn.setObjectName(_fromUtf8("rbOn"))
        self.rbAuto = QtGui.QRadioButton(self.groupBox_2)
        self.rbAuto.setGeometry(QtCore.QRect(21, 250, 211, 31))
        self.rbAuto.setObjectName(_fromUtf8("rbAuto"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(720, 440, 621, 351))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.leAet_1 = QtGui.QLineEdit(self.groupBox_3)
        self.leAet_1.setGeometry(QtCore.QRect(70, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAet_1.setFont(font)
        self.leAet_1.setObjectName(_fromUtf8("leAet_1"))
        self.tbAetRd_1 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetRd_1.setGeometry(QtCore.QRect(160, 50, 41, 41))
        self.tbAetRd_1.setObjectName(_fromUtf8("tbAetRd_1"))
        self.tbAetWr_1 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetWr_1.setGeometry(QtCore.QRect(210, 50, 41, 41))
        self.tbAetWr_1.setObjectName(_fromUtf8("tbAetWr_1"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(10, 50, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setLineWidth(-5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.tbNtWr_1 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtWr_1.setGeometry(QtCore.QRect(540, 60, 41, 41))
        self.tbNtWr_1.setObjectName(_fromUtf8("tbNtWr_1"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(300, 60, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setLineWidth(-5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.leNt_1 = QtGui.QLineEdit(self.groupBox_3)
        self.leNt_1.setGeometry(QtCore.QRect(400, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leNt_1.setFont(font)
        self.leNt_1.setObjectName(_fromUtf8("leNt_1"))
        self.tbNtRd_1 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtRd_1.setGeometry(QtCore.QRect(490, 60, 41, 41))
        self.tbNtRd_1.setObjectName(_fromUtf8("tbNtRd_1"))
        self.tbNtWr_2 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtWr_2.setGeometry(QtCore.QRect(540, 110, 41, 41))
        self.tbNtWr_2.setObjectName(_fromUtf8("tbNtWr_2"))
        self.tbNtRd_2 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtRd_2.setGeometry(QtCore.QRect(490, 110, 41, 41))
        self.tbNtRd_2.setObjectName(_fromUtf8("tbNtRd_2"))
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(300, 110, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setLineWidth(-5)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.tbAetWr_2 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetWr_2.setGeometry(QtCore.QRect(210, 100, 41, 41))
        self.tbAetWr_2.setObjectName(_fromUtf8("tbAetWr_2"))
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(10, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setLineWidth(-5)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.leNt_2 = QtGui.QLineEdit(self.groupBox_3)
        self.leNt_2.setGeometry(QtCore.QRect(400, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leNt_2.setFont(font)
        self.leNt_2.setObjectName(_fromUtf8("leNt_2"))
        self.leAet_2 = QtGui.QLineEdit(self.groupBox_3)
        self.leAet_2.setGeometry(QtCore.QRect(70, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAet_2.setFont(font)
        self.leAet_2.setObjectName(_fromUtf8("leAet_2"))
        self.tbAetRd_2 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetRd_2.setGeometry(QtCore.QRect(160, 100, 41, 41))
        self.tbAetRd_2.setObjectName(_fromUtf8("tbAetRd_2"))
        self.tbNtWr_3 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtWr_3.setGeometry(QtCore.QRect(540, 160, 41, 41))
        self.tbNtWr_3.setObjectName(_fromUtf8("tbNtWr_3"))
        self.tbNtRd_3 = QtGui.QToolButton(self.groupBox_3)
        self.tbNtRd_3.setGeometry(QtCore.QRect(490, 160, 41, 41))
        self.tbNtRd_3.setObjectName(_fromUtf8("tbNtRd_3"))
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(300, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setLineWidth(-5)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.tbAetWr_3 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetWr_3.setGeometry(QtCore.QRect(210, 150, 41, 41))
        self.tbAetWr_3.setObjectName(_fromUtf8("tbAetWr_3"))
        self.label_24 = QtGui.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(10, 150, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setLineWidth(-5)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.leNt_3 = QtGui.QLineEdit(self.groupBox_3)
        self.leNt_3.setGeometry(QtCore.QRect(400, 160, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leNt_3.setFont(font)
        self.leNt_3.setObjectName(_fromUtf8("leNt_3"))
        self.leAet_3 = QtGui.QLineEdit(self.groupBox_3)
        self.leAet_3.setGeometry(QtCore.QRect(70, 150, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAet_3.setFont(font)
        self.leAet_3.setObjectName(_fromUtf8("leAet_3"))
        self.tbAetRd_3 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetRd_3.setGeometry(QtCore.QRect(160, 150, 41, 41))
        self.tbAetRd_3.setObjectName(_fromUtf8("tbAetRd_3"))
        self.tbAetRd_4 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetRd_4.setGeometry(QtCore.QRect(160, 200, 41, 41))
        self.tbAetRd_4.setObjectName(_fromUtf8("tbAetRd_4"))
        self.tbAetWr_4 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetWr_4.setGeometry(QtCore.QRect(210, 200, 41, 41))
        self.tbAetWr_4.setObjectName(_fromUtf8("tbAetWr_4"))
        self.leAet_4 = QtGui.QLineEdit(self.groupBox_3)
        self.leAet_4.setGeometry(QtCore.QRect(70, 205, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAet_4.setFont(font)
        self.leAet_4.setObjectName(_fromUtf8("leAet_4"))
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(10, 200, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setLineWidth(-5)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(10, 250, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setLineWidth(-5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.leAet_5 = QtGui.QLineEdit(self.groupBox_3)
        self.leAet_5.setGeometry(QtCore.QRect(70, 250, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAet_5.setFont(font)
        self.leAet_5.setObjectName(_fromUtf8("leAet_5"))
        self.tbAetWr_5 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetWr_5.setGeometry(QtCore.QRect(210, 250, 41, 41))
        self.tbAetWr_5.setObjectName(_fromUtf8("tbAetWr_5"))
        self.tbAetRd_5 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetRd_5.setGeometry(QtCore.QRect(160, 250, 41, 41))
        self.tbAetRd_5.setObjectName(_fromUtf8("tbAetRd_5"))
        self.tbAetWr_6 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetWr_6.setGeometry(QtCore.QRect(210, 300, 41, 41))
        self.tbAetWr_6.setObjectName(_fromUtf8("tbAetWr_6"))
        self.tbAetRd_6 = QtGui.QToolButton(self.groupBox_3)
        self.tbAetRd_6.setGeometry(QtCore.QRect(160, 300, 41, 41))
        self.tbAetRd_6.setObjectName(_fromUtf8("tbAetRd_6"))
        self.leAet_6 = QtGui.QLineEdit(self.groupBox_3)
        self.leAet_6.setGeometry(QtCore.QRect(70, 300, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAet_6.setFont(font)
        self.leAet_6.setObjectName(_fromUtf8("leAet_6"))
        self.label_28 = QtGui.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(0, 300, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setLineWidth(-5)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.llDataBand = QtGui.QLabel(self.centralwidget)
        self.llDataBand.setGeometry(QtCore.QRect(150, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.llDataBand.setFont(font)
        self.llDataBand.setFrameShape(QtGui.QFrame.Panel)
        self.llDataBand.setFrameShadow(QtGui.QFrame.Sunken)
        self.llDataBand.setText(_fromUtf8(""))
        self.llDataBand.setObjectName(_fromUtf8("llDataBand"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(14, 120, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lcdDataConvF_cond_1 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdDataConvF_cond_1.setGeometry(QtCore.QRect(400, 370, 181, 41))
        self.lcdDataConvF_cond_1.setNumDigits(11)
        self.lcdDataConvF_cond_1.setObjectName(_fromUtf8("lcdDataConvF_cond_1"))
        self.lcdDataConv_cond_1 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdDataConv_cond_1.setGeometry(QtCore.QRect(420, 240, 191, 41))
        self.lcdDataConv_cond_1.setNumDigits(11)
        self.lcdDataConv_cond_1.setObjectName(_fromUtf8("lcdDataConv_cond_1"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(380, 320, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.llDataBand_2 = QtGui.QLabel(self.centralwidget)
        self.llDataBand_2.setGeometry(QtCore.QRect(270, 118, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.llDataBand_2.setFont(font)
        self.llDataBand_2.setFrameShape(QtGui.QFrame.Panel)
        self.llDataBand_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.llDataBand_2.setText(_fromUtf8(""))
        self.llDataBand_2.setObjectName(_fromUtf8("llDataBand_2"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(419, 70, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setLineWidth(-5)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.leKu = QtGui.QLineEdit(self.centralwidget)
        self.leKu.setGeometry(QtCore.QRect(470, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leKu.setFont(font)
        self.leKu.setObjectName(_fromUtf8("leKu"))
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(1350, 660, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_33.setFont(font)
        self.label_33.setLineWidth(-5)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(1350, 560, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setLineWidth(-5)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(1350, 500, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setLineWidth(-5)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.leAetu_2 = QtGui.QLineEdit(self.centralwidget)
        self.leAetu_2.setGeometry(QtCore.QRect(1450, 560, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAetu_2.setFont(font)
        self.leAetu_2.setObjectName(_fromUtf8("leAetu_2"))
        self.leAetu_6 = QtGui.QLineEdit(self.centralwidget)
        self.leAetu_6.setGeometry(QtCore.QRect(1450, 750, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAetu_6.setFont(font)
        self.leAetu_6.setObjectName(_fromUtf8("leAetu_6"))
        self.leAetu_1 = QtGui.QLineEdit(self.centralwidget)
        self.leAetu_1.setGeometry(QtCore.QRect(1450, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAetu_1.setFont(font)
        self.leAetu_1.setObjectName(_fromUtf8("leAetu_1"))
        self.leAetu_4 = QtGui.QLineEdit(self.centralwidget)
        self.leAetu_4.setGeometry(QtCore.QRect(1450, 660, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAetu_4.setFont(font)
        self.leAetu_4.setObjectName(_fromUtf8("leAetu_4"))
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(1350, 750, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_35.setFont(font)
        self.label_35.setLineWidth(-5)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.leAetu_3 = QtGui.QLineEdit(self.centralwidget)
        self.leAetu_3.setGeometry(QtCore.QRect(1450, 610, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAetu_3.setFont(font)
        self.leAetu_3.setObjectName(_fromUtf8("leAetu_3"))
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(1350, 610, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setLineWidth(-5)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.leAetu_5 = QtGui.QLineEdit(self.centralwidget)
        self.leAetu_5.setGeometry(QtCore.QRect(1450, 710, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAetu_5.setFont(font)
        self.leAetu_5.setObjectName(_fromUtf8("leAetu_5"))
        self.tbAetuWr = QtGui.QToolButton(self.centralwidget)
        self.tbAetuWr.setGeometry(QtCore.QRect(1540, 790, 41, 41))
        self.tbAetuWr.setObjectName(_fromUtf8("tbAetuWr"))
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(420, 122, 40, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_36.setFont(font)
        self.label_36.setLineWidth(-5)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.leB = QtGui.QLineEdit(self.centralwidget)
        self.leB.setGeometry(QtCore.QRect(470, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leB.setFont(font)
        self.leB.setObjectName(_fromUtf8("leB"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 180, 681, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Serif"))
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtGui.QFrame.Box)
        self.label_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.leB_ = QtGui.QLineEdit(self.centralwidget)
        self.leB_.setGeometry(QtCore.QRect(540, 820, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leB_.setFont(font)
        self.leB_.setObjectName(_fromUtf8("leB_"))
        self.tbmB_Rd = QtGui.QToolButton(self.centralwidget)
        self.tbmB_Rd.setGeometry(QtCore.QRect(630, 820, 41, 41))
        self.tbmB_Rd.setObjectName(_fromUtf8("tbmB_Rd"))
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(470, 822, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setLineWidth(-5)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_37 = QtGui.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(1380, 800, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_37.setFont(font)
        self.label_37.setLineWidth(-5)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.leB_6 = QtGui.QLineEdit(self.centralwidget)
        self.leB_6.setGeometry(QtCore.QRect(1450, 790, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leB_6.setFont(font)
        self.leB_6.setObjectName(_fromUtf8("leB_6"))
        self.tbmB_Wr = QtGui.QToolButton(self.centralwidget)
        self.tbmB_Wr.setGeometry(QtCore.QRect(680, 820, 41, 41))
        self.tbmB_Wr.setObjectName(_fromUtf8("tbmB_Wr"))
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(1350, 700, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setLineWidth(-5)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        fmCondPar.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fmCondPar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1703, 38))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        fmCondPar.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fmCondPar)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fmCondPar.setStatusBar(self.statusbar)
        self.actConf = QtGui.QAction(fmCondPar)
        self.actConf.setObjectName(_fromUtf8("actConf"))

        self.retranslateUi(fmCondPar)
        QtCore.QMetaObject.connectSlotsByName(fmCondPar)

    def retranslateUi(self, fmCondPar):
        fmCondPar.setWindowTitle(_translate("fmCondPar", "Кондуктометр", None))
        self.label.setText(_translate("fmCondPar", "Данные АЦП (Adc_rez):", None))
        self.tbScan.setText(_translate("fmCondPar", "Rd", None))
        self.tbAutoScan.setText(_translate("fmCondPar", "A", None))
        self.label_12.setText(_translate("fmCondPar", "Коэффициент(32р):", None))
        self.ch24b.setText(_translate("fmCondPar", "24р  АЦП", None))
        self.chZeroComp.setText(_translate("fmCondPar", "Автокомпенсация нуля", None))
        self.tbIgnRd.setText(_translate("fmCondPar", "Rd", None))
        self.label_13.setText(_translate("fmCondPar", "zcntIgn = ", None))
        self.tbIgnWr.setText(_translate("fmCondPar", "Wr", None))
        self.tbZeroWr.setText(_translate("fmCondPar", "Wr", None))
        self.label_14.setText(_translate("fmCondPar", "zcntZero = ", None))
        self.tbZeroRd.setText(_translate("fmCondPar", "Rd", None))
        self.tbMeasWr.setText(_translate("fmCondPar", "Wr", None))
        self.label_15.setText(_translate("fmCondPar", "mcntMeas = ", None))
        self.tbMeasRd.setText(_translate("fmCondPar", "Rd", None))
        self.label_16.setText(_translate("fmCondPar", "Адрес MODBUS:", None))
        self.tbmKRd.setText(_translate("fmCondPar", "Rd", None))
        self.tbmKWr.setText(_translate("fmCondPar", "Wr", None))
        self.label_3.setText(_translate("fmCondPar", "<html><head/><body><p><span style=\" font-size:12pt;\">R </span><span style=\" font-size:12pt; vertical-align:sub;\">Выход</span><span style=\" font-size:12pt;\"> = К</span><span style=\" font-size:12pt; vertical-align:sub;\">дi</span><span style=\" font-size:12pt;\">* N</span></p></body></html>", None))
        self.label_4.setText(_translate("fmCondPar", "R Выход (фильтр):", None))
        self.label_17.setText(_translate("fmCondPar", "Мин. отсчетов:", None))
        self.label_18.setText(_translate("fmCondPar", "Размер окна:", None))
        self.label_5.setText(_translate("fmCondPar", "Значащие отсчеты:", None))
        self.label_6.setText(_translate("fmCondPar", "Кол-во итераций:", None))
        self.groupBox.setTitle(_translate("fmCondPar", "Выходы PD Out", None))
        self.cbPD1.setText(_translate("fmCondPar", "Диапазон 1 (PD4 х1 R=100К Кд1)", None))
        self.cbPD2.setText(_translate("fmCondPar", "Диапазон 2 (PD4 x10 R=100К Кд1)", None))
        self.cbPD3.setText(_translate("fmCondPar", "Диапазон 3 (PD6 х1 R=50K Кд2)", None))
        self.cbPD4.setText(_translate("fmCondPar", "Диапазон 4 (PD6 х1 R=3K8 Кд3) ", None))
        self.tbPD47Rd.setText(_translate("fmCondPar", "Rd", None))
        self.tbPD47Wr.setText(_translate("fmCondPar", "Wr", None))
        self.cbPDAuto.setText(_translate("fmCondPar", "Автоопределение", None))
        self.cbPDXx10.setText(_translate("fmCondPar", "Усиление    (х10)", None))
        self.cbPD6.setText(_translate("fmCondPar", "Диапазон 6 (PD6x10  R=0.380К Кд4)", None))
        self.cbPD5.setText(_translate("fmCondPar", "Диапазон 5 (PD6 x 1  R=0.380К  Кд4)", None))
        self.cbPD7.setText(_translate("fmCondPar", "Диапазон 7 (PD6 x 10)  R=0К Кд5)", None))
        self.groupBox_2.setTitle(_translate("fmCondPar", "Частота меандра PB5", None))
        self.tbFreqMeandrRd.setText(_translate("fmCondPar", "Rd", None))
        self.rb500.setText(_translate("fmCondPar", "500 Гц", None))
        self.rb5000.setText(_translate("fmCondPar", "5000 Гц", None))
        self.rbOff.setText(_translate("fmCondPar", "\"0\"", None))
        self.tbFreqMeandrWr.setText(_translate("fmCondPar", "Wr", None))
        self.rbOn.setText(_translate("fmCondPar", "\"1\"", None))
        self.rbAuto.setText(_translate("fmCondPar", "Автоустановка", None))
        self.groupBox_3.setTitle(_translate("fmCondPar", "Коэффициенты калибровки диапазонов", None))
        self.tbAetRd_1.setText(_translate("fmCondPar", "Rd", None))
        self.tbAetWr_1.setText(_translate("fmCondPar", "Wr", None))
        self.label_19.setText(_translate("fmCondPar", "<html><head/><body><p>Kд 1</p></body></html>", None))
        self.tbNtWr_1.setText(_translate("fmCondPar", "Wr", None))
        self.label_20.setText(_translate("fmCondPar", "Nд min", None))
        self.tbNtRd_1.setText(_translate("fmCondPar", "Rd", None))
        self.tbNtWr_2.setText(_translate("fmCondPar", "Wr", None))
        self.tbNtRd_2.setText(_translate("fmCondPar", "Rd", None))
        self.label_21.setText(_translate("fmCondPar", "Nд max", None))
        self.tbAetWr_2.setText(_translate("fmCondPar", "Wr", None))
        self.label_22.setText(_translate("fmCondPar", "Kд 2", None))
        self.tbAetRd_2.setText(_translate("fmCondPar", "Rd", None))
        self.tbNtWr_3.setText(_translate("fmCondPar", "Wr", None))
        self.tbNtRd_3.setText(_translate("fmCondPar", "Rd", None))
        self.label_23.setText(_translate("fmCondPar", "R/0.38K", None))
        self.tbAetWr_3.setText(_translate("fmCondPar", "Wr", None))
        self.label_24.setText(_translate("fmCondPar", "Kд 3", None))
        self.tbAetRd_3.setText(_translate("fmCondPar", "Rd", None))
        self.tbAetRd_4.setText(_translate("fmCondPar", "Rd", None))
        self.tbAetWr_4.setText(_translate("fmCondPar", "Wr", None))
        self.label_25.setText(_translate("fmCondPar", "Кд 4", None))
        self.label_26.setText(_translate("fmCondPar", "Кд 5", None))
        self.tbAetWr_5.setText(_translate("fmCondPar", "Wr", None))
        self.tbAetRd_5.setText(_translate("fmCondPar", "Rd", None))
        self.tbAetWr_6.setText(_translate("fmCondPar", "Wr", None))
        self.tbAetRd_6.setText(_translate("fmCondPar", "Rd", None))
        self.label_28.setText(_translate("fmCondPar", "Кд 6", None))
        self.label_7.setText(_translate("fmCondPar", "Диапазон", None))
        self.label_9.setText(_translate("fmCondPar", "X Выход (фильтр):", None))
        self.label_27.setText(_translate("fmCondPar", "Кяч =", None))
        self.label_33.setText(_translate("fmCondPar", "Кд яч 4", None))
        self.label_31.setText(_translate("fmCondPar", "Kд яч 2", None))
        self.label_32.setText(_translate("fmCondPar", "<html><head/><body><p>Kд яч 1</p></body></html>", None))
        self.label_35.setText(_translate("fmCondPar", "Кд яч 6", None))
        self.label_29.setText(_translate("fmCondPar", "Kд яч 3", None))
        self.tbAetuWr.setText(_translate("fmCondPar", "Wr", None))
        self.label_36.setText(_translate("fmCondPar", "B =", None))
        self.label_8.setText(_translate("fmCondPar", "<html><head/><body><p><span style=\" font-size:12pt;\">X </span><span style=\" font-size:12pt; vertical-align:sub;\">Выход</span><span style=\" font-size:12pt;\"> = К </span><span style=\" font-size:12pt; vertical-align:sub;\">яч</span><span style=\" font-size:12pt;\">/(К </span><span style=\" font-size:12pt; vertical-align:sub;\">яч д*</span><span style=\" font-size:12pt;\">R </span><span style=\" font-size:12pt; vertical-align:sub;\">Выход</span><span style=\" font-size:12pt;\">)+B- К </span><span style=\" font-size:12pt; vertical-align:sub;\">яч*</span><span style=\" font-size:12pt;\">1.956947E-6</span></p></body></html>", None))
        self.tbmB_Rd.setText(_translate("fmCondPar", "Rd", None))
        self.label_30.setText(_translate("fmCondPar", "B_", None))
        self.label_37.setText(_translate("fmCondPar", "B 6", None))
        self.tbmB_Wr.setText(_translate("fmCondPar", "Wr", None))
        self.label_34.setText(_translate("fmCondPar", "Кд яч 5", None))
        self.actConf.setText(_translate("fmCondPar", "Настройки", None))

