# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi_meteo_19_11_2015\svi\forms\fmCreateConfig.ui'
#
# Created: Fri Nov 27 14:42:11 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmCreateConfig(object):
    def setupUi(self, fmCreateConfig):
        fmCreateConfig.setObjectName(_fromUtf8("fmCreateConfig"))
        fmCreateConfig.resize(750, 680)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(fmCreateConfig.sizePolicy().hasHeightForWidth())
        fmCreateConfig.setSizePolicy(sizePolicy)
        fmCreateConfig.setMinimumSize(QtCore.QSize(750, 680))
        fmCreateConfig.setSizeIncrement(QtCore.QSize(1, 1))
        fmCreateConfig.setDocumentMode(True)
        self.centralwidget = QtGui.QWidget(fmCreateConfig)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 256, 361, 231))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.lwVPIn = QtGui.QListWidget(self.groupBox_4)
        self.lwVPIn.setGeometry(QtCore.QRect(10, 40, 341, 80))
        self.lwVPIn.setObjectName(_fromUtf8("lwVPIn"))
        self.lwVPOut = QtGui.QListWidget(self.groupBox_4)
        self.lwVPOut.setGeometry(QtCore.QRect(10, 145, 341, 80))
        self.lwVPOut.setObjectName(_fromUtf8("lwVPOut"))
        self.lbl1_13 = QtGui.QLabel(self.groupBox_4)
        self.lbl1_13.setGeometry(QtCore.QRect(10, 125, 118, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_13.setFont(font)
        self.lbl1_13.setLineWidth(-5)
        self.lbl1_13.setObjectName(_fromUtf8("lbl1_13"))
        self.lbl1_12 = QtGui.QLabel(self.groupBox_4)
        self.lbl1_12.setGeometry(QtCore.QRect(10, 19, 110, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_12.setFont(font)
        self.lbl1_12.setLineWidth(-5)
        self.lbl1_12.setObjectName(_fromUtf8("lbl1_12"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 11, 197, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.lwVP = QtGui.QListWidget(self.centralwidget)
        self.lwVP.setGeometry(QtCore.QRect(11, 31, 351, 192))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwVP.sizePolicy().hasHeightForWidth())
        self.lwVP.setSizePolicy(sizePolicy)
        self.lwVP.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lwVP.setObjectName(_fromUtf8("lwVP"))
        self.tbChangeVPList = QtGui.QToolButton(self.centralwidget)
        self.tbChangeVPList.setGeometry(QtCore.QRect(11, 229, 69, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbChangeVPList.setFont(font)
        self.tbChangeVPList.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbChangeVPList.setArrowType(QtCore.Qt.NoArrow)
        self.tbChangeVPList.setObjectName(_fromUtf8("tbChangeVPList"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 495, 361, 151))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.tbTest_ = QtGui.QToolButton(self.groupBox_3)
        self.tbTest_.setGeometry(QtCore.QRect(10, 117, 42, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbTest_.setFont(font)
        self.tbTest_.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbTest_.setArrowType(QtCore.Qt.NoArrow)
        self.tbTest_.setObjectName(_fromUtf8("tbTest_"))
        self.leConfName = QtGui.QLineEdit(self.groupBox_3)
        self.leConfName.setGeometry(QtCore.QRect(10, 45, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leConfName.setFont(font)
        self.leConfName.setObjectName(_fromUtf8("leConfName"))
        self.tbSaveConfig = QtGui.QToolButton(self.groupBox_3)
        self.tbSaveConfig.setGeometry(QtCore.QRect(185, 120, 166, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbSaveConfig.setFont(font)
        self.tbSaveConfig.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbSaveConfig.setArrowType(QtCore.Qt.NoArrow)
        self.tbSaveConfig.setObjectName(_fromUtf8("tbSaveConfig"))
        self.lbl1_8 = QtGui.QLabel(self.groupBox_3)
        self.lbl1_8.setGeometry(QtCore.QRect(10, 23, 169, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_8.setFont(font)
        self.lbl1_8.setLineWidth(-5)
        self.lbl1_8.setObjectName(_fromUtf8("lbl1_8"))
        self.lbl1_11 = QtGui.QLabel(self.groupBox_3)
        self.lbl1_11.setGeometry(QtCore.QRect(10, 70, 169, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_11.setFont(font)
        self.lbl1_11.setLineWidth(-5)
        self.lbl1_11.setObjectName(_fromUtf8("lbl1_11"))
        self.leConfDescr = QtGui.QLineEdit(self.groupBox_3)
        self.leConfDescr.setGeometry(QtCore.QRect(10, 92, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leConfDescr.setFont(font)
        self.leConfDescr.setObjectName(_fromUtf8("leConfDescr"))
        self.tbConfDescr = QtGui.QToolButton(self.groupBox_3)
        self.tbConfDescr.setGeometry(QtCore.QRect(270, 93, 78, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbConfDescr.setFont(font)
        self.tbConfDescr.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbConfDescr.setArrowType(QtCore.Qt.NoArrow)
        self.tbConfDescr.setObjectName(_fromUtf8("tbConfDescr"))
        self.lwConfVPOut = QtGui.QListWidget(self.centralwidget)
        self.lwConfVPOut.setEnabled(True)
        self.lwConfVPOut.setGeometry(QtCore.QRect(390, 297, 351, 80))
        self.lwConfVPOut.setObjectName(_fromUtf8("lwConfVPOut"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 384, 351, 271))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lbl1_7 = QtGui.QLabel(self.groupBox_2)
        self.lbl1_7.setGeometry(QtCore.QRect(10, 23, 135, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_7.setFont(font)
        self.lbl1_7.setLineWidth(-5)
        self.lbl1_7.setObjectName(_fromUtf8("lbl1_7"))
        self.leVPName = QtGui.QLineEdit(self.groupBox_2)
        self.leVPName.setGeometry(QtCore.QRect(160, 20, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leVPName.setFont(font)
        self.leVPName.setObjectName(_fromUtf8("leVPName"))
        self.tbChangeVPNameInConfig = QtGui.QToolButton(self.groupBox_2)
        self.tbChangeVPNameInConfig.setGeometry(QtCore.QRect(260, 50, 69, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbChangeVPNameInConfig.setFont(font)
        self.tbChangeVPNameInConfig.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbChangeVPNameInConfig.setArrowType(QtCore.Qt.NoArrow)
        self.tbChangeVPNameInConfig.setObjectName(_fromUtf8("tbChangeVPNameInConfig"))
        self.lbl1_9 = QtGui.QLabel(self.groupBox_2)
        self.lbl1_9.setGeometry(QtCore.QRect(10, 61, 110, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_9.setFont(font)
        self.lbl1_9.setLineWidth(-5)
        self.lbl1_9.setObjectName(_fromUtf8("lbl1_9"))
        self.lwConfVPIn = QtGui.QListWidget(self.groupBox_2)
        self.lwConfVPIn.setGeometry(QtCore.QRect(10, 81, 331, 91))
        self.lwConfVPIn.setObjectName(_fromUtf8("lwConfVPIn"))
        self.lblch_2 = QtGui.QLabel(self.groupBox_2)
        self.lblch_2.setGeometry(QtCore.QRect(10, 180, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblch_2.setFont(font)
        self.lblch_2.setLineWidth(-5)
        self.lblch_2.setObjectName(_fromUtf8("lblch_2"))
        self.lblch_3 = QtGui.QLabel(self.groupBox_2)
        self.lblch_3.setGeometry(QtCore.QRect(126, 180, 42, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblch_3.setFont(font)
        self.lblch_3.setLineWidth(-5)
        self.lblch_3.setObjectName(_fromUtf8("lblch_3"))
        self.tbChangeInConfig = QtGui.QToolButton(self.groupBox_2)
        self.tbChangeInConfig.setGeometry(QtCore.QRect(10, 200, 85, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbChangeInConfig.setFont(font)
        self.tbChangeInConfig.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbChangeInConfig.setArrowType(QtCore.Qt.NoArrow)
        self.tbChangeInConfig.setObjectName(_fromUtf8("tbChangeInConfig"))
        self.cb_In_2 = QtGui.QComboBox(self.groupBox_2)
        self.cb_In_2.setGeometry(QtCore.QRect(126, 200, 101, 20))
        self.cb_In_2.setEditable(False)
        self.cb_In_2.setObjectName(_fromUtf8("cb_In_2"))
        self.lblch_4 = QtGui.QLabel(self.groupBox_2)
        self.lblch_4.setGeometry(QtCore.QRect(126, 226, 33, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblch_4.setFont(font)
        self.lblch_4.setLineWidth(-5)
        self.lblch_4.setObjectName(_fromUtf8("lblch_4"))
        self.tbChangeInConfig_Off = QtGui.QToolButton(self.groupBox_2)
        self.tbChangeInConfig_Off.setGeometry(QtCore.QRect(10, 246, 78, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbChangeInConfig_Off.setFont(font)
        self.tbChangeInConfig_Off.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbChangeInConfig_Off.setArrowType(QtCore.Qt.NoArrow)
        self.tbChangeInConfig_Off.setObjectName(_fromUtf8("tbChangeInConfig_Off"))
        self.cb_Ch_2 = QtGui.QComboBox(self.groupBox_2)
        self.cb_Ch_2.setGeometry(QtCore.QRect(126, 246, 101, 20))
        self.cb_Ch_2.setEditable(False)
        self.cb_Ch_2.setObjectName(_fromUtf8("cb_Ch_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(412, 2, 205, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lwConf = QtGui.QListWidget(self.centralwidget)
        self.lwConf.setGeometry(QtCore.QRect(387, 33, 351, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwConf.sizePolicy().hasHeightForWidth())
        self.lwConf.setSizePolicy(sizePolicy)
        self.lwConf.setObjectName(_fromUtf8("lwConf"))
        self.tbAddToConfig = QtGui.QToolButton(self.centralwidget)
        self.tbAddToConfig.setGeometry(QtCore.QRect(413, 238, 166, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbAddToConfig.sizePolicy().hasHeightForWidth())
        self.tbAddToConfig.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbAddToConfig.setFont(font)
        self.tbAddToConfig.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbAddToConfig.setArrowType(QtCore.Qt.NoArrow)
        self.tbAddToConfig.setObjectName(_fromUtf8("tbAddToConfig"))
        self.tbDelFromConfig = QtGui.QToolButton(self.centralwidget)
        self.tbDelFromConfig.setGeometry(QtCore.QRect(631, 238, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDelFromConfig.setFont(font)
        self.tbDelFromConfig.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbDelFromConfig.setArrowType(QtCore.Qt.NoArrow)
        self.tbDelFromConfig.setObjectName(_fromUtf8("tbDelFromConfig"))
        self.lbl1_10 = QtGui.QLabel(self.centralwidget)
        self.lbl1_10.setGeometry(QtCore.QRect(412, 267, 118, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl1_10.setFont(font)
        self.lbl1_10.setLineWidth(-5)
        self.lbl1_10.setObjectName(_fromUtf8("lbl1_10"))
        fmCreateConfig.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fmCreateConfig)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        fmCreateConfig.setMenuBar(self.menubar)

        self.retranslateUi(fmCreateConfig)
        self.cb_In_2.setCurrentIndex(-1)
        self.cb_Ch_2.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(fmCreateConfig)

    def retranslateUi(self, fmCreateConfig):
        fmCreateConfig.setWindowTitle(_translate("fmCreateConfig", "Изменение конфигурации", None))
        self.groupBox_4.setTitle(_translate("fmCreateConfig", "Информация о виртуальном приборе", None))
        self.lbl1_13.setText(_translate("fmCreateConfig", "Назначение выходов", None))
        self.lbl1_12.setText(_translate("fmCreateConfig", "Назначение входов", None))
        self.label.setText(_translate("fmCreateConfig", "Список виртуальных приборов", None))
        self.tbChangeVPList.setText(_translate("fmCreateConfig", "Изменить", None))
        self.groupBox_3.setTitle(_translate("fmCreateConfig", "Конфигурация", None))
        self.tbTest_.setText(_translate("fmCreateConfig", "Тест", None))
        self.leConfName.setText(_translate("fmCreateConfig", "0", None))
        self.tbSaveConfig.setText(_translate("fmCreateConfig", "Ввод", None))
        self.lbl1_8.setText(_translate("fmCreateConfig", "Наименование конфигурации", None))
        self.lbl1_11.setText(_translate("fmCreateConfig", "Описание конфигурации", None))
        self.leConfDescr.setText(_translate("fmCreateConfig", "0", None))
        self.tbConfDescr.setText(_translate("fmCreateConfig", "Ввод", None))
        self.groupBox_2.setTitle(_translate("fmCreateConfig", "Добавление или изменение", None))
        self.lbl1_7.setText(_translate("fmCreateConfig", "Наименование прибора", None))
        self.leVPName.setText(_translate("fmCreateConfig", "0", None))
        self.tbChangeVPNameInConfig.setText(_translate("fmCreateConfig", "Изменить", None))
        self.lbl1_9.setText(_translate("fmCreateConfig", "Назначение входов", None))
        self.lblch_2.setText(_translate("fmCreateConfig", "Подключить к", None))
        self.lblch_3.setText(_translate("fmCreateConfig", "Модуль", None))
        self.tbChangeInConfig.setText(_translate("fmCreateConfig", "Подключить", None))
        self.lblch_4.setText(_translate("fmCreateConfig", "Канал", None))
        self.tbChangeInConfig_Off.setText(_translate("fmCreateConfig", "Отключить", None))
        self.label_2.setText(_translate("fmCreateConfig", "Приборы данной конфигурации", None))
        self.tbAddToConfig.setText(_translate("fmCreateConfig", "Добавить в конфигурацию", None))
        self.tbDelFromConfig.setText(_translate("fmCreateConfig", "Удалить", None))
        self.lbl1_10.setText(_translate("fmCreateConfig", "Назначение выходов", None))

