# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi_meteo_19_11_2015\svi_vs_v.0.6.4\forms\fmKeyboard.ui'
#
# Created: Fri Feb 12 16:12:21 2016
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmKeyboard(object):
    def setupUi(self, fmKeyboard):
        fmKeyboard.setObjectName(_fromUtf8("fmKeyboard"))
        fmKeyboard.resize(563, 125)
        fmKeyboard.setMinimumSize(QtCore.QSize(563, 125))
        fmKeyboard.setMaximumSize(QtCore.QSize(563, 125))
        self.centralwidget = QtGui.QWidget(fmKeyboard)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tb_1 = QtGui.QToolButton(self.centralwidget)
        self.tb_1.setGeometry(QtCore.QRect(468, 1, 31, 31))
        self.tb_1.setObjectName(_fromUtf8("tb_1"))
        self.tb_2 = QtGui.QToolButton(self.centralwidget)
        self.tb_2.setGeometry(QtCore.QRect(498, 1, 31, 31))
        self.tb_2.setObjectName(_fromUtf8("tb_2"))
        self.tb_3 = QtGui.QToolButton(self.centralwidget)
        self.tb_3.setGeometry(QtCore.QRect(528, 1, 31, 31))
        self.tb_3.setObjectName(_fromUtf8("tb_3"))
        self.tb_6 = QtGui.QToolButton(self.centralwidget)
        self.tb_6.setGeometry(QtCore.QRect(528, 31, 31, 31))
        self.tb_6.setObjectName(_fromUtf8("tb_6"))
        self.tb_5 = QtGui.QToolButton(self.centralwidget)
        self.tb_5.setGeometry(QtCore.QRect(498, 31, 31, 31))
        self.tb_5.setObjectName(_fromUtf8("tb_5"))
        self.tb_4 = QtGui.QToolButton(self.centralwidget)
        self.tb_4.setGeometry(QtCore.QRect(468, 31, 31, 31))
        self.tb_4.setObjectName(_fromUtf8("tb_4"))
        self.tb_0 = QtGui.QToolButton(self.centralwidget)
        self.tb_0.setGeometry(QtCore.QRect(468, 91, 31, 31))
        self.tb_0.setObjectName(_fromUtf8("tb_0"))
        self.tb_b = QtGui.QToolButton(self.centralwidget)
        self.tb_b.setGeometry(QtCore.QRect(498, 91, 31, 31))
        self.tb_b.setObjectName(_fromUtf8("tb_b"))
        self.tb_ = QtGui.QToolButton(self.centralwidget)
        self.tb_.setGeometry(QtCore.QRect(528, 91, 31, 31))
        self.tb_.setText(_fromUtf8(""))
        self.tb_.setObjectName(_fromUtf8("tb_"))
        self.tb_9 = QtGui.QToolButton(self.centralwidget)
        self.tb_9.setGeometry(QtCore.QRect(528, 61, 31, 31))
        self.tb_9.setObjectName(_fromUtf8("tb_9"))
        self.tb_8 = QtGui.QToolButton(self.centralwidget)
        self.tb_8.setGeometry(QtCore.QRect(498, 61, 31, 31))
        self.tb_8.setObjectName(_fromUtf8("tb_8"))
        self.tb_7 = QtGui.QToolButton(self.centralwidget)
        self.tb_7.setGeometry(QtCore.QRect(468, 61, 31, 31))
        self.tb_7.setObjectName(_fromUtf8("tb_7"))
        self.tb_e = QtGui.QToolButton(self.centralwidget)
        self.tb_e.setGeometry(QtCore.QRect(93, 30, 31, 31))
        self.tb_e.setObjectName(_fromUtf8("tb_e"))
        self.tb_w = QtGui.QToolButton(self.centralwidget)
        self.tb_w.setGeometry(QtCore.QRect(63, 30, 31, 31))
        self.tb_w.setObjectName(_fromUtf8("tb_w"))
        self.tb_q = QtGui.QToolButton(self.centralwidget)
        self.tb_q.setGeometry(QtCore.QRect(33, 30, 31, 31))
        self.tb_q.setObjectName(_fromUtf8("tb_q"))
        self.tb_r = QtGui.QToolButton(self.centralwidget)
        self.tb_r.setGeometry(QtCore.QRect(123, 30, 31, 31))
        self.tb_r.setObjectName(_fromUtf8("tb_r"))
        self.tb_t = QtGui.QToolButton(self.centralwidget)
        self.tb_t.setGeometry(QtCore.QRect(153, 30, 31, 31))
        self.tb_t.setObjectName(_fromUtf8("tb_t"))
        self.tb_y = QtGui.QToolButton(self.centralwidget)
        self.tb_y.setGeometry(QtCore.QRect(183, 30, 31, 31))
        self.tb_y.setObjectName(_fromUtf8("tb_y"))
        self.tb_sq2 = QtGui.QToolButton(self.centralwidget)
        self.tb_sq2.setGeometry(QtCore.QRect(363, 30, 31, 31))
        self.tb_sq2.setObjectName(_fromUtf8("tb_sq2"))
        self.tb_i = QtGui.QToolButton(self.centralwidget)
        self.tb_i.setGeometry(QtCore.QRect(243, 30, 31, 31))
        self.tb_i.setObjectName(_fromUtf8("tb_i"))
        self.tb_u = QtGui.QToolButton(self.centralwidget)
        self.tb_u.setGeometry(QtCore.QRect(213, 30, 31, 31))
        self.tb_u.setObjectName(_fromUtf8("tb_u"))
        self.tb_p = QtGui.QToolButton(self.centralwidget)
        self.tb_p.setGeometry(QtCore.QRect(303, 30, 31, 31))
        self.tb_p.setObjectName(_fromUtf8("tb_p"))
        self.tb_o = QtGui.QToolButton(self.centralwidget)
        self.tb_o.setGeometry(QtCore.QRect(273, 30, 31, 31))
        self.tb_o.setObjectName(_fromUtf8("tb_o"))
        self.tb_sq1 = QtGui.QToolButton(self.centralwidget)
        self.tb_sq1.setGeometry(QtCore.QRect(333, 30, 31, 31))
        self.tb_sq1.setObjectName(_fromUtf8("tb_sq1"))
        self.tb_ap = QtGui.QToolButton(self.centralwidget)
        self.tb_ap.setGeometry(QtCore.QRect(343, 60, 31, 31))
        self.tb_ap.setObjectName(_fromUtf8("tb_ap"))
        self.tb_s = QtGui.QToolButton(self.centralwidget)
        self.tb_s.setGeometry(QtCore.QRect(73, 60, 31, 31))
        self.tb_s.setObjectName(_fromUtf8("tb_s"))
        self.tb_j = QtGui.QToolButton(self.centralwidget)
        self.tb_j.setGeometry(QtCore.QRect(223, 60, 31, 31))
        self.tb_j.setObjectName(_fromUtf8("tb_j"))
        self.tb_a = QtGui.QToolButton(self.centralwidget)
        self.tb_a.setGeometry(QtCore.QRect(43, 60, 31, 31))
        self.tb_a.setObjectName(_fromUtf8("tb_a"))
        self.tb_l = QtGui.QToolButton(self.centralwidget)
        self.tb_l.setGeometry(QtCore.QRect(283, 60, 31, 31))
        self.tb_l.setObjectName(_fromUtf8("tb_l"))
        self.tb_tz = QtGui.QToolButton(self.centralwidget)
        self.tb_tz.setGeometry(QtCore.QRect(313, 60, 31, 31))
        self.tb_tz.setObjectName(_fromUtf8("tb_tz"))
        self.tb_f = QtGui.QToolButton(self.centralwidget)
        self.tb_f.setGeometry(QtCore.QRect(133, 60, 31, 31))
        self.tb_f.setObjectName(_fromUtf8("tb_f"))
        self.tb_h = QtGui.QToolButton(self.centralwidget)
        self.tb_h.setGeometry(QtCore.QRect(193, 60, 31, 31))
        self.tb_h.setObjectName(_fromUtf8("tb_h"))
        self.tb_k = QtGui.QToolButton(self.centralwidget)
        self.tb_k.setGeometry(QtCore.QRect(253, 60, 31, 31))
        self.tb_k.setObjectName(_fromUtf8("tb_k"))
        self.tb_d = QtGui.QToolButton(self.centralwidget)
        self.tb_d.setGeometry(QtCore.QRect(103, 60, 31, 31))
        self.tb_d.setObjectName(_fromUtf8("tb_d"))
        self.tb_g = QtGui.QToolButton(self.centralwidget)
        self.tb_g.setGeometry(QtCore.QRect(163, 60, 31, 31))
        self.tb_g.setObjectName(_fromUtf8("tb_g"))
        self.tb_b_2 = QtGui.QToolButton(self.centralwidget)
        self.tb_b_2.setGeometry(QtCore.QRect(173, 90, 31, 31))
        self.tb_b_2.setObjectName(_fromUtf8("tb_b_2"))
        self.tb_m = QtGui.QToolButton(self.centralwidget)
        self.tb_m.setGeometry(QtCore.QRect(233, 90, 31, 31))
        self.tb_m.setObjectName(_fromUtf8("tb_m"))
        self.tb_x = QtGui.QToolButton(self.centralwidget)
        self.tb_x.setGeometry(QtCore.QRect(83, 90, 31, 31))
        self.tb_x.setObjectName(_fromUtf8("tb_x"))
        self.tb_v = QtGui.QToolButton(self.centralwidget)
        self.tb_v.setGeometry(QtCore.QRect(143, 90, 31, 31))
        self.tb_v.setObjectName(_fromUtf8("tb_v"))
        self.tb_z = QtGui.QToolButton(self.centralwidget)
        self.tb_z.setGeometry(QtCore.QRect(53, 90, 31, 31))
        self.tb_z.setObjectName(_fromUtf8("tb_z"))
        self.tb_c = QtGui.QToolButton(self.centralwidget)
        self.tb_c.setGeometry(QtCore.QRect(113, 90, 31, 31))
        self.tb_c.setObjectName(_fromUtf8("tb_c"))
        self.tb_n = QtGui.QToolButton(self.centralwidget)
        self.tb_n.setGeometry(QtCore.QRect(203, 90, 31, 31))
        self.tb_n.setObjectName(_fromUtf8("tb_n"))
        self.tb_t1 = QtGui.QToolButton(self.centralwidget)
        self.tb_t1.setGeometry(QtCore.QRect(293, 90, 31, 31))
        self.tb_t1.setObjectName(_fromUtf8("tb_t1"))
        self.tb_z1 = QtGui.QToolButton(self.centralwidget)
        self.tb_z1.setGeometry(QtCore.QRect(263, 90, 31, 31))
        self.tb_z1.setObjectName(_fromUtf8("tb_z1"))
        self.tb_d1 = QtGui.QToolButton(self.centralwidget)
        self.tb_d1.setGeometry(QtCore.QRect(323, 90, 31, 31))
        self.tb_d1.setObjectName(_fromUtf8("tb_d1"))
        self.tb_Ru_En = QtGui.QToolButton(self.centralwidget)
        self.tb_Ru_En.setGeometry(QtCore.QRect(410, 90, 51, 31))
        self.tb_Ru_En.setObjectName(_fromUtf8("tb_Ru_En"))
        self.tb_Caps = QtGui.QToolButton(self.centralwidget)
        self.tb_Caps.setGeometry(QtCore.QRect(2, 60, 41, 31))
        self.tb_Caps.setObjectName(_fromUtf8("tb_Caps"))
        self.tb_Shift = QtGui.QToolButton(self.centralwidget)
        self.tb_Shift.setGeometry(QtCore.QRect(1, 90, 51, 31))
        self.tb_Shift.setObjectName(_fromUtf8("tb_Shift"))
        self.leText = QtGui.QLineEdit(self.centralwidget)
        self.leText.setGeometry(QtCore.QRect(1, 2, 461, 20))
        self.leText.setObjectName(_fromUtf8("leText"))
        self.tb_Space = QtGui.QToolButton(self.centralwidget)
        self.tb_Space.setGeometry(QtCore.QRect(356, 90, 51, 31))
        self.tb_Space.setText(_fromUtf8(""))
        self.tb_Space.setObjectName(_fromUtf8("tb_Space"))
        self.tb_Del = QtGui.QToolButton(self.centralwidget)
        self.tb_Del.setGeometry(QtCore.QRect(410, 60, 51, 31))
        self.tb_Del.setObjectName(_fromUtf8("tb_Del"))
        self.tb_tilda = QtGui.QToolButton(self.centralwidget)
        self.tb_tilda.setGeometry(QtCore.QRect(3, 30, 31, 31))
        self.tb_tilda.setObjectName(_fromUtf8("tb_tilda"))
        self.tb_minus = QtGui.QToolButton(self.centralwidget)
        self.tb_minus.setGeometry(QtCore.QRect(375, 60, 31, 31))
        self.tb_minus.setObjectName(_fromUtf8("tb_minus"))
        self.tb_eq = QtGui.QToolButton(self.centralwidget)
        self.tb_eq.setGeometry(QtCore.QRect(397, 30, 31, 31))
        self.tb_eq.setObjectName(_fromUtf8("tb_eq"))
        self.tb_d2 = QtGui.QToolButton(self.centralwidget)
        self.tb_d2.setGeometry(QtCore.QRect(430, 30, 31, 31))
        self.tb_d2.setObjectName(_fromUtf8("tb_d2"))
        fmKeyboard.setCentralWidget(self.centralwidget)
        self.actConf = QtGui.QAction(fmKeyboard)
        self.actConf.setObjectName(_fromUtf8("actConf"))

        self.retranslateUi(fmKeyboard)
        QtCore.QMetaObject.connectSlotsByName(fmKeyboard)

    def retranslateUi(self, fmKeyboard):
        fmKeyboard.setWindowTitle(_translate("fmKeyboard", "Клавиатура", None))
        self.tb_1.setText(_translate("fmKeyboard", "1", None))
        self.tb_2.setText(_translate("fmKeyboard", "2", None))
        self.tb_3.setText(_translate("fmKeyboard", "3", None))
        self.tb_6.setText(_translate("fmKeyboard", "6", None))
        self.tb_5.setText(_translate("fmKeyboard", "5", None))
        self.tb_4.setText(_translate("fmKeyboard", "4", None))
        self.tb_0.setText(_translate("fmKeyboard", "0", None))
        self.tb_b.setText(_translate("fmKeyboard", ".", None))
        self.tb_9.setText(_translate("fmKeyboard", "9", None))
        self.tb_8.setText(_translate("fmKeyboard", "8", None))
        self.tb_7.setText(_translate("fmKeyboard", "7", None))
        self.tb_e.setText(_translate("fmKeyboard", "e", None))
        self.tb_w.setText(_translate("fmKeyboard", "w", None))
        self.tb_q.setText(_translate("fmKeyboard", "q", None))
        self.tb_r.setText(_translate("fmKeyboard", "r", None))
        self.tb_t.setText(_translate("fmKeyboard", "t", None))
        self.tb_y.setText(_translate("fmKeyboard", "y", None))
        self.tb_sq2.setText(_translate("fmKeyboard", "]", None))
        self.tb_i.setText(_translate("fmKeyboard", "i", None))
        self.tb_u.setText(_translate("fmKeyboard", "u", None))
        self.tb_p.setText(_translate("fmKeyboard", "p", None))
        self.tb_o.setText(_translate("fmKeyboard", "o", None))
        self.tb_sq1.setText(_translate("fmKeyboard", "[", None))
        self.tb_ap.setText(_translate("fmKeyboard", "\'", None))
        self.tb_s.setText(_translate("fmKeyboard", "s", None))
        self.tb_j.setText(_translate("fmKeyboard", "j", None))
        self.tb_a.setText(_translate("fmKeyboard", "a", None))
        self.tb_l.setText(_translate("fmKeyboard", "l", None))
        self.tb_tz.setText(_translate("fmKeyboard", ";", None))
        self.tb_f.setText(_translate("fmKeyboard", "f", None))
        self.tb_h.setText(_translate("fmKeyboard", "h", None))
        self.tb_k.setText(_translate("fmKeyboard", "k", None))
        self.tb_d.setText(_translate("fmKeyboard", "d", None))
        self.tb_g.setText(_translate("fmKeyboard", "g", None))
        self.tb_b_2.setText(_translate("fmKeyboard", "b", None))
        self.tb_m.setText(_translate("fmKeyboard", "m", None))
        self.tb_x.setText(_translate("fmKeyboard", "x", None))
        self.tb_v.setText(_translate("fmKeyboard", "v", None))
        self.tb_z.setText(_translate("fmKeyboard", "z", None))
        self.tb_c.setText(_translate("fmKeyboard", "c", None))
        self.tb_n.setText(_translate("fmKeyboard", "n", None))
        self.tb_t1.setText(_translate("fmKeyboard", ".", None))
        self.tb_z1.setText(_translate("fmKeyboard", ",", None))
        self.tb_d1.setText(_translate("fmKeyboard", "/", None))
        self.tb_Ru_En.setText(_translate("fmKeyboard", "Ru/En", None))
        self.tb_Caps.setText(_translate("fmKeyboard", "Caps", None))
        self.tb_Shift.setText(_translate("fmKeyboard", "Shift", None))
        self.tb_Del.setText(_translate("fmKeyboard", "Del", None))
        self.tb_tilda.setText(_translate("fmKeyboard", "~", None))
        self.tb_minus.setText(_translate("fmKeyboard", "-", None))
        self.tb_eq.setText(_translate("fmKeyboard", "+", None))
        self.tb_d2.setText(_translate("fmKeyboard", ":", None))
        self.actConf.setText(_translate("fmKeyboard", "Настройки", None))

