# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi_vs_v.0.4\forms\fmO_2Calib.ui'
#
# Created: Thu Jan 15 10:25:18 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmO_2Calib(object):
    def setupUi(self, fmO_2Calib):
        fmO_2Calib.setObjectName(_fromUtf8("fmO_2Calib"))
        fmO_2Calib.resize(481, 441)
        self.centralwidget = QtGui.QWidget(fmO_2Calib)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.cbSensor = QtGui.QComboBox(self.centralwidget)
        self.cbSensor.setGeometry(QtCore.QRect(20, 195, 311, 22))
        self.cbSensor.setObjectName(_fromUtf8("cbSensor"))
        self.cbSensor.addItem(_fromUtf8(""))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(340, 48, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setLineWidth(-5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(213, 138, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setLineWidth(-5)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.leA_1 = QtGui.QLineEdit(self.centralwidget)
        self.leA_1.setGeometry(QtCore.QRect(53, 7, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA_1.setFont(font)
        self.leA_1.setObjectName(_fromUtf8("leA_1"))
        self.tbCalib = QtGui.QToolButton(self.centralwidget)
        self.tbCalib.setGeometry(QtCore.QRect(20, 230, 311, 22))
        self.tbCalib.setObjectName(_fromUtf8("tbCalib"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(213, 8, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setLineWidth(-5)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.leP_grad = QtGui.QLineEdit(self.centralwidget)
        self.leP_grad.setGeometry(QtCore.QRect(256, 97, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leP_grad.setFont(font)
        self.leP_grad.setObjectName(_fromUtf8("leP_grad"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(340, 138, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setLineWidth(-5)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(213, 48, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setLineWidth(-5)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(216, 98, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setLineWidth(-5)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(340, 8, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setLineWidth(-5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.leI_2 = QtGui.QLineEdit(self.centralwidget)
        self.leI_2.setGeometry(QtCore.QRect(253, 47, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leI_2.setFont(font)
        self.leI_2.setObjectName(_fromUtf8("leI_2"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(13, 98, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setLineWidth(-5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(13, 138, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setLineWidth(-5)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(143, 48, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setLineWidth(-5)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.leT_grad = QtGui.QLineEdit(self.centralwidget)
        self.leT_grad.setGeometry(QtCore.QRect(53, 97, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leT_grad.setFont(font)
        self.leT_grad.setObjectName(_fromUtf8("leT_grad"))
        self.leI_1 = QtGui.QLineEdit(self.centralwidget)
        self.leI_1.setGeometry(QtCore.QRect(253, 7, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leI_1.setFont(font)
        self.leI_1.setObjectName(_fromUtf8("leI_1"))
        self.leS = QtGui.QLineEdit(self.centralwidget)
        self.leS.setGeometry(QtCore.QRect(253, 137, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leS.setFont(font)
        self.leS.setObjectName(_fromUtf8("leS"))
        self.label_32 = QtGui.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(20, 170, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setLineWidth(-5)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(343, 98, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setLineWidth(-5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(13, 8, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setLineWidth(-5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(143, 138, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setLineWidth(-5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.leA_2 = QtGui.QLineEdit(self.centralwidget)
        self.leA_2.setGeometry(QtCore.QRect(53, 47, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA_2.setFont(font)
        self.leA_2.setObjectName(_fromUtf8("leA_2"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(13, 48, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setLineWidth(-5)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(143, 8, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setLineWidth(-5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.leA_0 = QtGui.QLineEdit(self.centralwidget)
        self.leA_0.setGeometry(QtCore.QRect(53, 137, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA_0.setFont(font)
        self.leA_0.setObjectName(_fromUtf8("leA_0"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 300, 461, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_37 = QtGui.QLabel(self.groupBox)
        self.label_37.setGeometry(QtCore.QRect(10, 60, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_37.setFont(font)
        self.label_37.setLineWidth(-5)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.leProfilName_ = QtGui.QLineEdit(self.groupBox)
        self.leProfilName_.setGeometry(QtCore.QRect(140, 20, 301, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leProfilName_.setFont(font)
        self.leProfilName_.setObjectName(_fromUtf8("leProfilName_"))
        self.label_40 = QtGui.QLabel(self.groupBox)
        self.label_40.setGeometry(QtCore.QRect(10, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_40.setFont(font)
        self.label_40.setLineWidth(-5)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.leDescr_ = QtGui.QLineEdit(self.groupBox)
        self.leDescr_.setGeometry(QtCore.QRect(140, 61, 301, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leDescr_.setFont(font)
        self.leDescr_.setObjectName(_fromUtf8("leDescr_"))
        self.tbSaveProfilO2 = QtGui.QToolButton(self.centralwidget)
        self.tbSaveProfilO2.setGeometry(QtCore.QRect(20, 267, 341, 22))
        self.tbSaveProfilO2.setObjectName(_fromUtf8("tbSaveProfilO2"))
        fmO_2Calib.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fmO_2Calib)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 481, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        fmO_2Calib.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fmO_2Calib)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fmO_2Calib.setStatusBar(self.statusbar)
        self.actTIns = QtGui.QAction(fmO_2Calib)
        self.actTIns.setObjectName(_fromUtf8("actTIns"))
        self.actTDel = QtGui.QAction(fmO_2Calib)
        self.actTDel.setObjectName(_fromUtf8("actTDel"))
        self.actPrIns = QtGui.QAction(fmO_2Calib)
        self.actPrIns.setObjectName(_fromUtf8("actPrIns"))
        self.actPrDel = QtGui.QAction(fmO_2Calib)
        self.actPrDel.setObjectName(_fromUtf8("actPrDel"))
        self.actPrRen = QtGui.QAction(fmO_2Calib)
        self.actPrRen.setObjectName(_fromUtf8("actPrRen"))

        self.retranslateUi(fmO_2Calib)
        self.cbSensor.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(fmO_2Calib)

    def retranslateUi(self, fmO_2Calib):
        fmO_2Calib.setWindowTitle(_translate("fmO_2Calib", "Градуировка", None))
        self.cbSensor.setItemText(0, _translate("fmO_2Calib", "ACpO2-00", None))
        self.label_20.setText(_translate("fmO_2Calib", "[нА]", None))
        self.label_27.setText(_translate("fmO_2Calib", "S<sub></sub>=", None))
        self.tbCalib.setText(_translate("fmO_2Calib", "Расчитать калибровочные коэффициенты", None))
        self.label_14.setText(_translate("fmO_2Calib", "I<sub>1</sub>=", None))
        self.label_24.setText(_translate("fmO_2Calib", "[ ]", None))
        self.label_22.setText(_translate("fmO_2Calib", "I<sub>2</sub>=", None))
        self.label_16.setText(_translate("fmO_2Calib", "P<sub>град</sub>=", None))
        self.label_15.setText(_translate("fmO_2Calib", "[нА]", None))
        self.label_18.setText(_translate("fmO_2Calib", "Т<sub>град</sub>=", None))
        self.label_25.setText(_translate("fmO_2Calib", "A<sub>0</sub>=", None))
        self.label_21.setText(_translate("fmO_2Calib", "[мг/дм3]", None))
        self.label_32.setText(_translate("fmO_2Calib", "Тип датчика", None))
        self.label_17.setText(_translate("fmO_2Calib", "[кПа]", None))
        self.label_13.setText(_translate("fmO_2Calib", "A<sub>1</sub>=", None))
        self.label_26.setText(_translate("fmO_2Calib", "[мг/дм3]", None))
        self.label_23.setText(_translate("fmO_2Calib", "A<sub>2</sub>=", None))
        self.label_19.setText(_translate("fmO_2Calib", "[мг/дм3]", None))
        self.groupBox.setTitle(_translate("fmO_2Calib", "Изменение наименования профиля", None))
        self.label_37.setText(_translate("fmO_2Calib", " Описание профиля", None))
        self.label_40.setText(_translate("fmO_2Calib", "Профиль измерения", None))
        self.tbSaveProfilO2.setText(_translate("fmO_2Calib", "Сохранить профиль", None))
        self.actTIns.setText(_translate("fmO_2Calib", "Вставить строку", None))
        self.actTDel.setText(_translate("fmO_2Calib", "Удалить строку", None))
        self.actPrIns.setText(_translate("fmO_2Calib", "Новый профиль", None))
        self.actPrDel.setText(_translate("fmO_2Calib", "Удалить профиль", None))
        self.actPrRen.setText(_translate("fmO_2Calib", "Переименовать профиль", None))

