# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi_vs_v.0.3\forms\fmO_2Calib.ui'
#
# Created: Fri Feb 21 09:34:06 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmO_2Calib(object):
    def setupUi(self, fmO_2Calib):
        fmO_2Calib.setObjectName(_fromUtf8("fmO_2Calib"))
        fmO_2Calib.resize(403, 563)
        self.centralwidget = QtGui.QWidget(fmO_2Calib)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.cbSensor = QtGui.QComboBox(self.centralwidget)
        self.cbSensor.setGeometry(QtCore.QRect(10, 478, 311, 22))
        self.cbSensor.setObjectName(_fromUtf8("cbSensor"))
        self.cbSensor.addItem(_fromUtf8(""))
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(13, 158, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setLineWidth(-5)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(340, 48, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setLineWidth(-5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(213, 228, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setLineWidth(-5)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.leA_1 = QtGui.QLineEdit(self.centralwidget)
        self.leA_1.setGeometry(QtCore.QRect(53, 7, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA_1.setFont(font)
        self.leA_1.setObjectName(_fromUtf8("leA_1"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 400, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setLineWidth(-5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.tbCalib = QtGui.QToolButton(self.centralwidget)
        self.tbCalib.setGeometry(QtCore.QRect(13, 268, 341, 22))
        self.tbCalib.setObjectName(_fromUtf8("tbCalib"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(213, 8, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setLineWidth(-5)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.leP_grad = QtGui.QLineEdit(self.centralwidget)
        self.leP_grad.setGeometry(QtCore.QRect(256, 97, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leP_grad.setFont(font)
        self.leP_grad.setObjectName(_fromUtf8("leP_grad"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(340, 228, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setLineWidth(-5)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(213, 48, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setLineWidth(-5)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(216, 98, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setLineWidth(-5)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.cbSreda = QtGui.QComboBox(self.centralwidget)
        self.cbSreda.setGeometry(QtCore.QRect(10, 375, 311, 22))
        self.cbSreda.setObjectName(_fromUtf8("cbSreda"))
        self.cbSreda.addItem(_fromUtf8(""))
        self.cbEd = QtGui.QComboBox(self.centralwidget)
        self.cbEd.setGeometry(QtCore.QRect(143, 158, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cbEd.setFont(font)
        self.cbEd.setObjectName(_fromUtf8("cbEd"))
        self.cbEd.addItem(_fromUtf8(""))
        self.tbElecAdd = QtGui.QToolButton(self.centralwidget)
        self.tbElecAdd.setGeometry(QtCore.QRect(330, 318, 27, 22))
        self.tbElecAdd.setObjectName(_fromUtf8("tbElecAdd"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(340, 8, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setLineWidth(-5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.leI_2 = QtGui.QLineEdit(self.centralwidget)
        self.leI_2.setGeometry(QtCore.QRect(253, 47, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leI_2.setFont(font)
        self.leI_2.setObjectName(_fromUtf8("leI_2"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(13, 98, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setLineWidth(-5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.leA = QtGui.QLineEdit(self.centralwidget)
        self.leA.setGeometry(QtCore.QRect(53, 158, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA.setFont(font)
        self.leA.setObjectName(_fromUtf8("leA"))
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(13, 228, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setLineWidth(-5)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(143, 48, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setLineWidth(-5)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.leT_grad = QtGui.QLineEdit(self.centralwidget)
        self.leT_grad.setGeometry(QtCore.QRect(53, 97, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leT_grad.setFont(font)
        self.leT_grad.setObjectName(_fromUtf8("leT_grad"))
        self.leI_1 = QtGui.QLineEdit(self.centralwidget)
        self.leI_1.setGeometry(QtCore.QRect(253, 7, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leI_1.setFont(font)
        self.leI_1.setObjectName(_fromUtf8("leI_1"))
        self.cbElec = QtGui.QComboBox(self.centralwidget)
        self.cbElec.setGeometry(QtCore.QRect(10, 318, 311, 22))
        self.cbElec.setObjectName(_fromUtf8("cbElec"))
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(343, 159, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setLineWidth(-5)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.cbTypeMess = QtGui.QComboBox(self.centralwidget)
        self.cbTypeMess.setGeometry(QtCore.QRect(10, 425, 311, 22))
        self.cbTypeMess.setObjectName(_fromUtf8("cbTypeMess"))
        self.cbTypeMess.addItem(_fromUtf8(""))
        self.leS = QtGui.QLineEdit(self.centralwidget)
        self.leS.setGeometry(QtCore.QRect(253, 227, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leS.setFont(font)
        self.leS.setObjectName(_fromUtf8("leS"))
        self.label_32 = QtGui.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(10, 453, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setLineWidth(-5)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(343, 98, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setLineWidth(-5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(13, 8, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setLineWidth(-5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tbEd = QtGui.QToolButton(self.centralwidget)
        self.tbEd.setGeometry(QtCore.QRect(13, 193, 341, 22))
        self.tbEd.setObjectName(_fromUtf8("tbEd"))
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(143, 228, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setLineWidth(-5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.leA_2 = QtGui.QLineEdit(self.centralwidget)
        self.leA_2.setGeometry(QtCore.QRect(53, 47, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA_2.setFont(font)
        self.leA_2.setObjectName(_fromUtf8("leA_2"))
        self.leElec = QtGui.QLineEdit(self.centralwidget)
        self.leElec.setEnabled(False)
        self.leElec.setGeometry(QtCore.QRect(10, 318, 311, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leElec.setFont(font)
        self.leElec.setObjectName(_fromUtf8("leElec"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(13, 48, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setLineWidth(-5)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.leA_mgdm3 = QtGui.QLineEdit(self.centralwidget)
        self.leA_mgdm3.setGeometry(QtCore.QRect(253, 158, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA_mgdm3.setFont(font)
        self.leA_mgdm3.setObjectName(_fromUtf8("leA_mgdm3"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(143, 8, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setLineWidth(-5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.leA_0 = QtGui.QLineEdit(self.centralwidget)
        self.leA_0.setGeometry(QtCore.QRect(53, 227, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leA_0.setFont(font)
        self.leA_0.setObjectName(_fromUtf8("leA_0"))
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(10, 350, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setLineWidth(-5)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(10, 290, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setLineWidth(-5)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        fmO_2Calib.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fmO_2Calib)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 403, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.muProf = QtGui.QMenu(self.menubar)
        self.muProf.setObjectName(_fromUtf8("muProf"))
        self.muTabl = QtGui.QMenu(self.menubar)
        self.muTabl.setObjectName(_fromUtf8("muTabl"))
        fmO_2Calib.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fmO_2Calib)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fmO_2Calib.setStatusBar(self.statusbar)
        self.actTIns = QtGui.QAction(fmO_2Calib)
        self.actTIns.setObjectName(_fromUtf8("actTIns"))
        self.actTDel = QtGui.QAction(fmO_2Calib)
        self.actTDel.setObjectName(_fromUtf8("actTDel"))
        self.actPrIns = QtGui.QAction(fmO_2Calib)
        self.actPrIns.setObjectName(_fromUtf8("actPrIns"))
        self.actPrDel = QtGui.QAction(fmO_2Calib)
        self.actPrDel.setObjectName(_fromUtf8("actPrDel"))
        self.actPrRen = QtGui.QAction(fmO_2Calib)
        self.actPrRen.setObjectName(_fromUtf8("actPrRen"))
        self.menubar.addAction(self.muProf.menuAction())
        self.menubar.addAction(self.muTabl.menuAction())

        self.retranslateUi(fmO_2Calib)
        self.cbSensor.setCurrentIndex(0)
        self.cbSreda.setCurrentIndex(0)
        self.cbEd.setCurrentIndex(0)
        self.cbTypeMess.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(fmO_2Calib)

    def retranslateUi(self, fmO_2Calib):
        fmO_2Calib.setWindowTitle(_translate("fmO_2Calib", "Градуировка", None))
        self.cbSensor.setItemText(0, _translate("fmO_2Calib", "ACpO2-00", None))
        self.label_28.setText(_translate("fmO_2Calib", "A=", None))
        self.label_20.setText(_translate("fmO_2Calib", "[нА]", None))
        self.label_27.setText(_translate("fmO_2Calib", "S<sub></sub>=", None))
        self.label_3.setText(_translate("fmO_2Calib", "Тип измерения", None))
        self.tbCalib.setText(_translate("fmO_2Calib", "Расчитать калибровочные коэффициенты", None))
        self.label_14.setText(_translate("fmO_2Calib", "I<sub>1</sub>=", None))
        self.label_24.setText(_translate("fmO_2Calib", "[ ]", None))
        self.label_22.setText(_translate("fmO_2Calib", "I<sub>2</sub>=", None))
        self.label_16.setText(_translate("fmO_2Calib", "P<sub>град</sub>=", None))
        self.cbSreda.setItemText(0, _translate("fmO_2Calib", "Жидкость", None))
        self.cbEd.setItemText(0, _translate("fmO_2Calib", "мг/дм3", None))
        self.tbElecAdd.setText(_translate("fmO_2Calib", "+", None))
        self.label_15.setText(_translate("fmO_2Calib", "[нА]", None))
        self.label_18.setText(_translate("fmO_2Calib", "Т<sub>град</sub>=", None))
        self.label_25.setText(_translate("fmO_2Calib", "A<sub>0</sub>=", None))
        self.label_21.setText(_translate("fmO_2Calib", "[мг/дм3]", None))
        self.label_29.setText(_translate("fmO_2Calib", "[мг/дм3]", None))
        self.cbTypeMess.setItemText(0, _translate("fmO_2Calib", "Кислородомер", None))
        self.label_32.setText(_translate("fmO_2Calib", "Тип датчика", None))
        self.label_17.setText(_translate("fmO_2Calib", "[кПа]", None))
        self.label_13.setText(_translate("fmO_2Calib", "A<sub>1</sub>=", None))
        self.tbEd.setText(_translate("fmO_2Calib", "БПК. Пересчитать в мг/дм3", None))
        self.label_26.setText(_translate("fmO_2Calib", "[мг/дм3]", None))
        self.label_23.setText(_translate("fmO_2Calib", "A<sub>2</sub>=", None))
        self.label_19.setText(_translate("fmO_2Calib", "[мг/дм3]", None))
        self.label_30.setText(_translate("fmO_2Calib", "Среда измерения", None))
        self.label_31.setText(_translate("fmO_2Calib", "Профиль измерения", None))
        self.muProf.setTitle(_translate("fmO_2Calib", "Профиль", None))
        self.muTabl.setTitle(_translate("fmO_2Calib", "Таблица", None))
        self.actTIns.setText(_translate("fmO_2Calib", "Вставить строку", None))
        self.actTDel.setText(_translate("fmO_2Calib", "Удалить строку", None))
        self.actPrIns.setText(_translate("fmO_2Calib", "Новый профиль", None))
        self.actPrDel.setText(_translate("fmO_2Calib", "Удалить профиль", None))
        self.actPrRen.setText(_translate("fmO_2Calib", "Переименовать профиль", None))

