# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi_vs_v.0.3\forms\fmPortCons.ui'
#
# Created: Mon Jan 13 11:22:09 2014
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_fmPortCons(object):
    def setupUi(self, fmPortCons):
        fmPortCons.setObjectName(_fromUtf8("fmPortCons"))
        fmPortCons.resize(626, 439)
        self.centralwidget = QtGui.QWidget(fmPortCons)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.teLog = QtGui.QTextEdit(self.centralwidget)
        self.teLog.setGeometry(QtCore.QRect(10, 10, 601, 301))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teLog.sizePolicy().hasHeightForWidth())
        self.teLog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.teLog.setFont(font)
        self.teLog.setAcceptDrops(False)
        self.teLog.setAutoFillBackground(False)
        self.teLog.setReadOnly(True)
        self.teLog.setObjectName(_fromUtf8("teLog"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 320, 601, 32))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.leHex = QtGui.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leHex.setFont(font)
        self.leHex.setText(_fromUtf8(""))
        self.leHex.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leHex.setObjectName(_fromUtf8("leHex"))
        self.horizontalLayout.addWidget(self.leHex)
        self.tbCRC = QtGui.QToolButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbCRC.setFont(font)
        self.tbCRC.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbCRC.setArrowType(QtCore.Qt.NoArrow)
        self.tbCRC.setObjectName(_fromUtf8("tbCRC"))
        self.horizontalLayout.addWidget(self.tbCRC)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 350, 601, 30))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.leASCII = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leASCII.setFont(font)
        self.leASCII.setText(_fromUtf8(""))
        self.leASCII.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leASCII.setObjectName(_fromUtf8("leASCII"))
        self.horizontalLayout_2.addWidget(self.leASCII)
        spacerItem = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        fmPortCons.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fmPortCons)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.qmPort = QtGui.QMenu(self.menubar)
        self.qmPort.setObjectName(_fromUtf8("qmPort"))
        fmPortCons.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fmPortCons)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fmPortCons.setStatusBar(self.statusbar)
        self.menubar.addAction(self.qmPort.menuAction())

        self.retranslateUi(fmPortCons)
        QtCore.QMetaObject.connectSlotsByName(fmPortCons)

    def retranslateUi(self, fmPortCons):
        fmPortCons.setWindowTitle(QtGui.QApplication.translate("fmPortCons", "Консоль отладки обмена", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("fmPortCons", "Tx(hex):    ", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCRC.setText(QtGui.QApplication.translate("fmPortCons", "+CRC16", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("fmPortCons", "Tx(ASCII):", None, QtGui.QApplication.UnicodeUTF8))
        self.qmPort.setTitle(QtGui.QApplication.translate("fmPortCons", "Порт", None, QtGui.QApplication.UnicodeUTF8))

