# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi_vs_v.0.4\forms\fmProgramming_1_1.ui'
#
# Created: Tue Nov 18 10:28:28 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmProgramming_1_1(object):
    def setupUi(self, fmProgramming_1_1):
        fmProgramming_1_1.setObjectName(_fromUtf8("fmProgramming_1_1"))
        fmProgramming_1_1.resize(718, 531)
        self.centralwidget = QtGui.QWidget(fmProgramming_1_1)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.cbTypeAnalog_ = QtGui.QComboBox(self.centralwidget)
        self.cbTypeAnalog_.setGeometry(QtCore.QRect(10, 100, 171, 22))
        self.cbTypeAnalog_.setEditable(False)
        self.cbTypeAnalog_.setObjectName(_fromUtf8("cbTypeAnalog_"))
        self.label_43 = QtGui.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(20, 260, 71, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_43.setFont(font)
        self.label_43.setLineWidth(-5)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.tbSaveEeprom_ = QtGui.QPushButton(self.centralwidget)
        self.tbSaveEeprom_.setGeometry(QtCore.QRect(10, 390, 171, 23))
        self.tbSaveEeprom_.setObjectName(_fromUtf8("tbSaveEeprom_"))
        self.tbAddDBNum_ = QtGui.QToolButton(self.centralwidget)
        self.tbAddDBNum_.setGeometry(QtCore.QRect(380, 390, 141, 22))
        self.tbAddDBNum_.setObjectName(_fromUtf8("tbAddDBNum_"))
        self.twDBNum_ = QtGui.QTableWidget(self.centralwidget)
        self.twDBNum_.setGeometry(QtCore.QRect(230, 40, 461, 331))
        self.twDBNum_.setObjectName(_fromUtf8("twDBNum_"))
        self.twDBNum_.setColumnCount(0)
        self.twDBNum_.setRowCount(0)
        self.tbSaveDBNum_ = QtGui.QToolButton(self.centralwidget)
        self.tbSaveDBNum_.setGeometry(QtCore.QRect(530, 390, 141, 22))
        self.tbSaveDBNum_.setObjectName(_fromUtf8("tbSaveDBNum_"))
        self.label_42 = QtGui.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(20, 140, 51, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_42.setFont(font)
        self.label_42.setLineWidth(-5)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(400, 10, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tbDelDBNum_ = QtGui.QToolButton(self.centralwidget)
        self.tbDelDBNum_.setGeometry(QtCore.QRect(230, 390, 141, 22))
        self.tbDelDBNum_.setObjectName(_fromUtf8("tbDelDBNum_"))
        self.leDate_ = QtGui.QLineEdit(self.centralwidget)
        self.leDate_.setGeometry(QtCore.QRect(10, 170, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leDate_.setFont(font)
        self.leDate_.setObjectName(_fromUtf8("leDate_"))
        self.label_41 = QtGui.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(10, 70, 171, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_41.setFont(font)
        self.label_41.setLineWidth(-5)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(10, 10, 121, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setLineWidth(-5)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.leVersion_ = QtGui.QLineEdit(self.centralwidget)
        self.leVersion_.setGeometry(QtCore.QRect(10, 290, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leVersion_.setFont(font)
        self.leVersion_.setObjectName(_fromUtf8("leVersion_"))
        self.cbSNum_ = QtGui.QSpinBox(self.centralwidget)
        self.cbSNum_.setGeometry(QtCore.QRect(10, 40, 171, 22))
        self.cbSNum_.setMaximum(1000000)
        self.cbSNum_.setObjectName(_fromUtf8("cbSNum_"))
        self.tbSaveDB_ = QtGui.QToolButton(self.centralwidget)
        self.tbSaveDB_.setGeometry(QtCore.QRect(380, 420, 141, 22))
        self.tbSaveDB_.setObjectName(_fromUtf8("tbSaveDB_"))
        self.label_44 = QtGui.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(20, 200, 111, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_44.setFont(font)
        self.label_44.setLineWidth(-5)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.leVersionHW_ = QtGui.QLineEdit(self.centralwidget)
        self.leVersionHW_.setGeometry(QtCore.QRect(10, 230, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leVersionHW_.setFont(font)
        self.leVersionHW_.setObjectName(_fromUtf8("leVersionHW_"))
        self.leComment_ = QtGui.QLineEdit(self.centralwidget)
        self.leComment_.setGeometry(QtCore.QRect(10, 350, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leComment_.setFont(font)
        self.leComment_.setObjectName(_fromUtf8("leComment_"))
        self.label_45 = QtGui.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(20, 320, 141, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_45.setFont(font)
        self.label_45.setLineWidth(-5)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.tbReadEeprom_ = QtGui.QPushButton(self.centralwidget)
        self.tbReadEeprom_.setGeometry(QtCore.QRect(10, 420, 171, 23))
        self.tbReadEeprom_.setObjectName(_fromUtf8("tbReadEeprom_"))
        self.tbSearchModuls = QtGui.QPushButton(self.centralwidget)
        self.tbSearchModuls.setGeometry(QtCore.QRect(10, 460, 171, 23))
        self.tbSearchModuls.setObjectName(_fromUtf8("tbSearchModuls"))
        fmProgramming_1_1.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fmProgramming_1_1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        fmProgramming_1_1.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fmProgramming_1_1)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fmProgramming_1_1.setStatusBar(self.statusbar)

        self.retranslateUi(fmProgramming_1_1)
        self.cbTypeAnalog_.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(fmProgramming_1_1)

    def retranslateUi(self, fmProgramming_1_1):
        fmProgramming_1_1.setWindowTitle(_translate("fmProgramming_1_1", "Изменение конфигурации", None))
        self.label_43.setText(_translate("fmProgramming_1_1", "Версия ПО", None))
        self.tbSaveEeprom_.setText(_translate("fmProgramming_1_1", "Запмсь в EEPROM", None))
        self.tbAddDBNum_.setText(_translate("fmProgramming_1_1", "Добавить запись", None))
        self.tbSaveDBNum_.setText(_translate("fmProgramming_1_1", "Изменить запись", None))
        self.label_42.setText(_translate("fmProgramming_1_1", "Дата", None))
        self.label_9.setText(_translate("fmProgramming_1_1", "База номеров приборов", None))
        self.tbDelDBNum_.setText(_translate("fmProgramming_1_1", "Удалить запись", None))
        self.leDate_.setText(_translate("fmProgramming_1_1", "0", None))
        self.label_41.setText(_translate("fmProgramming_1_1", "Тип аналогового устройства", None))
        self.label_31.setText(_translate("fmProgramming_1_1", "Заводской номер", None))
        self.leVersion_.setText(_translate("fmProgramming_1_1", "0", None))
        self.tbSaveDB_.setText(_translate("fmProgramming_1_1", "Сохранить БД", None))
        self.label_44.setText(_translate("fmProgramming_1_1", "Версия модуля", None))
        self.leVersionHW_.setText(_translate("fmProgramming_1_1", "0", None))
        self.leComment_.setText(_translate("fmProgramming_1_1", "0", None))
        self.label_45.setText(_translate("fmProgramming_1_1", "Комментарий", None))
        self.tbReadEeprom_.setText(_translate("fmProgramming_1_1", "Чтение из EEPROM", None))
        self.tbSearchModuls.setText(_translate("fmProgramming_1_1", "Поиск модулей", None))

