# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\__2018\NB2\svi\forms\fmSelectConfig.ui'
#
# Created: Thu Sep 20 13:41:02 2018
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmSelectConfig(object):
    def setupUi(self, fmSelectConfig):
        fmSelectConfig.setObjectName(_fromUtf8("fmSelectConfig"))
        fmSelectConfig.setWindowModality(QtCore.Qt.NonModal)
        fmSelectConfig.resize(960, 1012)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(fmSelectConfig.sizePolicy().hasHeightForWidth())
        fmSelectConfig.setSizePolicy(sizePolicy)
        fmSelectConfig.setMinimumSize(QtCore.QSize(960, 1012))
        fmSelectConfig.setMaximumSize(QtCore.QSize(960, 1012))
        self.centralwidget = QtGui.QWidget(fmSelectConfig)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tbUpConf = QtGui.QToolButton(self.centralwidget)
        self.tbUpConf.setGeometry(QtCore.QRect(10, 540, 61, 61))
        self.tbUpConf.setArrowType(QtCore.Qt.DownArrow)
        self.tbUpConf.setObjectName(_fromUtf8("tbUpConf"))
        self.tbDnConf = QtGui.QToolButton(self.centralwidget)
        self.tbDnConf.setGeometry(QtCore.QRect(10, 70, 61, 61))
        self.tbDnConf.setIconSize(QtCore.QSize(16, 16))
        self.tbDnConf.setAutoRepeatInterval(100)
        self.tbDnConf.setArrowType(QtCore.Qt.UpArrow)
        self.tbDnConf.setObjectName(_fromUtf8("tbDnConf"))
        self.tbSettings = QtGui.QToolButton(self.centralwidget)
        self.tbSettings.setGeometry(QtCore.QRect(500, 920, 200, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbSettings.sizePolicy().hasHeightForWidth())
        self.tbSettings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbSettings.setFont(font)
        self.tbSettings.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbSettings.setArrowType(QtCore.Qt.NoArrow)
        self.tbSettings.setObjectName(_fromUtf8("tbSettings"))
        self.tbLoadLastConfig = QtGui.QToolButton(self.centralwidget)
        self.tbLoadLastConfig.setGeometry(QtCore.QRect(740, 70, 200, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbLoadLastConfig.sizePolicy().hasHeightForWidth())
        self.tbLoadLastConfig.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbLoadLastConfig.setFont(font)
        self.tbLoadLastConfig.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbLoadLastConfig.setArrowType(QtCore.Qt.NoArrow)
        self.tbLoadLastConfig.setObjectName(_fromUtf8("tbLoadLastConfig"))
        self.tbCloseConfig = QtGui.QToolButton(self.centralwidget)
        self.tbCloseConfig.setGeometry(QtCore.QRect(740, 253, 200, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbCloseConfig.sizePolicy().hasHeightForWidth())
        self.tbCloseConfig.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbCloseConfig.setFont(font)
        self.tbCloseConfig.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbCloseConfig.setArrowType(QtCore.Qt.NoArrow)
        self.tbCloseConfig.setObjectName(_fromUtf8("tbCloseConfig"))
        self.tbSetting = QtGui.QToolButton(self.centralwidget)
        self.tbSetting.setGeometry(QtCore.QRect(730, 920, 200, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbSetting.sizePolicy().hasHeightForWidth())
        self.tbSetting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbSetting.setFont(font)
        self.tbSetting.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbSetting.setArrowType(QtCore.Qt.NoArrow)
        self.tbSetting.setObjectName(_fromUtf8("tbSetting"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.lwConf = QtGui.QListWidget(self.centralwidget)
        self.lwConf.setGeometry(QtCore.QRect(90, 70, 611, 531))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lwConf.setFont(font)
        self.lwConf.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.lwConf.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lwConf.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.lwConf.setObjectName(_fromUtf8("lwConf"))
        self.tbChangeConf = QtGui.QToolButton(self.centralwidget)
        self.tbChangeConf.setGeometry(QtCore.QRect(740, 630, 200, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbChangeConf.sizePolicy().hasHeightForWidth())
        self.tbChangeConf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbChangeConf.setFont(font)
        self.tbChangeConf.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbChangeConf.setArrowType(QtCore.Qt.NoArrow)
        self.tbChangeConf.setObjectName(_fromUtf8("tbChangeConf"))
        self.tbSelectConf = QtGui.QToolButton(self.centralwidget)
        self.tbSelectConf.setGeometry(QtCore.QRect(740, 163, 200, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbSelectConf.sizePolicy().hasHeightForWidth())
        self.tbSelectConf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbSelectConf.setFont(font)
        self.tbSelectConf.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbSelectConf.setArrowType(QtCore.Qt.NoArrow)
        self.tbSelectConf.setObjectName(_fromUtf8("tbSelectConf"))
        self.tbDelConf = QtGui.QToolButton(self.centralwidget)
        self.tbDelConf.setGeometry(QtCore.QRect(740, 530, 200, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbDelConf.sizePolicy().hasHeightForWidth())
        self.tbDelConf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbDelConf.setFont(font)
        self.tbDelConf.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbDelConf.setArrowType(QtCore.Qt.NoArrow)
        self.tbDelConf.setObjectName(_fromUtf8("tbDelConf"))
        self.tbCreateConf = QtGui.QToolButton(self.centralwidget)
        self.tbCreateConf.setGeometry(QtCore.QRect(740, 440, 200, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbCreateConf.sizePolicy().hasHeightForWidth())
        self.tbCreateConf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbCreateConf.setFont(font)
        self.tbCreateConf.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbCreateConf.setArrowType(QtCore.Qt.NoArrow)
        self.tbCreateConf.setObjectName(_fromUtf8("tbCreateConf"))
        self.tbTestModuls = QtGui.QToolButton(self.centralwidget)
        self.tbTestModuls.setGeometry(QtCore.QRect(740, 720, 200, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbTestModuls.sizePolicy().hasHeightForWidth())
        self.tbTestModuls.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbTestModuls.setFont(font)
        self.tbTestModuls.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.tbTestModuls.setArrowType(QtCore.Qt.NoArrow)
        self.tbTestModuls.setObjectName(_fromUtf8("tbTestModuls"))
        self.tbDescribe = QtGui.QTextBrowser(self.centralwidget)
        self.tbDescribe.setGeometry(QtCore.QRect(100, 690, 601, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tbDescribe.setFont(font)
        self.tbDescribe.setObjectName(_fromUtf8("tbDescribe"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 640, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        fmSelectConfig.setCentralWidget(self.centralwidget)

        self.retranslateUi(fmSelectConfig)
        QtCore.QMetaObject.connectSlotsByName(fmSelectConfig)

    def retranslateUi(self, fmSelectConfig):
        fmSelectConfig.setWindowTitle(_translate("fmSelectConfig", "Выбор конфигурации", None))
        self.tbUpConf.setText(_translate("fmSelectConfig", "...", None))
        self.tbDnConf.setText(_translate("fmSelectConfig", "...", None))
        self.tbSettings.setText(_translate("fmSelectConfig", "Параметры", None))
        self.tbLoadLastConfig.setText(_translate("fmSelectConfig", "Продолжить", None))
        self.tbCloseConfig.setText(_translate("fmSelectConfig", "Закрыть", None))
        self.tbSetting.setText(_translate("fmSelectConfig", "Настройка", None))
        self.label.setText(_translate("fmSelectConfig", "Конфигурации", None))
        self.tbChangeConf.setText(_translate("fmSelectConfig", "Изменить", None))
        self.tbSelectConf.setText(_translate("fmSelectConfig", "Выбрать", None))
        self.tbDelConf.setText(_translate("fmSelectConfig", "Удалить", None))
        self.tbCreateConf.setText(_translate("fmSelectConfig", "Создать", None))
        self.tbTestModuls.setText(_translate("fmSelectConfig", "Тест", None))
        self.label_2.setText(_translate("fmSelectConfig", "Описание", None))

