# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi (4)\svi\forms\fmTConf.ui'
#
# Created: Thu Sep 13 10:44:46 2018
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmTConf(object):
    def setupUi(self, fmTConf):
        fmTConf.setObjectName(_fromUtf8("fmTConf"))
        fmTConf.resize(1052, 633)
        fmTConf.setMinimumSize(QtCore.QSize(1052, 633))
        fmTConf.setMaximumSize(QtCore.QSize(1052, 633))
        self.centralwidget = QtGui.QWidget(fmTConf)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.leAddrMB = QtGui.QLineEdit(self.centralwidget)
        self.leAddrMB.setGeometry(QtCore.QRect(270, 10, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAddrMB.setFont(font)
        self.leAddrMB.setObjectName(_fromUtf8("leAddrMB"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.tbAddrMBWr = QtGui.QToolButton(self.centralwidget)
        self.tbAddrMBWr.setGeometry(QtCore.QRect(470, 10, 41, 41))
        self.tbAddrMBWr.setObjectName(_fromUtf8("tbAddrMBWr"))
        self.tbAddrMBRd = QtGui.QToolButton(self.centralwidget)
        self.tbAddrMBRd.setGeometry(QtCore.QRect(400, 10, 41, 41))
        self.tbAddrMBRd.setObjectName(_fromUtf8("tbAddrMBRd"))
        self.tbthrATRd = QtGui.QToolButton(self.centralwidget)
        self.tbthrATRd.setGeometry(QtCore.QRect(400, 60, 41, 41))
        self.tbthrATRd.setObjectName(_fromUtf8("tbthrATRd"))
        self.tbthrATWr = QtGui.QToolButton(self.centralwidget)
        self.tbthrATWr.setGeometry(QtCore.QRect(470, 60, 41, 41))
        self.tbthrATWr.setObjectName(_fromUtf8("tbthrATWr"))
        self.lethrAT = QtGui.QLineEdit(self.centralwidget)
        self.lethrAT.setGeometry(QtCore.QRect(270, 60, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lethrAT.setFont(font)
        self.lethrAT.setObjectName(_fromUtf8("lethrAT"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(10, 60, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.tbConfRd = QtGui.QToolButton(self.centralwidget)
        self.tbConfRd.setGeometry(QtCore.QRect(400, 260, 41, 41))
        self.tbConfRd.setObjectName(_fromUtf8("tbConfRd"))
        self.tbConfWr = QtGui.QToolButton(self.centralwidget)
        self.tbConfWr.setGeometry(QtCore.QRect(470, 260, 41, 41))
        self.tbConfWr.setObjectName(_fromUtf8("tbConfWr"))
        self.leConf = QtGui.QLineEdit(self.centralwidget)
        self.leConf.setGeometry(QtCore.QRect(270, 260, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leConf.setFont(font)
        self.leConf.setObjectName(_fromUtf8("leConf"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(10, 250, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(10, 370, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.leSerNum = QtGui.QLineEdit(self.centralwidget)
        self.leSerNum.setGeometry(QtCore.QRect(270, 370, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leSerNum.setFont(font)
        self.leSerNum.setObjectName(_fromUtf8("leSerNum"))
        self.tbSerNumWr = QtGui.QToolButton(self.centralwidget)
        self.tbSerNumWr.setGeometry(QtCore.QRect(470, 370, 41, 41))
        self.tbSerNumWr.setObjectName(_fromUtf8("tbSerNumWr"))
        self.tbSerNumRd = QtGui.QToolButton(self.centralwidget)
        self.tbSerNumRd.setGeometry(QtCore.QRect(400, 370, 41, 41))
        self.tbSerNumRd.setObjectName(_fromUtf8("tbSerNumRd"))
        self.tbModeRd = QtGui.QToolButton(self.centralwidget)
        self.tbModeRd.setGeometry(QtCore.QRect(400, 210, 41, 41))
        self.tbModeRd.setObjectName(_fromUtf8("tbModeRd"))
        self.tbModeWr = QtGui.QToolButton(self.centralwidget)
        self.tbModeWr.setGeometry(QtCore.QRect(470, 210, 41, 41))
        self.tbModeWr.setObjectName(_fromUtf8("tbModeWr"))
        self.leMode = QtGui.QLineEdit(self.centralwidget)
        self.leMode.setGeometry(QtCore.QRect(270, 210, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leMode.setFont(font)
        self.leMode.setObjectName(_fromUtf8("leMode"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(10, 200, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(10, 310, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.leIO = QtGui.QLineEdit(self.centralwidget)
        self.leIO.setGeometry(QtCore.QRect(270, 320, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leIO.setFont(font)
        self.leIO.setObjectName(_fromUtf8("leIO"))
        self.tbIOWr = QtGui.QToolButton(self.centralwidget)
        self.tbIOWr.setGeometry(QtCore.QRect(470, 310, 41, 41))
        self.tbIOWr.setObjectName(_fromUtf8("tbIOWr"))
        self.tbIORd = QtGui.QToolButton(self.centralwidget)
        self.tbIORd.setGeometry(QtCore.QRect(400, 310, 41, 41))
        self.tbIORd.setObjectName(_fromUtf8("tbIORd"))
        self.tbSave = QtGui.QToolButton(self.centralwidget)
        self.tbSave.setGeometry(QtCore.QRect(220, 510, 471, 41))
        self.tbSave.setObjectName(_fromUtf8("tbSave"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(110, 470, 731, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(660, 13, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(660, 283, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.tbTypeIDRd = QtGui.QToolButton(self.centralwidget)
        self.tbTypeIDRd.setGeometry(QtCore.QRect(930, 280, 41, 41))
        self.tbTypeIDRd.setObjectName(_fromUtf8("tbTypeIDRd"))
        self.teDescribe = QtGui.QTextEdit(self.centralwidget)
        self.teDescribe.setGeometry(QtCore.QRect(660, 53, 361, 161))
        self.teDescribe.setObjectName(_fromUtf8("teDescribe"))
        self.tbDescribeRd = QtGui.QToolButton(self.centralwidget)
        self.tbDescribeRd.setGeometry(QtCore.QRect(870, 223, 41, 41))
        self.tbDescribeRd.setObjectName(_fromUtf8("tbDescribeRd"))
        self.tbDescribeWr = QtGui.QToolButton(self.centralwidget)
        self.tbDescribeWr.setGeometry(QtCore.QRect(930, 223, 41, 41))
        self.tbDescribeWr.setObjectName(_fromUtf8("tbDescribeWr"))
        self.leTypeID = QtGui.QLineEdit(self.centralwidget)
        self.leTypeID.setGeometry(QtCore.QRect(812, 281, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leTypeID.setFont(font)
        self.leTypeID.setObjectName(_fromUtf8("leTypeID"))
        self.tbTypeIDWr = QtGui.QToolButton(self.centralwidget)
        self.tbTypeIDWr.setGeometry(QtCore.QRect(990, 280, 41, 41))
        self.tbTypeIDWr.setObjectName(_fromUtf8("tbTypeIDWr"))
        self.leCR0 = QtGui.QLineEdit(self.centralwidget)
        self.leCR0.setGeometry(QtCore.QRect(270, 110, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leCR0.setFont(font)
        self.leCR0.setObjectName(_fromUtf8("leCR0"))
        self.tbKaRd = QtGui.QToolButton(self.centralwidget)
        self.tbKaRd.setGeometry(QtCore.QRect(400, 160, 41, 41))
        self.tbKaRd.setObjectName(_fromUtf8("tbKaRd"))
        self.tbCR0Wr = QtGui.QToolButton(self.centralwidget)
        self.tbCR0Wr.setGeometry(QtCore.QRect(470, 110, 41, 41))
        self.tbCR0Wr.setObjectName(_fromUtf8("tbCR0Wr"))
        self.tbCR0RdVar = QtGui.QToolButton(self.centralwidget)
        self.tbCR0RdVar.setGeometry(QtCore.QRect(530, 110, 81, 41))
        self.tbCR0RdVar.setObjectName(_fromUtf8("tbCR0RdVar"))
        self.tbKaWr = QtGui.QToolButton(self.centralwidget)
        self.tbKaWr.setGeometry(QtCore.QRect(470, 160, 41, 41))
        self.tbKaWr.setObjectName(_fromUtf8("tbKaWr"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setLineWidth(-5)
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.leKa = QtGui.QLineEdit(self.centralwidget)
        self.leKa.setGeometry(QtCore.QRect(270, 160, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leKa.setFont(font)
        self.leKa.setObjectName(_fromUtf8("leKa"))
        self.tbCR0Rd = QtGui.QToolButton(self.centralwidget)
        self.tbCR0Rd.setGeometry(QtCore.QRect(400, 110, 41, 41))
        self.tbCR0Rd.setObjectName(_fromUtf8("tbCR0Rd"))
        fmTConf.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fmTConf)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1052, 38))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        fmTConf.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fmTConf)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fmTConf.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(fmTConf)
        QtCore.QMetaObject.connectSlotsByName(fmTConf)

    def retranslateUi(self, fmTConf):
        fmTConf.setWindowTitle(_translate("fmTConf", "Настройки милливольтметра ", None))
        self.label_16.setText(_translate("fmTConf", "Адрес MODBUS:", None))
        self.tbAddrMBWr.setText(_translate("fmTConf", "Wr", None))
        self.tbAddrMBRd.setText(_translate("fmTConf", "Rd", None))
        self.tbthrATRd.setText(_translate("fmTConf", "Rd", None))
        self.tbthrATWr.setText(_translate("fmTConf", "Wr", None))
        self.label_17.setText(_translate("fmTConf", "Пауза во фрейме:", None))
        self.tbConfRd.setText(_translate("fmTConf", "Rd", None))
        self.tbConfWr.setText(_translate("fmTConf", "Wr", None))
        self.label_18.setText(_translate("fmTConf", "ADC conf <b>(hex)</b>:", None))
        self.label_19.setText(_translate("fmTConf", "Серийный номер:", None))
        self.tbSerNumWr.setText(_translate("fmTConf", "Wr", None))
        self.tbSerNumRd.setText(_translate("fmTConf", "Rd", None))
        self.tbModeRd.setText(_translate("fmTConf", "Rd", None))
        self.tbModeWr.setText(_translate("fmTConf", "Wr", None))
        self.label_20.setText(_translate("fmTConf", "ADC mode <b>(hex)</b>:", None))
        self.label_21.setText(_translate("fmTConf", "ADC IO <b>(hex)</b>:", None))
        self.tbIOWr.setText(_translate("fmTConf", "Wr", None))
        self.tbIORd.setText(_translate("fmTConf", "Rd", None))
        self.tbSave.setText(_translate("fmTConf", "Сохранить в энергонезависимой памяти", None))
        self.label_33.setText(_translate("fmTConf", "Описание", None))
        self.label_34.setText(_translate("fmTConf", "Тип модуля", None))
        self.tbTypeIDRd.setText(_translate("fmTConf", "Rd", None))
        self.tbDescribeRd.setText(_translate("fmTConf", "Rd", None))
        self.tbDescribeWr.setText(_translate("fmTConf", "Wr", None))
        self.tbTypeIDWr.setText(_translate("fmTConf", "Wr", None))
        self.tbKaRd.setText(_translate("fmTConf", "Rd", None))
        self.tbCR0Wr.setText(_translate("fmTConf", "Wr", None))
        self.tbCR0RdVar.setText(_translate("fmTConf", "RdVar", None))
        self.tbKaWr.setText(_translate("fmTConf", "Wr", None))
        self.label_12.setText(_translate("fmTConf", "1024/ &#945;", None))
        self.label_2.setText(_translate("fmTConf", "Код АЦП при 0<sup>o</sup>С", None))
        self.tbCR0Rd.setText(_translate("fmTConf", "Rd", None))
        self.menu.setTitle(_translate("fmTConf", "?", None))

