# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi (4)\svi\forms\fmTPConf.ui'
#
# Created: Thu Sep 13 10:45:05 2018
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fmTPConf(object):
    def setupUi(self, fmTPConf):
        fmTPConf.setObjectName(_fromUtf8("fmTPConf"))
        fmTPConf.resize(1036, 848)
        fmTPConf.setMinimumSize(QtCore.QSize(1036, 848))
        fmTPConf.setMaximumSize(QtCore.QSize(1036, 848))
        self.centralwidget = QtGui.QWidget(fmTPConf)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(20, 500, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setLineWidth(-5)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 450, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setLineWidth(-5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.tbApWr = QtGui.QToolButton(self.centralwidget)
        self.tbApWr.setGeometry(QtCore.QRect(480, 500, 41, 41))
        self.tbApWr.setObjectName(_fromUtf8("tbApWr"))
        self.tbP0Rd = QtGui.QToolButton(self.centralwidget)
        self.tbP0Rd.setGeometry(QtCore.QRect(410, 450, 41, 41))
        self.tbP0Rd.setObjectName(_fromUtf8("tbP0Rd"))
        self.leP0 = QtGui.QLineEdit(self.centralwidget)
        self.leP0.setGeometry(QtCore.QRect(280, 450, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leP0.setFont(font)
        self.leP0.setObjectName(_fromUtf8("leP0"))
        self.tbApRd = QtGui.QToolButton(self.centralwidget)
        self.tbApRd.setGeometry(QtCore.QRect(410, 500, 41, 41))
        self.tbApRd.setObjectName(_fromUtf8("tbApRd"))
        self.tbP0Wr = QtGui.QToolButton(self.centralwidget)
        self.tbP0Wr.setGeometry(QtCore.QRect(480, 450, 41, 41))
        self.tbP0Wr.setObjectName(_fromUtf8("tbP0Wr"))
        self.leAp = QtGui.QLineEdit(self.centralwidget)
        self.leAp.setGeometry(QtCore.QRect(280, 500, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAp.setFont(font)
        self.leAp.setObjectName(_fromUtf8("leAp"))
        self.tbPConfWr = QtGui.QToolButton(self.centralwidget)
        self.tbPConfWr.setGeometry(QtCore.QRect(480, 600, 41, 41))
        self.tbPConfWr.setObjectName(_fromUtf8("tbPConfWr"))
        self.tbPModeWr = QtGui.QToolButton(self.centralwidget)
        self.tbPModeWr.setGeometry(QtCore.QRect(480, 550, 41, 41))
        self.tbPModeWr.setObjectName(_fromUtf8("tbPModeWr"))
        self.tbPIOWr = QtGui.QToolButton(self.centralwidget)
        self.tbPIOWr.setGeometry(QtCore.QRect(480, 650, 41, 41))
        self.tbPIOWr.setObjectName(_fromUtf8("tbPIOWr"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(20, 640, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.tbPConfRd = QtGui.QToolButton(self.centralwidget)
        self.tbPConfRd.setGeometry(QtCore.QRect(410, 600, 41, 41))
        self.tbPConfRd.setObjectName(_fromUtf8("tbPConfRd"))
        self.tbPModeRd = QtGui.QToolButton(self.centralwidget)
        self.tbPModeRd.setGeometry(QtCore.QRect(410, 550, 41, 41))
        self.tbPModeRd.setObjectName(_fromUtf8("tbPModeRd"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(20, 590, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.tbPIORd = QtGui.QToolButton(self.centralwidget)
        self.tbPIORd.setGeometry(QtCore.QRect(410, 650, 41, 41))
        self.tbPIORd.setObjectName(_fromUtf8("tbPIORd"))
        self.leIO_P = QtGui.QLineEdit(self.centralwidget)
        self.leIO_P.setGeometry(QtCore.QRect(279, 650, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leIO_P.setFont(font)
        self.leIO_P.setObjectName(_fromUtf8("leIO_P"))
        self.leMode_P = QtGui.QLineEdit(self.centralwidget)
        self.leMode_P.setGeometry(QtCore.QRect(279, 550, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leMode_P.setFont(font)
        self.leMode_P.setObjectName(_fromUtf8("leMode_P"))
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(20, 540, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.leConf_P = QtGui.QLineEdit(self.centralwidget)
        self.leConf_P.setGeometry(QtCore.QRect(280, 600, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leConf_P.setFont(font)
        self.leConf_P.setObjectName(_fromUtf8("leConf_P"))
        self.tbP0RdVar = QtGui.QToolButton(self.centralwidget)
        self.tbP0RdVar.setGeometry(QtCore.QRect(530, 450, 81, 41))
        self.tbP0RdVar.setObjectName(_fromUtf8("tbP0RdVar"))
        self.tbApRdVar = QtGui.QToolButton(self.centralwidget)
        self.tbApRdVar.setGeometry(QtCore.QRect(530, 500, 81, 41))
        self.tbApRdVar.setObjectName(_fromUtf8("tbApRdVar"))
        self.tbAddrMBWr = QtGui.QToolButton(self.centralwidget)
        self.tbAddrMBWr.setGeometry(QtCore.QRect(480, 20, 41, 41))
        self.tbAddrMBWr.setObjectName(_fromUtf8("tbAddrMBWr"))
        self.tbCR0RdVar = QtGui.QToolButton(self.centralwidget)
        self.tbCR0RdVar.setGeometry(QtCore.QRect(540, 120, 81, 41))
        self.tbCR0RdVar.setObjectName(_fromUtf8("tbCR0RdVar"))
        self.leKa = QtGui.QLineEdit(self.centralwidget)
        self.leKa.setGeometry(QtCore.QRect(280, 170, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leKa.setFont(font)
        self.leKa.setObjectName(_fromUtf8("leKa"))
        self.tbKaRd = QtGui.QToolButton(self.centralwidget)
        self.tbKaRd.setGeometry(QtCore.QRect(410, 170, 41, 41))
        self.tbKaRd.setObjectName(_fromUtf8("tbKaRd"))
        self.leAddrMB = QtGui.QLineEdit(self.centralwidget)
        self.leAddrMB.setGeometry(QtCore.QRect(280, 20, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leAddrMB.setFont(font)
        self.leAddrMB.setObjectName(_fromUtf8("leAddrMB"))
        self.tbIOWr = QtGui.QToolButton(self.centralwidget)
        self.tbIOWr.setGeometry(QtCore.QRect(480, 320, 41, 41))
        self.tbIOWr.setObjectName(_fromUtf8("tbIOWr"))
        self.leConf = QtGui.QLineEdit(self.centralwidget)
        self.leConf.setGeometry(QtCore.QRect(280, 270, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leConf.setFont(font)
        self.leConf.setObjectName(_fromUtf8("leConf"))
        self.tbIORd = QtGui.QToolButton(self.centralwidget)
        self.tbIORd.setGeometry(QtCore.QRect(410, 320, 41, 41))
        self.tbIORd.setObjectName(_fromUtf8("tbIORd"))
        self.leMode = QtGui.QLineEdit(self.centralwidget)
        self.leMode.setGeometry(QtCore.QRect(280, 220, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leMode.setFont(font)
        self.leMode.setObjectName(_fromUtf8("leMode"))
        self.tbTypeIDWr = QtGui.QToolButton(self.centralwidget)
        self.tbTypeIDWr.setGeometry(QtCore.QRect(980, 290, 41, 41))
        self.tbTypeIDWr.setObjectName(_fromUtf8("tbTypeIDWr"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(20, 210, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 160, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setLineWidth(-5)
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.leIO = QtGui.QLineEdit(self.centralwidget)
        self.leIO.setGeometry(QtCore.QRect(280, 330, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leIO.setFont(font)
        self.leIO.setObjectName(_fromUtf8("leIO"))
        self.leTypeID = QtGui.QLineEdit(self.centralwidget)
        self.leTypeID.setGeometry(QtCore.QRect(802, 291, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leTypeID.setFont(font)
        self.leTypeID.setObjectName(_fromUtf8("leTypeID"))
        self.tbthrATRd = QtGui.QToolButton(self.centralwidget)
        self.tbthrATRd.setGeometry(QtCore.QRect(410, 70, 41, 41))
        self.tbthrATRd.setObjectName(_fromUtf8("tbthrATRd"))
        self.tbAddrMBRd = QtGui.QToolButton(self.centralwidget)
        self.tbAddrMBRd.setGeometry(QtCore.QRect(410, 20, 41, 41))
        self.tbAddrMBRd.setObjectName(_fromUtf8("tbAddrMBRd"))
        self.tbKaWr = QtGui.QToolButton(self.centralwidget)
        self.tbKaWr.setGeometry(QtCore.QRect(480, 170, 41, 41))
        self.tbKaWr.setObjectName(_fromUtf8("tbKaWr"))
        self.tbConfRd = QtGui.QToolButton(self.centralwidget)
        self.tbConfRd.setGeometry(QtCore.QRect(410, 270, 41, 41))
        self.tbConfRd.setObjectName(_fromUtf8("tbConfRd"))
        self.teDescribe = QtGui.QTextEdit(self.centralwidget)
        self.teDescribe.setGeometry(QtCore.QRect(650, 63, 361, 161))
        self.teDescribe.setObjectName(_fromUtf8("teDescribe"))
        self.tbSerNumWr = QtGui.QToolButton(self.centralwidget)
        self.tbSerNumWr.setGeometry(QtCore.QRect(480, 380, 41, 41))
        self.tbSerNumWr.setObjectName(_fromUtf8("tbSerNumWr"))
        self.tbModeRd = QtGui.QToolButton(self.centralwidget)
        self.tbModeRd.setGeometry(QtCore.QRect(410, 220, 41, 41))
        self.tbModeRd.setObjectName(_fromUtf8("tbModeRd"))
        self.tbSave = QtGui.QToolButton(self.centralwidget)
        self.tbSave.setGeometry(QtCore.QRect(240, 720, 471, 41))
        self.tbSave.setObjectName(_fromUtf8("tbSave"))
        self.tbSerNumRd = QtGui.QToolButton(self.centralwidget)
        self.tbSerNumRd.setGeometry(QtCore.QRect(410, 380, 41, 41))
        self.tbSerNumRd.setObjectName(_fromUtf8("tbSerNumRd"))
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(650, 293, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(20, 320, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.tbTypeIDRd = QtGui.QToolButton(self.centralwidget)
        self.tbTypeIDRd.setGeometry(QtCore.QRect(920, 290, 41, 41))
        self.tbTypeIDRd.setObjectName(_fromUtf8("tbTypeIDRd"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 30, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.tbConfWr = QtGui.QToolButton(self.centralwidget)
        self.tbConfWr.setGeometry(QtCore.QRect(480, 270, 41, 41))
        self.tbConfWr.setObjectName(_fromUtf8("tbConfWr"))
        self.tbthrATWr = QtGui.QToolButton(self.centralwidget)
        self.tbthrATWr.setGeometry(QtCore.QRect(480, 70, 41, 41))
        self.tbthrATWr.setObjectName(_fromUtf8("tbthrATWr"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 690, 1001, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 70, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(650, 23, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.leSerNum = QtGui.QLineEdit(self.centralwidget)
        self.leSerNum.setGeometry(QtCore.QRect(280, 380, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leSerNum.setFont(font)
        self.leSerNum.setObjectName(_fromUtf8("leSerNum"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(20, 260, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.tbCR0Wr = QtGui.QToolButton(self.centralwidget)
        self.tbCR0Wr.setGeometry(QtCore.QRect(480, 120, 41, 41))
        self.tbCR0Wr.setObjectName(_fromUtf8("tbCR0Wr"))
        self.tbModeWr = QtGui.QToolButton(self.centralwidget)
        self.tbModeWr.setGeometry(QtCore.QRect(480, 220, 41, 41))
        self.tbModeWr.setObjectName(_fromUtf8("tbModeWr"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(20, 380, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.tbCR0Rd = QtGui.QToolButton(self.centralwidget)
        self.tbCR0Rd.setGeometry(QtCore.QRect(410, 120, 41, 41))
        self.tbCR0Rd.setObjectName(_fromUtf8("tbCR0Rd"))
        self.tbDescribeRd = QtGui.QToolButton(self.centralwidget)
        self.tbDescribeRd.setGeometry(QtCore.QRect(860, 233, 41, 41))
        self.tbDescribeRd.setObjectName(_fromUtf8("tbDescribeRd"))
        self.leCR0 = QtGui.QLineEdit(self.centralwidget)
        self.leCR0.setGeometry(QtCore.QRect(280, 120, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leCR0.setFont(font)
        self.leCR0.setObjectName(_fromUtf8("leCR0"))
        self.lethrAT = QtGui.QLineEdit(self.centralwidget)
        self.lethrAT.setGeometry(QtCore.QRect(280, 70, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lethrAT.setFont(font)
        self.lethrAT.setObjectName(_fromUtf8("lethrAT"))
        self.tbDescribeWr = QtGui.QToolButton(self.centralwidget)
        self.tbDescribeWr.setGeometry(QtCore.QRect(920, 233, 41, 41))
        self.tbDescribeWr.setObjectName(_fromUtf8("tbDescribeWr"))
        fmTPConf.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fmTPConf)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 38))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        fmTPConf.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fmTPConf)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fmTPConf.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(fmTPConf)
        QtCore.QMetaObject.connectSlotsByName(fmTPConf)

    def retranslateUi(self, fmTPConf):
        fmTPConf.setWindowTitle(_translate("fmTPConf", "Настройки термометра  и измерителя давления", None))
        self.label_22.setText(_translate("fmTPConf", "A<sub>p</sub>", None))
        self.label_15.setText(_translate("fmTPConf", "P<sub>0</sub>", None))
        self.tbApWr.setText(_translate("fmTPConf", "Wr", None))
        self.tbP0Rd.setText(_translate("fmTPConf", "Rd", None))
        self.tbApRd.setText(_translate("fmTPConf", "Rd", None))
        self.tbP0Wr.setText(_translate("fmTPConf", "Wr", None))
        self.tbPConfWr.setText(_translate("fmTPConf", "Wr", None))
        self.tbPModeWr.setText(_translate("fmTPConf", "Wr", None))
        self.tbPIOWr.setText(_translate("fmTPConf", "Wr", None))
        self.label_23.setText(_translate("fmTPConf", "ADC IO P <b>(hex)</b>:", None))
        self.tbPConfRd.setText(_translate("fmTPConf", "Rd", None))
        self.tbPModeRd.setText(_translate("fmTPConf", "Rd", None))
        self.label_24.setText(_translate("fmTPConf", "ADC conf P<b>(hex)</b>:", None))
        self.tbPIORd.setText(_translate("fmTPConf", "Rd", None))
        self.label_25.setText(_translate("fmTPConf", "ADC mode P <b>(hex)</b>:", None))
        self.tbP0RdVar.setText(_translate("fmTPConf", "RdVar", None))
        self.tbApRdVar.setText(_translate("fmTPConf", "RdVar", None))
        self.tbAddrMBWr.setText(_translate("fmTPConf", "Wr", None))
        self.tbCR0RdVar.setText(_translate("fmTPConf", "RdVar", None))
        self.tbKaRd.setText(_translate("fmTPConf", "Rd", None))
        self.tbIOWr.setText(_translate("fmTPConf", "Wr", None))
        self.tbIORd.setText(_translate("fmTPConf", "Rd", None))
        self.tbTypeIDWr.setText(_translate("fmTPConf", "Wr", None))
        self.label_20.setText(_translate("fmTPConf", "ADC mode <b>(hex)</b>:", None))
        self.label_12.setText(_translate("fmTPConf", "1024/ &#945;", None))
        self.tbthrATRd.setText(_translate("fmTPConf", "Rd", None))
        self.tbAddrMBRd.setText(_translate("fmTPConf", "Rd", None))
        self.tbKaWr.setText(_translate("fmTPConf", "Wr", None))
        self.tbConfRd.setText(_translate("fmTPConf", "Rd", None))
        self.tbSerNumWr.setText(_translate("fmTPConf", "Wr", None))
        self.tbModeRd.setText(_translate("fmTPConf", "Rd", None))
        self.tbSave.setText(_translate("fmTPConf", "Сохранить в энергонезависимой памяти", None))
        self.tbSerNumRd.setText(_translate("fmTPConf", "Rd", None))
        self.label_34.setText(_translate("fmTPConf", "Тип модуля", None))
        self.label_21.setText(_translate("fmTPConf", "ADC IO <b>(hex)</b>:", None))
        self.tbTypeIDRd.setText(_translate("fmTPConf", "Rd", None))
        self.label_16.setText(_translate("fmTPConf", "Адрес MODBUS:", None))
        self.tbConfWr.setText(_translate("fmTPConf", "Wr", None))
        self.tbthrATWr.setText(_translate("fmTPConf", "Wr", None))
        self.label_2.setText(_translate("fmTPConf", "Код АЦП при 0<sup>o</sup>С", None))
        self.label_17.setText(_translate("fmTPConf", "Пауза во фрейме:", None))
        self.label_33.setText(_translate("fmTPConf", "Описание", None))
        self.label_18.setText(_translate("fmTPConf", "ADC conf <b>(hex)</b>:", None))
        self.tbCR0Wr.setText(_translate("fmTPConf", "Wr", None))
        self.tbModeWr.setText(_translate("fmTPConf", "Wr", None))
        self.label_19.setText(_translate("fmTPConf", "Серийный номер:", None))
        self.tbCR0Rd.setText(_translate("fmTPConf", "Rd", None))
        self.tbDescribeRd.setText(_translate("fmTPConf", "Rd", None))
        self.tbDescribeWr.setText(_translate("fmTPConf", "Wr", None))
        self.menu.setTitle(_translate("fmTPConf", "?", None))

