# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\__2018\NB2\svi\forms\fpChart_II.ui'
#
# Created: Thu Sep 20 16:21:36 2018
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fpChart_II(object):
    def setupUi(self, fpChart_II):
        fpChart_II.setObjectName(_fromUtf8("fpChart_II"))
        fpChart_II.resize(1045, 1045)
        fpChart_II.setMinimumSize(QtCore.QSize(1045, 1045))
        fpChart_II.setMaximumSize(QtCore.QSize(1045, 1045))
        self.centralwidget = QtGui.QWidget(fpChart_II)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(630, 20, 298, 131))
        self.groupBox_2.setMinimumSize(QtCore.QSize(298, 121))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lblVal_6 = QtGui.QLabel(self.groupBox_2)
        self.lblVal_6.setGeometry(QtCore.QRect(197, 80, 81, 31))
        self.lblVal_6.setMinimumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblVal_6.setFont(font)
        self.lblVal_6.setLineWidth(-5)
        self.lblVal_6.setText(_fromUtf8(""))
        self.lblVal_6.setObjectName(_fromUtf8("lblVal_6"))
        self.lcdMain_percent_max = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdMain_percent_max.setGeometry(QtCore.QRect(10, 80, 181, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_percent_max.sizePolicy().hasHeightForWidth())
        self.lcdMain_percent_max.setSizePolicy(sizePolicy)
        self.lcdMain_percent_max.setMinimumSize(QtCore.QSize(181, 41))
        self.lcdMain_percent_max.setSmallDecimalPoint(True)
        self.lcdMain_percent_max.setDigitCount(8)
        self.lcdMain_percent_max.setProperty("value", 0.0)
        self.lcdMain_percent_max.setProperty("intValue", 0)
        self.lcdMain_percent_max.setObjectName(_fromUtf8("lcdMain_percent_max"))
        self.lblVal_3 = QtGui.QLabel(self.groupBox_2)
        self.lblVal_3.setGeometry(QtCore.QRect(197, 33, 91, 31))
        self.lblVal_3.setMinimumSize(QtCore.QSize(91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblVal_3.setFont(font)
        self.lblVal_3.setLineWidth(-5)
        self.lblVal_3.setText(_fromUtf8(""))
        self.lblVal_3.setObjectName(_fromUtf8("lblVal_3"))
        self.lcdMain_mg_max = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdMain_mg_max.setGeometry(QtCore.QRect(10, 33, 181, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_mg_max.sizePolicy().hasHeightForWidth())
        self.lcdMain_mg_max.setSizePolicy(sizePolicy)
        self.lcdMain_mg_max.setMinimumSize(QtCore.QSize(181, 41))
        self.lcdMain_mg_max.setSmallDecimalPoint(True)
        self.lcdMain_mg_max.setDigitCount(8)
        self.lcdMain_mg_max.setProperty("value", 0.0)
        self.lcdMain_mg_max.setProperty("intValue", 0)
        self.lcdMain_mg_max.setObjectName(_fromUtf8("lcdMain_mg_max"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(310, 670, 731, 301))
        self.groupBox_3.setMinimumSize(QtCore.QSize(731, 235))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.tbAddMarker = QtGui.QToolButton(self.groupBox_3)
        self.tbAddMarker.setGeometry(QtCore.QRect(300, 230, 141, 51))
        self.tbAddMarker.setMinimumSize(QtCore.QSize(121, 31))
        self.tbAddMarker.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbAddMarker.setObjectName(_fromUtf8("tbAddMarker"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(20, 156, 111, 21))
        self.label_12.setMinimumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setLineWidth(-5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.leVal_marker = QtGui.QLineEdit(self.groupBox_3)
        self.leVal_marker.setGeometry(QtCore.QRect(140, 146, 81, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leVal_marker.sizePolicy().hasHeightForWidth())
        self.leVal_marker.setSizePolicy(sizePolicy)
        self.leVal_marker.setMinimumSize(QtCore.QSize(81, 31))
        self.leVal_marker.setMaximumSize(QtCore.QSize(81, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.leVal_marker.setFont(font)
        self.leVal_marker.setFrame(True)
        self.leVal_marker.setReadOnly(False)
        self.leVal_marker.setObjectName(_fromUtf8("leVal_marker"))
        self.leComment_marker = QtGui.QLineEdit(self.groupBox_3)
        self.leComment_marker.setGeometry(QtCore.QRect(10, 250, 251, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leComment_marker.sizePolicy().hasHeightForWidth())
        self.leComment_marker.setSizePolicy(sizePolicy)
        self.leComment_marker.setMinimumSize(QtCore.QSize(81, 31))
        self.leComment_marker.setMaximumSize(QtCore.QSize(1811, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.leComment_marker.setFont(font)
        self.leComment_marker.setText(_fromUtf8(""))
        self.leComment_marker.setFrame(True)
        self.leComment_marker.setReadOnly(False)
        self.leComment_marker.setObjectName(_fromUtf8("leComment_marker"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(20, 210, 131, 21))
        self.label_13.setMinimumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setLineWidth(-5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.rbCon = QtGui.QRadioButton(self.groupBox_3)
        self.rbCon.setEnabled(True)
        self.rbCon.setGeometry(QtCore.QRect(10, 37, 271, 31))
        self.rbCon.setMinimumSize(QtCore.QSize(111, 17))
        self.rbCon.setText(_fromUtf8(""))
        self.rbCon.setCheckable(True)
        self.rbCon.setChecked(True)
        self.rbCon.setObjectName(_fromUtf8("rbCon"))
        self.rbTime = QtGui.QRadioButton(self.groupBox_3)
        self.rbTime.setGeometry(QtCore.QRect(10, 90, 181, 31))
        self.rbTime.setMinimumSize(QtCore.QSize(82, 17))
        self.rbTime.setObjectName(_fromUtf8("rbTime"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(260, 23, 211, 21))
        self.label_16.setMinimumSize(QtCore.QSize(111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setLineWidth(-5)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.tbDelMarker = QtGui.QToolButton(self.groupBox_3)
        self.tbDelMarker.setGeometry(QtCore.QRect(465, 230, 131, 51))
        self.tbDelMarker.setMinimumSize(QtCore.QSize(121, 31))
        self.tbDelMarker.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbDelMarker.setObjectName(_fromUtf8("tbDelMarker"))
        self.lwListMarker = QtGui.QListWidget(self.groupBox_3)
        self.lwListMarker.setGeometry(QtCore.QRect(260, 50, 431, 161))
        self.lwListMarker.setMinimumSize(QtCore.QSize(391, 141))
        self.lwListMarker.setObjectName(_fromUtf8("lwListMarker"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(19, 19, 298, 131))
        self.groupBox_5.setMinimumSize(QtCore.QSize(298, 121))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.lblVal_1 = QtGui.QLabel(self.groupBox_5)
        self.lblVal_1.setGeometry(QtCore.QRect(197, 33, 91, 31))
        self.lblVal_1.setMinimumSize(QtCore.QSize(91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblVal_1.setFont(font)
        self.lblVal_1.setLineWidth(-5)
        self.lblVal_1.setText(_fromUtf8(""))
        self.lblVal_1.setObjectName(_fromUtf8("lblVal_1"))
        self.lcdMain_percent = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdMain_percent.setGeometry(QtCore.QRect(10, 80, 181, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_percent.sizePolicy().hasHeightForWidth())
        self.lcdMain_percent.setSizePolicy(sizePolicy)
        self.lcdMain_percent.setMinimumSize(QtCore.QSize(181, 41))
        self.lcdMain_percent.setSmallDecimalPoint(True)
        self.lcdMain_percent.setDigitCount(8)
        self.lcdMain_percent.setProperty("value", 0.0)
        self.lcdMain_percent.setProperty("intValue", 0)
        self.lcdMain_percent.setObjectName(_fromUtf8("lcdMain_percent"))
        self.lblVal_4 = QtGui.QLabel(self.groupBox_5)
        self.lblVal_4.setGeometry(QtCore.QRect(197, 80, 81, 31))
        self.lblVal_4.setMinimumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblVal_4.setFont(font)
        self.lblVal_4.setLineWidth(-5)
        self.lblVal_4.setText(_fromUtf8(""))
        self.lblVal_4.setObjectName(_fromUtf8("lblVal_4"))
        self.lcdMain_mg = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdMain_mg.setGeometry(QtCore.QRect(10, 33, 181, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_mg.sizePolicy().hasHeightForWidth())
        self.lcdMain_mg.setSizePolicy(sizePolicy)
        self.lcdMain_mg.setMinimumSize(QtCore.QSize(181, 41))
        self.lcdMain_mg.setFrameShape(QtGui.QFrame.Box)
        self.lcdMain_mg.setLineWidth(0)
        self.lcdMain_mg.setMidLineWidth(1)
        self.lcdMain_mg.setSmallDecimalPoint(True)
        self.lcdMain_mg.setNumDigits(8)
        self.lcdMain_mg.setDigitCount(8)
        self.lcdMain_mg.setProperty("value", 0.0)
        self.lcdMain_mg.setProperty("intValue", 0)
        self.lcdMain_mg.setObjectName(_fromUtf8("lcdMain_mg"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(330, 20, 298, 131))
        self.groupBox.setMinimumSize(QtCore.QSize(298, 121))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lblVal_5 = QtGui.QLabel(self.groupBox)
        self.lblVal_5.setGeometry(QtCore.QRect(197, 80, 81, 31))
        self.lblVal_5.setMinimumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblVal_5.setFont(font)
        self.lblVal_5.setLineWidth(-5)
        self.lblVal_5.setText(_fromUtf8(""))
        self.lblVal_5.setObjectName(_fromUtf8("lblVal_5"))
        self.lcdMain_percent_min = QtGui.QLCDNumber(self.groupBox)
        self.lcdMain_percent_min.setGeometry(QtCore.QRect(10, 80, 181, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_percent_min.sizePolicy().hasHeightForWidth())
        self.lcdMain_percent_min.setSizePolicy(sizePolicy)
        self.lcdMain_percent_min.setMinimumSize(QtCore.QSize(181, 41))
        self.lcdMain_percent_min.setSmallDecimalPoint(True)
        self.lcdMain_percent_min.setDigitCount(8)
        self.lcdMain_percent_min.setProperty("value", 0.0)
        self.lcdMain_percent_min.setProperty("intValue", 0)
        self.lcdMain_percent_min.setObjectName(_fromUtf8("lcdMain_percent_min"))
        self.lblVal_2 = QtGui.QLabel(self.groupBox)
        self.lblVal_2.setGeometry(QtCore.QRect(197, 33, 91, 31))
        self.lblVal_2.setMinimumSize(QtCore.QSize(91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblVal_2.setFont(font)
        self.lblVal_2.setLineWidth(-5)
        self.lblVal_2.setText(_fromUtf8(""))
        self.lblVal_2.setObjectName(_fromUtf8("lblVal_2"))
        self.lcdMain_mg_min = QtGui.QLCDNumber(self.groupBox)
        self.lcdMain_mg_min.setGeometry(QtCore.QRect(10, 33, 181, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_mg_min.sizePolicy().hasHeightForWidth())
        self.lcdMain_mg_min.setSizePolicy(sizePolicy)
        self.lcdMain_mg_min.setMinimumSize(QtCore.QSize(181, 41))
        self.lcdMain_mg_min.setSmallDecimalPoint(True)
        self.lcdMain_mg_min.setDigitCount(8)
        self.lcdMain_mg_min.setProperty("value", 0.0)
        self.lcdMain_mg_min.setProperty("intValue", 0)
        self.lcdMain_mg_min.setObjectName(_fromUtf8("lcdMain_mg_min"))
        self.qwtPlot = Qwt5.QwtPlot(self.centralwidget)
        self.qwtPlot.setGeometry(QtCore.QRect(19, 110, 975, 571))
        self.qwtPlot.setMinimumSize(QtCore.QSize(912, 281))
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(19, 670, 276, 301))
        self.groupBox_4.setMinimumSize(QtCore.QSize(181, 221))
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.chbPause = QtGui.QCheckBox(self.groupBox_4)
        self.chbPause.setGeometry(QtCore.QRect(10, 100, 251, 31))
        self.chbPause.setMinimumSize(QtCore.QSize(131, 17))
        self.chbPause.setObjectName(_fromUtf8("chbPause"))
        self.tbResetViewPar = QtGui.QToolButton(self.groupBox_4)
        self.tbResetViewPar.setGeometry(QtCore.QRect(10, 200, 131, 51))
        self.tbResetViewPar.setMinimumSize(QtCore.QSize(121, 31))
        self.tbResetViewPar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbResetViewPar.setObjectName(_fromUtf8("tbResetViewPar"))
        self.chbZoom = QtGui.QCheckBox(self.groupBox_4)
        self.chbZoom.setGeometry(QtCore.QRect(10, 40, 181, 31))
        self.chbZoom.setMinimumSize(QtCore.QSize(131, 17))
        self.chbZoom.setObjectName(_fromUtf8("chbZoom"))
        fpChart_II.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fpChart_II)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 38))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.muAbout = QtGui.QMenu(self.menubar)
        self.muAbout.setObjectName(_fromUtf8("muAbout"))
        fpChart_II.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fpChart_II)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fpChart_II.setStatusBar(self.statusbar)
        self.actConf = QtGui.QAction(fpChart_II)
        self.actConf.setObjectName(_fromUtf8("actConf"))
        self.menubar.addAction(self.muAbout.menuAction())

        self.retranslateUi(fpChart_II)
        QtCore.QMetaObject.connectSlotsByName(fpChart_II)

    def retranslateUi(self, fpChart_II):
        fpChart_II.setWindowTitle(_translate("fpChart_II", "Кислородомер", None))
        self.groupBox_2.setTitle(_translate("fpChart_II", "Максимальное  значение", None))
        self.groupBox_3.setTitle(_translate("fpChart_II", "Маркеры", None))
        self.tbAddMarker.setText(_translate("fpChart_II", "Добавить", None))
        self.label_12.setText(_translate("fpChart_II", "Значение", None))
        self.leVal_marker.setText(_translate("fpChart_II", "0", None))
        self.label_13.setText(_translate("fpChart_II", "Пояснение", None))
        self.rbTime.setText(_translate("fpChart_II", "Время", None))
        self.label_16.setText(_translate("fpChart_II", "Список маркеров", None))
        self.tbDelMarker.setText(_translate("fpChart_II", "Удалить", None))
        self.groupBox_5.setTitle(_translate("fpChart_II", "Значение", None))
        self.groupBox.setTitle(_translate("fpChart_II", "Минимальное  значение", None))
        self.groupBox_4.setTitle(_translate("fpChart_II", "Параметры отображения", None))
        self.chbPause.setText(_translate("fpChart_II", "Пауза отображения", None))
        self.tbResetViewPar.setText(_translate("fpChart_II", "Сброс", None))
        self.chbZoom.setText(_translate("fpChart_II", "Увеличение", None))
        self.muAbout.setTitle(_translate("fpChart_II", "?", None))
        self.actConf.setText(_translate("fpChart_II", "Градуировка", None))

from PyQt4 import Qwt5
