# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi_vs_v.0.3\forms\fpChart.ui'
#
# Created: Thu Feb 20 12:17:41 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fpChart(object):
    def setupUi(self, fpChart):
        fpChart.setObjectName(_fromUtf8("fpChart"))
        fpChart.resize(827, 712)
        fpChart.setMinimumSize(QtCore.QSize(308, 193))
        self.centralwidget = QtGui.QWidget(fpChart)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(280, 10, 261, 121))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lblVal_5 = QtGui.QLabel(self.groupBox)
        self.lblVal_5.setGeometry(QtCore.QRect(201, 70, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblVal_5.setFont(font)
        self.lblVal_5.setLineWidth(-5)
        self.lblVal_5.setText(_fromUtf8(""))
        self.lblVal_5.setObjectName(_fromUtf8("lblVal_5"))
        self.lcdMain_percent_min = QtGui.QLCDNumber(self.groupBox)
        self.lcdMain_percent_min.setGeometry(QtCore.QRect(10, 70, 181, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_percent_min.sizePolicy().hasHeightForWidth())
        self.lcdMain_percent_min.setSizePolicy(sizePolicy)
        self.lcdMain_percent_min.setSmallDecimalPoint(True)
        self.lcdMain_percent_min.setDigitCount(8)
        self.lcdMain_percent_min.setProperty("value", 0.0)
        self.lcdMain_percent_min.setProperty("intValue", 0)
        self.lcdMain_percent_min.setObjectName(_fromUtf8("lcdMain_percent_min"))
        self.lblVal_2 = QtGui.QLabel(self.groupBox)
        self.lblVal_2.setGeometry(QtCore.QRect(193, 25, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblVal_2.setFont(font)
        self.lblVal_2.setLineWidth(-5)
        self.lblVal_2.setText(_fromUtf8(""))
        self.lblVal_2.setObjectName(_fromUtf8("lblVal_2"))
        self.lcdMain_mg_min = QtGui.QLCDNumber(self.groupBox)
        self.lcdMain_mg_min.setGeometry(QtCore.QRect(10, 20, 181, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_mg_min.sizePolicy().hasHeightForWidth())
        self.lcdMain_mg_min.setSizePolicy(sizePolicy)
        self.lcdMain_mg_min.setSmallDecimalPoint(True)
        self.lcdMain_mg_min.setDigitCount(8)
        self.lcdMain_mg_min.setProperty("value", 0.0)
        self.lcdMain_mg_min.setProperty("intValue", 0)
        self.lcdMain_mg_min.setObjectName(_fromUtf8("lcdMain_mg_min"))
        self.qwtPlot = Qwt5.QwtPlot(self.centralwidget)
        self.qwtPlot.setGeometry(QtCore.QRect(10, 140, 801, 281))
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.leMain = QtGui.QLineEdit(self.centralwidget)
        self.leMain.setGeometry(QtCore.QRect(10, 700, 51, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leMain.sizePolicy().hasHeightForWidth())
        self.leMain.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.leMain.setFont(font)
        self.leMain.setFrame(True)
        self.leMain.setReadOnly(True)
        self.leMain.setObjectName(_fromUtf8("leMain"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(210, 434, 601, 231))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.tbAddMarker = QtGui.QToolButton(self.groupBox_3)
        self.tbAddMarker.setGeometry(QtCore.QRect(50, 190, 121, 31))
        self.tbAddMarker.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbAddMarker.setObjectName(_fromUtf8("tbAddMarker"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(20, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setLineWidth(-5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.leVal_marker = QtGui.QLineEdit(self.groupBox_3)
        self.leVal_marker.setGeometry(QtCore.QRect(90, 60, 81, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leVal_marker.sizePolicy().hasHeightForWidth())
        self.leVal_marker.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.leVal_marker.setFont(font)
        self.leVal_marker.setFrame(True)
        self.leVal_marker.setReadOnly(False)
        self.leVal_marker.setObjectName(_fromUtf8("leVal_marker"))
        self.leComment_marker = QtGui.QLineEdit(self.groupBox_3)
        self.leComment_marker.setGeometry(QtCore.QRect(90, 100, 81, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leComment_marker.sizePolicy().hasHeightForWidth())
        self.leComment_marker.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.leComment_marker.setFont(font)
        self.leComment_marker.setFrame(True)
        self.leComment_marker.setReadOnly(False)
        self.leComment_marker.setObjectName(_fromUtf8("leComment_marker"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(20, 110, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setLineWidth(-5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.rbCon = QtGui.QRadioButton(self.groupBox_3)
        self.rbCon.setEnabled(True)
        self.rbCon.setGeometry(QtCore.QRect(20, 20, 111, 17))
        self.rbCon.setText(_fromUtf8(""))
        self.rbCon.setCheckable(True)
        self.rbCon.setChecked(True)
        self.rbCon.setObjectName(_fromUtf8("rbCon"))
        self.rbTime = QtGui.QRadioButton(self.groupBox_3)
        self.rbTime.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.rbTime.setObjectName(_fromUtf8("rbTime"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(208, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setLineWidth(-5)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.tbDelMarker = QtGui.QToolButton(self.groupBox_3)
        self.tbDelMarker.setGeometry(QtCore.QRect(300, 190, 121, 31))
        self.tbDelMarker.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbDelMarker.setObjectName(_fromUtf8("tbDelMarker"))
        self.lwListMarker = QtGui.QListWidget(self.groupBox_3)
        self.lwListMarker.setGeometry(QtCore.QRect(200, 30, 391, 141))
        self.lwListMarker.setObjectName(_fromUtf8("lwListMarker"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 434, 181, 221))
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.chbPause = QtGui.QCheckBox(self.groupBox_4)
        self.chbPause.setGeometry(QtCore.QRect(20, 40, 131, 17))
        self.chbPause.setObjectName(_fromUtf8("chbPause"))
        self.tbResetViewPar = QtGui.QToolButton(self.groupBox_4)
        self.tbResetViewPar.setGeometry(QtCore.QRect(30, 185, 121, 31))
        self.tbResetViewPar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbResetViewPar.setObjectName(_fromUtf8("tbResetViewPar"))
        self.chbZoom = QtGui.QCheckBox(self.groupBox_4)
        self.chbZoom.setGeometry(QtCore.QRect(20, 20, 131, 17))
        self.chbZoom.setObjectName(_fromUtf8("chbZoom"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 261, 121))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.lblVal_1 = QtGui.QLabel(self.groupBox_5)
        self.lblVal_1.setGeometry(QtCore.QRect(193, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblVal_1.setFont(font)
        self.lblVal_1.setLineWidth(-5)
        self.lblVal_1.setText(_fromUtf8(""))
        self.lblVal_1.setObjectName(_fromUtf8("lblVal_1"))
        self.lcdMain_percent = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdMain_percent.setGeometry(QtCore.QRect(10, 70, 181, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_percent.sizePolicy().hasHeightForWidth())
        self.lcdMain_percent.setSizePolicy(sizePolicy)
        self.lcdMain_percent.setSmallDecimalPoint(True)
        self.lcdMain_percent.setDigitCount(8)
        self.lcdMain_percent.setProperty("value", 0.0)
        self.lcdMain_percent.setProperty("intValue", 0)
        self.lcdMain_percent.setObjectName(_fromUtf8("lcdMain_percent"))
        self.lblVal_4 = QtGui.QLabel(self.groupBox_5)
        self.lblVal_4.setGeometry(QtCore.QRect(200, 70, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblVal_4.setFont(font)
        self.lblVal_4.setLineWidth(-5)
        self.lblVal_4.setText(_fromUtf8(""))
        self.lblVal_4.setObjectName(_fromUtf8("lblVal_4"))
        self.lcdMain_mg = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdMain_mg.setGeometry(QtCore.QRect(10, 20, 181, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_mg.sizePolicy().hasHeightForWidth())
        self.lcdMain_mg.setSizePolicy(sizePolicy)
        self.lcdMain_mg.setFrameShape(QtGui.QFrame.Box)
        self.lcdMain_mg.setLineWidth(0)
        self.lcdMain_mg.setMidLineWidth(1)
        self.lcdMain_mg.setSmallDecimalPoint(True)
        self.lcdMain_mg.setNumDigits(8)
        self.lcdMain_mg.setDigitCount(8)
        self.lcdMain_mg.setProperty("value", 0.0)
        self.lcdMain_mg.setProperty("intValue", 0)
        self.lcdMain_mg.setObjectName(_fromUtf8("lcdMain_mg"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(550, 10, 261, 121))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lblVal_6 = QtGui.QLabel(self.groupBox_2)
        self.lblVal_6.setGeometry(QtCore.QRect(199, 70, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblVal_6.setFont(font)
        self.lblVal_6.setLineWidth(-5)
        self.lblVal_6.setText(_fromUtf8(""))
        self.lblVal_6.setObjectName(_fromUtf8("lblVal_6"))
        self.lcdMain_percent_max = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdMain_percent_max.setGeometry(QtCore.QRect(10, 70, 181, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_percent_max.sizePolicy().hasHeightForWidth())
        self.lcdMain_percent_max.setSizePolicy(sizePolicy)
        self.lcdMain_percent_max.setSmallDecimalPoint(True)
        self.lcdMain_percent_max.setDigitCount(8)
        self.lcdMain_percent_max.setProperty("value", 0.0)
        self.lcdMain_percent_max.setProperty("intValue", 0)
        self.lcdMain_percent_max.setObjectName(_fromUtf8("lcdMain_percent_max"))
        self.lblVal_3 = QtGui.QLabel(self.groupBox_2)
        self.lblVal_3.setGeometry(QtCore.QRect(192, 25, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblVal_3.setFont(font)
        self.lblVal_3.setLineWidth(-5)
        self.lblVal_3.setText(_fromUtf8(""))
        self.lblVal_3.setObjectName(_fromUtf8("lblVal_3"))
        self.lcdMain_mg_max = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdMain_mg_max.setGeometry(QtCore.QRect(10, 20, 181, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_mg_max.sizePolicy().hasHeightForWidth())
        self.lcdMain_mg_max.setSizePolicy(sizePolicy)
        self.lcdMain_mg_max.setSmallDecimalPoint(True)
        self.lcdMain_mg_max.setDigitCount(8)
        self.lcdMain_mg_max.setProperty("value", 0.0)
        self.lcdMain_mg_max.setProperty("intValue", 0)
        self.lcdMain_mg_max.setObjectName(_fromUtf8("lcdMain_mg_max"))
        fpChart.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fpChart)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.muAbout = QtGui.QMenu(self.menubar)
        self.muAbout.setObjectName(_fromUtf8("muAbout"))
        fpChart.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fpChart)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fpChart.setStatusBar(self.statusbar)
        self.actConf = QtGui.QAction(fpChart)
        self.actConf.setObjectName(_fromUtf8("actConf"))
        self.menubar.addAction(self.muAbout.menuAction())

        self.retranslateUi(fpChart)
        QtCore.QMetaObject.connectSlotsByName(fpChart)

    def retranslateUi(self, fpChart):
        fpChart.setWindowTitle(_translate("fpChart", "Кислородомер", None))
        self.groupBox.setTitle(_translate("fpChart", "Минимальное  значение", None))
        self.leMain.setText(_translate("fpChart", "12", None))
        self.groupBox_3.setTitle(_translate("fpChart", "Маркеры", None))
        self.tbAddMarker.setText(_translate("fpChart", "Добавить", None))
        self.label_12.setText(_translate("fpChart", "Значение", None))
        self.leVal_marker.setText(_translate("fpChart", "0", None))
        self.leComment_marker.setText(_translate("fpChart", " ", None))
        self.label_13.setText(_translate("fpChart", "Пояснение", None))
        self.rbTime.setText(_translate("fpChart", "Время", None))
        self.label_16.setText(_translate("fpChart", "Список маркеров", None))
        self.tbDelMarker.setText(_translate("fpChart", "Удалить", None))
        self.groupBox_4.setTitle(_translate("fpChart", "Параметры отображения", None))
        self.chbPause.setText(_translate("fpChart", "Пауза отображения", None))
        self.tbResetViewPar.setText(_translate("fpChart", "Сброс", None))
        self.chbZoom.setText(_translate("fpChart", "Увеличение", None))
        self.groupBox_5.setTitle(_translate("fpChart", "Значение", None))
        self.groupBox_2.setTitle(_translate("fpChart", "Максимальное  значение", None))
        self.muAbout.setTitle(_translate("fpChart", "?", None))
        self.actConf.setText(_translate("fpChart", "Градуировка", None))

from PyQt4 import Qwt5
