# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi (4)\svi\forms\fpCond_2.ui'
#
# Created: Mon Sep 17 15:59:15 2018
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fpCond_Compact(object):
    def setupUi(self, fpCond_Compact):
        fpCond_Compact.setObjectName(_fromUtf8("fpCond_Compact"))
        fpCond_Compact.resize(536, 685)
        fpCond_Compact.setMinimumSize(QtCore.QSize(536, 685))
        fpCond_Compact.setMaximumSize(QtCore.QSize(4000, 2560))
        self.centralwidget = QtGui.QWidget(fpCond_Compact)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lblEd_3 = QtGui.QLabel(self.centralwidget)
        self.lblEd_3.setGeometry(QtCore.QRect(170, 280, 231, 41))
        self.lblEd_3.setMinimumSize(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lblEd_3.setFont(font)
        self.lblEd_3.setObjectName(_fromUtf8("lblEd_3"))
        self.lcdMain_3 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdMain_3.setGeometry(QtCore.QRect(10, 280, 131, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_3.sizePolicy().hasHeightForWidth())
        self.lcdMain_3.setSizePolicy(sizePolicy)
        self.lcdMain_3.setMinimumSize(QtCore.QSize(2, 2))
        self.lcdMain_3.setSmallDecimalPoint(True)
        self.lcdMain_3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdMain_3.setProperty("value", 0.0)
        self.lcdMain_3.setProperty("intValue", 0)
        self.lcdMain_3.setObjectName(_fromUtf8("lcdMain_3"))
        self.lcdMain = QtGui.QLCDNumber(self.centralwidget)
        self.lcdMain.setGeometry(QtCore.QRect(10, 40, 261, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain.sizePolicy().hasHeightForWidth())
        self.lcdMain.setSizePolicy(sizePolicy)
        self.lcdMain.setMinimumSize(QtCore.QSize(151, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcdMain.setPalette(palette)
        self.lcdMain.setSmallDecimalPoint(True)
        self.lcdMain.setNumDigits(5)
        self.lcdMain.setDigitCount(5)
        self.lcdMain.setProperty("value", -123.0)
        self.lcdMain.setProperty("intValue", -123)
        self.lcdMain.setObjectName(_fromUtf8("lcdMain"))
        self.lblProfilName = QtGui.QLabel(self.centralwidget)
        self.lblProfilName.setGeometry(QtCore.QRect(120, 6, 231, 21))
        self.lblProfilName.setMinimumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblProfilName.setFont(font)
        self.lblProfilName.setLineWidth(-5)
        self.lblProfilName.setObjectName(_fromUtf8("lblProfilName"))
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(10, 1, 121, 31))
        self.label_31.setMinimumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setLineWidth(-5)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.lblEd = QtGui.QLabel(self.centralwidget)
        self.lblEd.setGeometry(QtCore.QRect(300, 70, 221, 51))
        self.lblEd.setMinimumSize(QtCore.QSize(141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lblEd.setFont(font)
        self.lblEd.setObjectName(_fromUtf8("lblEd"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 150, 221, 21))
        self.label_8.setMinimumSize(QtCore.QSize(111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setLineWidth(-5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lcdMain_2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdMain_2.setGeometry(QtCore.QRect(10, 190, 131, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_2.sizePolicy().hasHeightForWidth())
        self.lcdMain_2.setSizePolicy(sizePolicy)
        self.lcdMain_2.setMinimumSize(QtCore.QSize(2, 2))
        self.lcdMain_2.setLineWidth(1)
        self.lcdMain_2.setSmallDecimalPoint(True)
        self.lcdMain_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdMain_2.setProperty("value", -1234.0)
        self.lcdMain_2.setProperty("intValue", -1234)
        self.lcdMain_2.setObjectName(_fromUtf8("lcdMain_2"))
        self.lblEd_2 = QtGui.QLabel(self.centralwidget)
        self.lblEd_2.setGeometry(QtCore.QRect(175, 192, 231, 51))
        self.lblEd_2.setMinimumSize(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lblEd_2.setFont(font)
        self.lblEd_2.setObjectName(_fromUtf8("lblEd_2"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 240, 191, 31))
        self.label_9.setMinimumSize(QtCore.QSize(111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setLineWidth(-5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 330, 371, 221))
        self.groupBox.setMinimumSize(QtCore.QSize(2, 105))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.rbAutoT = QtGui.QRadioButton(self.groupBox)
        self.rbAutoT.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.rbAutoT.setMinimumSize(QtCore.QSize(107, 17))
        self.rbAutoT.setObjectName(_fromUtf8("rbAutoT"))
        self.rbManualT = QtGui.QRadioButton(self.groupBox)
        self.rbManualT.setGeometry(QtCore.QRect(10, 100, 181, 31))
        self.rbManualT.setMinimumSize(QtCore.QSize(87, 17))
        self.rbManualT.setObjectName(_fromUtf8("rbManualT"))
        self.rbOffT = QtGui.QRadioButton(self.groupBox)
        self.rbOffT.setGeometry(QtCore.QRect(10, 160, 181, 31))
        self.rbOffT.setMinimumSize(QtCore.QSize(82, 17))
        self.rbOffT.setObjectName(_fromUtf8("rbOffT"))
        self.leTemp = QtGui.QLineEdit(self.groupBox)
        self.leTemp.setGeometry(QtCore.QRect(220, 100, 81, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leTemp.sizePolicy().hasHeightForWidth())
        self.leTemp.setSizePolicy(sizePolicy)
        self.leTemp.setMinimumSize(QtCore.QSize(6, 24))
        self.leTemp.setMaximumSize(QtCore.QSize(610, 310))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.leTemp.setFont(font)
        self.leTemp.setFrame(True)
        self.leTemp.setObjectName(_fromUtf8("leTemp"))
        self.tbEnterT = QtGui.QToolButton(self.groupBox)
        self.tbEnterT.setGeometry(QtCore.QRect(210, 160, 141, 51))
        self.tbEnterT.setMinimumSize(QtCore.QSize(4, 4))
        self.tbEnterT.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbEnterT.setObjectName(_fromUtf8("tbEnterT"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(320, 90, 41, 41))
        self.label.setMinimumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 0, 111, 31))
        self.label_5.setMinimumSize(QtCore.QSize(19, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lblID = QtGui.QLabel(self.centralwidget)
        self.lblID.setGeometry(QtCore.QRect(440, 0, 81, 31))
        self.lblID.setMinimumSize(QtCore.QSize(19, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.lblID.setFont(font)
        self.lblID.setObjectName(_fromUtf8("lblID"))
        self.tbSaveToNotepad_ = QtGui.QToolButton(self.centralwidget)
        self.tbSaveToNotepad_.setGeometry(QtCore.QRect(260, 570, 251, 51))
        self.tbSaveToNotepad_.setMinimumSize(QtCore.QSize(71, 31))
        self.tbSaveToNotepad_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbSaveToNotepad_.setObjectName(_fromUtf8("tbSaveToNotepad_"))
        fpCond_Compact.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fpCond_Compact)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 38))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        fpCond_Compact.setMenuBar(self.menubar)
        self.actConf = QtGui.QAction(fpCond_Compact)
        self.actConf.setObjectName(_fromUtf8("actConf"))
        self.action = QtGui.QAction(fpCond_Compact)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_2 = QtGui.QAction(fpCond_Compact)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.action_3 = QtGui.QAction(fpCond_Compact)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.action_4 = QtGui.QAction(fpCond_Compact)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action_5 = QtGui.QAction(fpCond_Compact)
        self.action_5.setObjectName(_fromUtf8("action_5"))

        self.retranslateUi(fpCond_Compact)
        QtCore.QMetaObject.connectSlotsByName(fpCond_Compact)

    def retranslateUi(self, fpCond_Compact):
        fpCond_Compact.setWindowTitle(_translate("fpCond_Compact", "Кондуктометр", None))
        self.lblEd_3.setText(_translate("fpCond_Compact", "<html><head/><body><p><span style=\" font-size:12pt;\">Ед.Изм</span></p><p><br/></p></body></html>", None))
        self.lblProfilName.setText(_translate("fpCond_Compact", "КОНДУКТОМЕТР 1", None))
        self.label_31.setText(_translate("fpCond_Compact", "Профиль", None))
        self.lblEd.setText(_translate("fpCond_Compact", "<html><head/><body><p>мкСм/см</p></body></html>", None))
        self.label_8.setText(_translate("fpCond_Compact", "Содержание NaCl", None))
        self.lblEd_2.setText(_translate("fpCond_Compact", "<html><head/><body><p><span style=\" font-size:12pt;\">Ед.Изм</span></p><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>", None))
        self.label_9.setText(_translate("fpCond_Compact", "Сопротивление", None))
        self.groupBox.setTitle(_translate("fpCond_Compact", "Термокомпенсация", None))
        self.rbAutoT.setText(_translate("fpCond_Compact", "Автоматическая", None))
        self.rbManualT.setText(_translate("fpCond_Compact", "Ручной ввод", None))
        self.rbOffT.setText(_translate("fpCond_Compact", "Отключить", None))
        self.leTemp.setText(_translate("fpCond_Compact", "12", None))
        self.tbEnterT.setText(_translate("fpCond_Compact", "Ввод", None))
        self.label.setText(_translate("fpCond_Compact", "<sup>o</sup>С", None))
        self.label_5.setText(_translate("fpCond_Compact", "Проба", None))
        self.lblID.setText(_translate("fpCond_Compact", "ID", None))
        self.tbSaveToNotepad_.setText(_translate("fpCond_Compact", "Записать в блокнот", None))
        self.actConf.setText(_translate("fpCond_Compact", "Градуировка", None))
        self.action.setText(_translate("fpCond_Compact", "Градуировка", None))
        self.action_2.setText(_translate("fpCond_Compact", "Сохранить профиль", None))
        self.action_3.setText(_translate("fpCond_Compact", "Редактировать профиль", None))
        self.action_4.setText(_translate("fpCond_Compact", "График", None))
        self.action_5.setText(_translate("fpCond_Compact", "Таблица результатов", None))

