# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ormet\source\svi_vs_v.0.4\forms\fpIon.ui'
#
# Created: Fri Mar  6 15:17:50 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fpIon(object):
    def setupUi(self, fpIon):
        fpIon.setObjectName(_fromUtf8("fpIon"))
        fpIon.resize(401, 479)
        fpIon.setMinimumSize(QtCore.QSize(401, 479))
        self.centralwidget = QtGui.QWidget(fpIon)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setMinimumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setLineWidth(-5)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setMinimumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setLineWidth(-5)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout.addWidget(self.label_34, 0, 1, 1, 3)
        self.lblProfilName = QtGui.QLabel(self.centralwidget)
        self.lblProfilName.setMinimumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblProfilName.setFont(font)
        self.lblProfilName.setLineWidth(-5)
        self.lblProfilName.setObjectName(_fromUtf8("lblProfilName"))
        self.gridLayout.addWidget(self.lblProfilName, 1, 0, 1, 1)
        self.lblDateTime = QtGui.QLabel(self.centralwidget)
        self.lblDateTime.setMinimumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblDateTime.setFont(font)
        self.lblDateTime.setLineWidth(-5)
        self.lblDateTime.setObjectName(_fromUtf8("lblDateTime"))
        self.gridLayout.addWidget(self.lblDateTime, 1, 1, 1, 3)
        self.lcdMain = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain.sizePolicy().hasHeightForWidth())
        self.lcdMain.setSizePolicy(sizePolicy)
        self.lcdMain.setMinimumSize(QtCore.QSize(201, 41))
        self.lcdMain.setObjectName(_fromUtf8("lcdMain"))
        self.gridLayout.addWidget(self.lcdMain, 2, 0, 1, 2)
        self.llMain = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.llMain.sizePolicy().hasHeightForWidth())
        self.llMain.setSizePolicy(sizePolicy)
        self.llMain.setMinimumSize(QtCore.QSize(51, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(20)
        self.llMain.setFont(font)
        self.llMain.setFrameShape(QtGui.QFrame.NoFrame)
        self.llMain.setFrameShadow(QtGui.QFrame.Sunken)
        self.llMain.setObjectName(_fromUtf8("llMain"))
        self.gridLayout.addWidget(self.llMain, 2, 2, 1, 2)
        self.lcdMain_2 = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_2.sizePolicy().hasHeightForWidth())
        self.lcdMain_2.setSizePolicy(sizePolicy)
        self.lcdMain_2.setMinimumSize(QtCore.QSize(201, 41))
        self.lcdMain_2.setObjectName(_fromUtf8("lcdMain_2"))
        self.gridLayout.addWidget(self.lcdMain_2, 3, 0, 1, 2)
        self.llMain_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.llMain_2.sizePolicy().hasHeightForWidth())
        self.llMain_2.setSizePolicy(sizePolicy)
        self.llMain_2.setMinimumSize(QtCore.QSize(51, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(20)
        self.llMain_2.setFont(font)
        self.llMain_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.llMain_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.llMain_2.setObjectName(_fromUtf8("llMain_2"))
        self.gridLayout.addWidget(self.llMain_2, 3, 2, 1, 2)
        self.lcdMain_3 = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_3.sizePolicy().hasHeightForWidth())
        self.lcdMain_3.setSizePolicy(sizePolicy)
        self.lcdMain_3.setMinimumSize(QtCore.QSize(201, 41))
        self.lcdMain_3.setObjectName(_fromUtf8("lcdMain_3"))
        self.gridLayout.addWidget(self.lcdMain_3, 4, 0, 1, 2)
        self.cbEd_3 = QtGui.QComboBox(self.centralwidget)
        self.cbEd_3.setMinimumSize(QtCore.QSize(171, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cbEd_3.setFont(font)
        self.cbEd_3.setAutoFillBackground(True)
        self.cbEd_3.setObjectName(_fromUtf8("cbEd_3"))
        self.gridLayout.addWidget(self.cbEd_3, 4, 2, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(381, 121))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.rbAutoT = QtGui.QRadioButton(self.groupBox)
        self.rbAutoT.setGeometry(QtCore.QRect(10, 24, 111, 17))
        self.rbAutoT.setMinimumSize(QtCore.QSize(111, 17))
        self.rbAutoT.setObjectName(_fromUtf8("rbAutoT"))
        self.rbManualT = QtGui.QRadioButton(self.groupBox)
        self.rbManualT.setGeometry(QtCore.QRect(10, 54, 82, 17))
        self.rbManualT.setMinimumSize(QtCore.QSize(82, 17))
        self.rbManualT.setObjectName(_fromUtf8("rbManualT"))
        self.rbOffT = QtGui.QRadioButton(self.groupBox)
        self.rbOffT.setGeometry(QtCore.QRect(10, 84, 82, 17))
        self.rbOffT.setMinimumSize(QtCore.QSize(82, 17))
        self.rbOffT.setObjectName(_fromUtf8("rbOffT"))
        self.leTemp = QtGui.QLineEdit(self.groupBox)
        self.leTemp.setGeometry(QtCore.QRect(130, 24, 61, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leTemp.sizePolicy().hasHeightForWidth())
        self.leTemp.setSizePolicy(sizePolicy)
        self.leTemp.setMinimumSize(QtCore.QSize(61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.leTemp.setFont(font)
        self.leTemp.setFrame(True)
        self.leTemp.setObjectName(_fromUtf8("leTemp"))
        self.tbEnterT = QtGui.QToolButton(self.groupBox)
        self.tbEnterT.setGeometry(QtCore.QRect(130, 74, 81, 31))
        self.tbEnterT.setMinimumSize(QtCore.QSize(81, 31))
        self.tbEnterT.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbEnterT.setObjectName(_fromUtf8("tbEnterT"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(210, 24, 31, 31))
        self.label_3.setMinimumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.groupBox, 5, 0, 1, 4)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(231, 61))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.leID = QtGui.QLineEdit(self.groupBox_2)
        self.leID.setGeometry(QtCore.QRect(40, 20, 81, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leID.sizePolicy().hasHeightForWidth())
        self.leID.setSizePolicy(sizePolicy)
        self.leID.setMinimumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.leID.setFont(font)
        self.leID.setFrame(True)
        self.leID.setObjectName(_fromUtf8("leID"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.label_4.setMinimumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tbSaveToNotepad_ = QtGui.QPushButton(self.groupBox_2)
        self.tbSaveToNotepad_.setGeometry(QtCore.QRect(140, 20, 81, 31))
        self.tbSaveToNotepad_.setMinimumSize(QtCore.QSize(81, 31))
        self.tbSaveToNotepad_.setObjectName(_fromUtf8("tbSaveToNotepad_"))
        self.gridLayout.addWidget(self.groupBox_2, 6, 0, 1, 3)
        self.tbSelectProfil = QtGui.QToolButton(self.centralwidget)
        self.tbSelectProfil.setMinimumSize(QtCore.QSize(121, 31))
        self.tbSelectProfil.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbSelectProfil.setObjectName(_fromUtf8("tbSelectProfil"))
        self.gridLayout.addWidget(self.tbSelectProfil, 7, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        fpIon.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fpIon)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 401, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.muAbout = QtGui.QMenu(self.menubar)
        self.muAbout.setObjectName(_fromUtf8("muAbout"))
        fpIon.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fpIon)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fpIon.setStatusBar(self.statusbar)
        self.actConf = QtGui.QAction(fpIon)
        self.actConf.setObjectName(_fromUtf8("actConf"))
        self.action = QtGui.QAction(fpIon)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_2 = QtGui.QAction(fpIon)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.action_3 = QtGui.QAction(fpIon)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.menubar.addAction(self.muAbout.menuAction())

        self.retranslateUi(fpIon)
        QtCore.QMetaObject.connectSlotsByName(fpIon)

    def retranslateUi(self, fpIon):
        fpIon.setWindowTitle(_translate("fpIon", "Иономер", None))
        self.label_31.setText(_translate("fpIon", "Профиль измерения", None))
        self.label_34.setText(_translate("fpIon", "Дата и время", None))
        self.lblProfilName.setText(_translate("fpIon", "Иономер", None))
        self.lblDateTime.setText(_translate("fpIon", "11.11.2011 11-11-11", None))
        self.llMain.setText(_translate("fpIon", "pX", None))
        self.llMain_2.setText(_translate("fpIon", "мВ", None))
        self.groupBox.setTitle(_translate("fpIon", "Термокомпенсация", None))
        self.rbAutoT.setText(_translate("fpIon", "Автоматическая", None))
        self.rbManualT.setText(_translate("fpIon", "Ручной ввод", None))
        self.rbOffT.setText(_translate("fpIon", "Отключить", None))
        self.leTemp.setText(_translate("fpIon", "12", None))
        self.tbEnterT.setText(_translate("fpIon", "Ввод", None))
        self.label_3.setText(_translate("fpIon", "<sup>o</sup>С", None))
        self.groupBox_2.setTitle(_translate("fpIon", "Запись в блокнот", None))
        self.leID.setText(_translate("fpIon", "12", None))
        self.label_4.setText(_translate("fpIon", "ID", None))
        self.tbSaveToNotepad_.setText(_translate("fpIon", "Записать", None))
        self.tbSelectProfil.setText(_translate("fpIon", " К Выбору профиля", None))
        self.muAbout.setTitle(_translate("fpIon", "?", None))
        self.actConf.setText(_translate("fpIon", "Градуировка", None))
        self.action.setText(_translate("fpIon", "Градиуровка", None))
        self.action_2.setText(_translate("fpIon", "Редактировать профиль", None))
        self.action_3.setText(_translate("fpIon", "Сохранить профиль", None))

