# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\__2018\NB2\svi\forms\fpO_2_2.ui'
#
# Created: Thu Sep 20 16:21:04 2018
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fpO_2(object):
    def setupUi(self, fpO_2):
        fpO_2.setObjectName(_fromUtf8("fpO_2"))
        fpO_2.resize(821, 744)
        fpO_2.setMinimumSize(QtCore.QSize(821, 744))
        fpO_2.setMaximumSize(QtCore.QSize(821, 744))
        self.centralwidget = QtGui.QWidget(fpO_2)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lcdMain = QtGui.QLCDNumber(self.centralwidget)
        self.lcdMain.setGeometry(QtCore.QRect(10, 50, 261, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain.sizePolicy().hasHeightForWidth())
        self.lcdMain.setSizePolicy(sizePolicy)
        self.lcdMain.setMinimumSize(QtCore.QSize(151, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcdMain.setPalette(palette)
        self.lcdMain.setSmallDecimalPoint(True)
        self.lcdMain.setProperty("value", 0.0)
        self.lcdMain.setProperty("intValue", 0)
        self.lcdMain.setObjectName(_fromUtf8("lcdMain"))
        self.lblEd = QtGui.QLabel(self.centralwidget)
        self.lblEd.setGeometry(QtCore.QRect(280, 80, 191, 61))
        self.lblEd.setMinimumSize(QtCore.QSize(4, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lblEd.setFont(font)
        self.lblEd.setObjectName(_fromUtf8("lblEd"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 280, 341, 251))
        self.groupBox.setMinimumSize(QtCore.QSize(2, 105))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.rbAutoT = QtGui.QRadioButton(self.groupBox)
        self.rbAutoT.setGeometry(QtCore.QRect(10, 46, 221, 31))
        self.rbAutoT.setMinimumSize(QtCore.QSize(107, 17))
        self.rbAutoT.setObjectName(_fromUtf8("rbAutoT"))
        self.rbManualT = QtGui.QRadioButton(self.groupBox)
        self.rbManualT.setGeometry(QtCore.QRect(10, 110, 211, 31))
        self.rbManualT.setMinimumSize(QtCore.QSize(87, 17))
        self.rbManualT.setObjectName(_fromUtf8("rbManualT"))
        self.rbOffT = QtGui.QRadioButton(self.groupBox)
        self.rbOffT.setGeometry(QtCore.QRect(10, 180, 151, 31))
        self.rbOffT.setMinimumSize(QtCore.QSize(82, 17))
        self.rbOffT.setObjectName(_fromUtf8("rbOffT"))
        self.leTemp = QtGui.QLineEdit(self.groupBox)
        self.leTemp.setGeometry(QtCore.QRect(200, 110, 81, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leTemp.sizePolicy().hasHeightForWidth())
        self.leTemp.setSizePolicy(sizePolicy)
        self.leTemp.setMinimumSize(QtCore.QSize(6, 24))
        self.leTemp.setMaximumSize(QtCore.QSize(610, 310))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.leTemp.setFont(font)
        self.leTemp.setFrame(True)
        self.leTemp.setObjectName(_fromUtf8("leTemp"))
        self.tbEnterT = QtGui.QToolButton(self.groupBox)
        self.tbEnterT.setGeometry(QtCore.QRect(180, 170, 141, 51))
        self.tbEnterT.setMinimumSize(QtCore.QSize(4, 4))
        self.tbEnterT.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbEnterT.setObjectName(_fromUtf8("tbEnterT"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(290, 110, 41, 41))
        self.label.setMinimumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 10, 121, 31))
        self.label_5.setMinimumSize(QtCore.QSize(19, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lblID = QtGui.QLabel(self.centralwidget)
        self.lblID.setGeometry(QtCore.QRect(500, 10, 251, 31))
        self.lblID.setMinimumSize(QtCore.QSize(19, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.lblID.setFont(font)
        self.lblID.setObjectName(_fromUtf8("lblID"))
        self.lcdMain_2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdMain_2.setGeometry(QtCore.QRect(10, 150, 261, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdMain_2.sizePolicy().hasHeightForWidth())
        self.lcdMain_2.setSizePolicy(sizePolicy)
        self.lcdMain_2.setMinimumSize(QtCore.QSize(151, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcdMain_2.setPalette(palette)
        self.lcdMain_2.setSmallDecimalPoint(True)
        self.lcdMain_2.setProperty("value", 0.0)
        self.lcdMain_2.setProperty("intValue", 0)
        self.lcdMain_2.setObjectName(_fromUtf8("lcdMain_2"))
        self.lblEd_2 = QtGui.QLabel(self.centralwidget)
        self.lblEd_2.setGeometry(QtCore.QRect(280, 170, 181, 61))
        self.lblEd_2.setMinimumSize(QtCore.QSize(4, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lblEd_2.setFont(font)
        self.lblEd_2.setObjectName(_fromUtf8("lblEd_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 280, 411, 251))
        self.groupBox_2.setMinimumSize(QtCore.QSize(2, 105))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.rbManualP = QtGui.QRadioButton(self.groupBox_2)
        self.rbManualP.setGeometry(QtCore.QRect(10, 110, 171, 31))
        self.rbManualP.setMinimumSize(QtCore.QSize(87, 17))
        self.rbManualP.setObjectName(_fromUtf8("rbManualP"))
        self.rbOffP = QtGui.QRadioButton(self.groupBox_2)
        self.rbOffP.setGeometry(QtCore.QRect(10, 180, 181, 31))
        self.rbOffP.setMinimumSize(QtCore.QSize(82, 17))
        self.rbOffP.setObjectName(_fromUtf8("rbOffP"))
        self.lePressure = QtGui.QLineEdit(self.groupBox_2)
        self.lePressure.setGeometry(QtCore.QRect(190, 110, 131, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lePressure.sizePolicy().hasHeightForWidth())
        self.lePressure.setSizePolicy(sizePolicy)
        self.lePressure.setMinimumSize(QtCore.QSize(6, 24))
        self.lePressure.setMaximumSize(QtCore.QSize(6179, 317))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.lePressure.setFont(font)
        self.lePressure.setFrame(True)
        self.lePressure.setObjectName(_fromUtf8("lePressure"))
        self.tbEnterP = QtGui.QToolButton(self.groupBox_2)
        self.tbEnterP.setGeometry(QtCore.QRect(180, 170, 151, 51))
        self.tbEnterP.setMinimumSize(QtCore.QSize(4, 4))
        self.tbEnterP.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbEnterP.setObjectName(_fromUtf8("tbEnterP"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(340, 103, 51, 51))
        self.label_2.setMinimumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.rbAutoP = QtGui.QRadioButton(self.groupBox_2)
        self.rbAutoP.setGeometry(QtCore.QRect(10, 40, 221, 41))
        self.rbAutoP.setMinimumSize(QtCore.QSize(107, 17))
        self.rbAutoP.setObjectName(_fromUtf8("rbAutoP"))
        self.tbSaveToNotepad = QtGui.QToolButton(self.centralwidget)
        self.tbSaveToNotepad.setGeometry(QtCore.QRect(490, 610, 251, 51))
        self.tbSaveToNotepad.setMinimumSize(QtCore.QSize(71, 31))
        self.tbSaveToNotepad.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbSaveToNotepad.setObjectName(_fromUtf8("tbSaveToNotepad"))
        self.leSalt = QtGui.QLineEdit(self.centralwidget)
        self.leSalt.setGeometry(QtCore.QRect(230, 550, 84, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leSalt.sizePolicy().hasHeightForWidth())
        self.leSalt.setSizePolicy(sizePolicy)
        self.leSalt.setMinimumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.leSalt.setFont(font)
        self.leSalt.setFrame(True)
        self.leSalt.setReadOnly(True)
        self.leSalt.setObjectName(_fromUtf8("leSalt"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 560, 211, 21))
        self.label_6.setMinimumSize(QtCore.QSize(111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setLineWidth(-5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 550, 111, 41))
        self.label_4.setMinimumSize(QtCore.QSize(61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        fpO_2.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fpO_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 38))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        fpO_2.setMenuBar(self.menubar)
        self.actConf = QtGui.QAction(fpO_2)
        self.actConf.setObjectName(_fromUtf8("actConf"))
        self.action = QtGui.QAction(fpO_2)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_2 = QtGui.QAction(fpO_2)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.action_3 = QtGui.QAction(fpO_2)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.action_4 = QtGui.QAction(fpO_2)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action_5 = QtGui.QAction(fpO_2)
        self.action_5.setObjectName(_fromUtf8("action_5"))

        self.retranslateUi(fpO_2)
        QtCore.QMetaObject.connectSlotsByName(fpO_2)

    def retranslateUi(self, fpO_2):
        fpO_2.setWindowTitle(_translate("fpO_2", " Кислородомер", None))
        self.lblEd.setText(_translate("fpO_2", "Ед.Изм<html><head/><body><p/></body></html>", None))
        self.groupBox.setTitle(_translate("fpO_2", "Термокомпенсация", None))
        self.rbAutoT.setText(_translate("fpO_2", "Автоматическая", None))
        self.rbManualT.setText(_translate("fpO_2", "Ручной ввод", None))
        self.rbOffT.setText(_translate("fpO_2", "Отключить", None))
        self.leTemp.setText(_translate("fpO_2", "12", None))
        self.tbEnterT.setText(_translate("fpO_2", "Ввод", None))
        self.label.setText(_translate("fpO_2", "<html><head/><body><p><span style=\" font-size:8pt; vertical-align:super;\">o</span><span style=\" font-size:8pt;\">С</span></p></body></html>", None))
        self.label_5.setText(_translate("fpO_2", "Проба", None))
        self.lblID.setText(_translate("fpO_2", "ID", None))
        self.lblEd_2.setText(_translate("fpO_2", "Ед.Изм<html><head/><body><p/></body></html>", None))
        self.groupBox_2.setTitle(_translate("fpO_2", "Компенсация давления", None))
        self.rbManualP.setText(_translate("fpO_2", "Ручной ввод", None))
        self.rbOffP.setText(_translate("fpO_2", "Отключить", None))
        self.lePressure.setText(_translate("fpO_2", "100.00", None))
        self.tbEnterP.setText(_translate("fpO_2", "Ввод", None))
        self.label_2.setText(_translate("fpO_2", "кПа", None))
        self.rbAutoP.setText(_translate("fpO_2", "Автоматическая", None))
        self.tbSaveToNotepad.setText(_translate("fpO_2", "Записать в блокнот", None))
        self.leSalt.setText(_translate("fpO_2", "0", None))
        self.label_6.setText(_translate("fpO_2", "Содержание соли", None))
        self.label_4.setText(_translate("fpO_2", "<html><head/><body><p>мг/дм<span style=\" vertical-align:super;\">3</span></p></body></html>", None))
        self.actConf.setText(_translate("fpO_2", "Градуировка", None))
        self.action.setText(_translate("fpO_2", "Градуировка", None))
        self.action_2.setText(_translate("fpO_2", "Сохранить профиль", None))
        self.action_3.setText(_translate("fpO_2", "Редактировать профиль", None))
        self.action_4.setText(_translate("fpO_2", "График", None))
        self.action_5.setText(_translate("fpO_2", "Таблица результатов", None))

